USE [SFGPRODU]
GO


IF type_id('[WSXML_SFG].[COMISIONNIVEL]') IS NOT NULL
        DROP TYPE [WSXML_SFG].[COMISIONNIVEL]

CREATE TYPE [WSXML_SFG].[COMISIONNIVEL] AS TABLE(
	[ID] [int] NOT NULL,
	[RANGOINICIAL] [float] NULL,
	[RANGOFINAL] [float] NULL,
	[VALORPORCENTUAL] [float] NULL,
	[VALORTRANSACCIONAL] [float] NULL
)
GO


IF type_id('[WSXML_SFG].[NUMBERARRAYIDCODIGO]') IS NOT NULL
        DROP TYPE [WSXML_SFG].[NUMBERARRAYIDCODIGO]
		
CREATE TYPE [WSXML_SFG].[NUMBERARRAYIDCODIGO] AS TABLE(
	[IDVALUE] [numeric](38, 0) NULL,
	[CODIGO] [numeric](38, 0) NULL
)
GO



IF type_id('[WSXML_SFG].[ADVANCEDCOMMISSION]') IS NOT NULL
        DROP TYPE [WSXML_SFG].[ADVANCEDCOMMISSION]
		
CREATE TYPE [WSXML_SFG].[ADVANCEDCOMMISSION] AS TABLE(
	[ID] [numeric](38, 0) NULL,
	[CODRANGOCOMISION] [numeric](38, 0) NULL,
	[CODTIPOCOMISION] [numeric](38, 0) NULL,
	[COMISIONANTICIPO] [numeric](38, 0) NULL,
	[VALORPORCENTUAL] [float] NULL,
	[VALORTRANSACCIONAL] [float] NULL
)
GO


IF type_id('[WSXML_SFG].[IDVALUENUMERIC]') IS NOT NULL
        DROP TYPE [WSXML_SFG].[IDVALUENUMERIC]

CREATE TYPE [WSXML_SFG].[IDVALUENUMERIC] AS TABLE(
	[ID] [numeric](38, 0) NULL,
	[VALUE] [NUMERIC](38,0) NULL
)
GO



IF type_id('[WSXML_SFG].[DISTRIBUCIONREC]') IS NOT NULL
        DROP TYPE [WSXML_SFG].[DISTRIBUCIONREC]

CREATE TYPE [WSXML_SFG].[DISTRIBUCIONREC] AS TABLE(
	ID_PUNTODEVENTA  NUMERIC(38,0),
	CODMAESTROFACTURACIONPDV NUMERIC(38,0),
	SALDOACTUAL FLOAT
)
GO