USE SFGPRODU;
--  DDL for Function AGRUPACION_CABEZA_F
--------------------------------------------------------

  IF OBJECT_ID('WSXML_SFG.AGRUPACION_CABEZA_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.AGRUPACION_CABEZA_F;
GO

  CREATE FUNCTION WSXML_SFG.AGRUPACION_CABEZA_F (@pk_ID_AGRUPACIONPUNTODEVENTA NVARCHAR(2000)) RETURNS NUMERIC(22,0) AS
 BEGIN
	DECLARE @result NUMERIC(22,0);
	DECLARE @ROWCOUNT NUMERIC(22,0) = 0;
	
	SELECT @result = CODPUNTODEVENTACABEZA FROM WSXML_SFG.AGRUPACIONPUNTODEVENTA C
		INNER JOIN WSXML_SFG.PUNTODEVENTA P ON (P.ID_PUNTODEVENTA = C.CODPUNTODEVENTACABEZA)
	WHERE ID_AGRUPACIONPUNTODEVENTA = @pk_ID_AGRUPACIONPUNTODEVENTA AND P.ACTIVE = 1;
	
	SET @ROWCOUNT = @@ROWCOUNT
	IF @result IS NULL BEGIN
		SELECT @result = MIN(ID_PUNTODEVENTA) FROM WSXML_SFG.PUNTODEVENTA
		WHERE CODAGRUPACIONPUNTODEVENTA = @pk_ID_AGRUPACIONPUNTODEVENTA
		  AND ACTIVE = 1;
		
		SET @ROWCOUNT = @@ROWCOUNT
	END 
  
	IF @ROWCOUNT = 0 BEGIN
		--SFGTMPTRACE.TraceLog('Head of Chain ' + ISNULL(@pk_ID_AGRUPACIONPUNTODEVENTA, '') + ' not found');
		RETURN 0;
	END
  
  RETURN @result;
  
END; 
GO