USE SFGPRODU;
--  DDL for Function ALIADOFROMNAME_F
--------------------------------------------------------

IF OBJECT_ID('WSXML_SFG.ALIADOFROMNAME_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.ALIADOFROMNAME_F;
GO

CREATE FUNCTION WSXML_SFG.ALIADOFROMNAME_F (@p_NOMALIADOESTRATEGICO VARCHAR(4000) /* Use -meta option ALIADOESTRATEGICO.NOMALIADOESTRATEGICO%TYPE */) 
RETURNS NUMERIC(22,0) AS
 BEGIN
  DECLARE @returnvalue NUMERIC(22,0);
 
  SELECT @returnvalue = ID_ALIADOESTRATEGICO FROM WSXML_SFG.ALIADOESTRATEGICO WHERE NOMALIADOESTRATEGICO = @p_NOMALIADOESTRATEGICO;

  IF @@ROWCOUNT = 0 BEGIN
	--RAISERROR('-20054 El aliado especificado no existe', 16, 1);
	RETURN CAST('-20054: El aliado especificado no existe' AS INT);
  END
  RETURN @returnvalue;
END;

