USE SFGPRODU;
--  DDL for Function ARCHIVONOMBRE_CTRLPAGO_F
--------------------------------------------------------

IF OBJECT_ID('WSXML_SFG.ARCHIVONOMBRE_CTRLPAGO_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.ARCHIVONOMBRE_CTRLPAGO_F;
GO

CREATE FUNCTION WSXML_SFG.ARCHIVONOMBRE_CTRLPAGO_F (@pk_ID_CTRLPAGO NUMERIC(22,0)) RETURNS NVARCHAR(2000) AS
BEGIN
	DECLARE @result VARCHAR(300);
 
	SELECT @result = NOMBREARCHIVO 
	FROM WSXML_SFG.ARCHIVOPAGO
	WHERE ID_ARCHIVOPAGO = (
		SELECT CODARCHIVOPAGO FROM WSXML_SFG.CTRLPAGO WHERE ID_CTRLPAGO = @pk_ID_CTRLPAGO
		);
	RETURN(@result);
END

