USE SFGPRODU;
--  DDL for Function COMISIONFORMATSIMPLE_F
--------------------------------------------------------

  IF OBJECT_ID('WSXML_SFG.COMISIONFORMATSIMPLE_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.COMISIONFORMATSIMPLE_F;
GO

  CREATE FUNCTION WSXML_SFG.COMISIONFORMATSIMPLE_F (@p_TIPO NUMERIC(22,0), @p_VALORPORCENTUAL FLOAT, @p_VALORTRANSACCIONAL FLOAT) RETURNS NVARCHAR(2000) AS
 BEGIN
  DECLARE @cCOMMISSIONNAME NVARCHAR(1000);
 
  IF @p_TIPO = 1 BEGIN    -- Porcentual
    SELECT @cCOMMISSIONNAME = ISNULL(RTRIM(LTRIM(FORMAT(@p_VALORPORCENTUAL, '#,##0.00'))), '') + '%';
  END
  ELSE IF @p_TIPO = 2 BEGIN -- Transaccional
    SELECT @cCOMMISSIONNAME = '$ ' + ISNULL(RTRIM(LTRIM(FORMAT(@p_VALORTRANSACCIONAL, '#,##0.00'))), '');
  END
  ELSE IF @p_TIPO = 3 BEGIN -- Mixto
    SELECT @cCOMMISSIONNAME =  ISNULL(RTRIM(LTRIM(FORMAT(@p_VALORPORCENTUAL, '#,##0.00'))), '') + '%' + ' - ' + '$ ' + ISNULL(RTRIM(LTRIM(FORMAT(@p_VALORTRANSACCIONAL, '#,##0.00'))), '');
  END 
  RETURN @cCOMMISSIONNAME;
END;
GO
