USE SFGPRODU;
--  DDL for Function COMISIONFROMNAME_F
--------------------------------------------------------
  IF OBJECT_ID('WSXML_SFG.COMISIONFROMNAME_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.COMISIONFROMNAME_F;
GO
  CREATE FUNCTION WSXML_SFG.COMISIONFROMNAME_F (@p_NOMRANGOCOMISION VARCHAR(4000) /* Use -meta option RANGOCOMISION.NOMRANGOCOMISION%TYPE */) 
  RETURNS NUMERIC(22,0) AS
 BEGIN
  DECLARE @returnvalue NUMERIC(22,0);
 
  SELECT @returnvalue = ID_RANGOCOMISION FROM WSXML_SFG.RANGOCOMISION WHERE NOMRANGOCOMISION = @p_NOMRANGOCOMISION;
  IF @@ROWCOUNT = 0 BEGIN
  RETURN CAST('-20054 La comision especificada no existe' AS INT);
  END
    RETURN @returnvalue;

END; 

