USE SFGPRODU;
--  DDL for Function COMPANIA_F
--------------------------------------------------------

IF OBJECT_ID('WSXML_SFG.COMPANIA_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.COMPANIA_F;
GO

  CREATE FUNCTION WSXML_SFG.COMPANIA_F (@p_CODIGO NVARCHAR(2000)) RETURNS NUMERIC(22,0) AS
 BEGIN
  DECLARE @result NUMERIC(22,0);
 
  SELECT @result = ID_COMPANIA FROM WSXML_SFG.COMPANIA WHERE CAST(CODIGO AS INT) = CAST(@p_CODIGO AS INT);
  IF @@ROWCOUNT = 0 BEGIN
	--SFGTMPTRACE.TraceLog('Company ' + ISNULL(@p_CODIGO, '') + ' not found');
	RETURN 0;
  END
  RETURN @result;
END
GO