USE SFGPRODU;
--  DDL for Function DBLIFZERO
--------------------------------------------------------

  IF OBJECT_ID('WSXML_SFG.DBLIFZERO', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.DBLIFZERO;
GO

CREATE FUNCTION WSXML_SFG.DBLIFZERO (@pVALUE FLOAT, @pVALUEZERO FLOAT) RETURNS FLOAT AS
BEGIN
  IF @pVALUE = 0 BEGIN
    RETURN @pVALUEZERO;
  END
  ELSE BEGIN
    RETURN @pVALUE;
  END 
  RETURN NULL;
END;

