USE SFGPRODU;
--  DDL for Function DURACION_ESTADO_TAREA
--------------------------------------------------------

  IF OBJECT_ID('WSXML_SFG.DURACION_ESTADO_TAREA', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.DURACION_ESTADO_TAREA;
GO

  CREATE FUNCTION WSXML_SFG.DURACION_ESTADO_TAREA (@P_CODTAREAEJECUTADA       NUMERIC(22,0),
                                                 @P_ID_ESTADOTAREAEJECUTADA NUMERIC(22,0))
  RETURNS VARCHAR(4000) AS
 BEGIN
  DECLARE @result VARCHAR(MAX);
 
  SELECT @result = WXML_SFG.FECHAS_DIFERENCIA(CASE WHEN MN.CODESTADOTAREA IN (1, 2) THEN GETDATE() ELSE MN.FECHAHORAESTADO END,
                           ISNULL(MX.FECHAHORAESTADO, MN.FECHAHORAESTADO))
    FROM (SELECT ET.ID_ESTADOTAREAEJECUTADA,
                 ET.CODTAREAEJECUTADA,
                 ET.CODESTADOTAREA,
                 ET.FECHAHORAMODIFICACION,
                 ET.FECHAHORAESTADO
            FROM WSXML_SFG.ESTADOTAREAEJECUTADA ET
           WHERE ET.CODTAREAEJECUTADA = @P_CODTAREAEJECUTADA
             AND ET.ID_ESTADOTAREAEJECUTADA = @P_ID_ESTADOTAREAEJECUTADA
           --ORDER BY ET.FECHAHORAESTADO DESC
		   ) MN,
         (SELECT ET.ID_ESTADOTAREAEJECUTADA,
                 ET.CODTAREAEJECUTADA,
                 ET.CODESTADOTAREA,
                 ET.FECHAHORAMODIFICACION,
                 ET.FECHAHORAESTADO
            FROM WSXML_SFG.ESTADOTAREAEJECUTADA ET
           WHERE ET.CODTAREAEJECUTADA = @P_CODTAREAEJECUTADA
          -- ORDER BY ET.FECHAHORAESTADO DESC
		   ) MX
   WHERE MN.ID_ESTADOTAREAEJECUTADA > MX.ID_ESTADOTAREAEJECUTADA--(+)
     --AND;

  RETURN(@result);
END;

