USE SFGPRODU;
--  DDL for Function FECHAS_DIFERENCIA
--------------------------------------------------------

 IF OBJECT_ID('WSXML_SFG.FECHAS_DIFERENCIA', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.FECHAS_DIFERENCIA;
GO

    CREATE FUNCTION WSXML_SFG.FECHAS_DIFERENCIA (@p_FECHA_MINUENDO DATETIME, @p_FECHA_SUSTRAENDO DATETIME) RETURNS VARCHAR(4000) AS
 BEGIN
	DECLARE @result VARCHAR(MAX);
  --DECLARE @minuendo VARCHAR(255)= TO_CHAR(@p_FECHA_MINUENDO,'DD/MM/YYYY HH24:MI:SS');
  --DECLARE @sustraendo VARCHAR(255)= TO_CHAR(@p_FECHA_SUSTRAENDO,'DD/MM/YYYY HH24:MI:SS');
 
  IF CONVERT(DATETIME, @p_FECHA_MINUENDO) > CONVERT(DATETIME,@p_FECHA_SUSTRAENDO) BEGIN
      DECLARE @days NUMERIC(22,0) = 0;
      DECLARE @hours NUMERIC(22,0) = 0;
      DECLARE @minutes NUMERIC(22,0) = 0;
      DECLARE @seconds NUMERIC(22,0) = 0;
    BEGIN
      SELECT
        @days = DATEDIFF(day,@p_FECHA_SUSTRAENDO,@p_FECHA_MINUENDO ),--((((86400*(CONVERT(FLOAT, CONVERT(DATETIME, @minuendo,'DD/MM/YYYY HH24:MI:SS'))- CONVERT(FLOAT, CONVERT(DATETIME, @sustraendo,'DD/MM/YYYY HH24:MI:SS'))))/60)/60)/24) Days,
        @hours = DATEDIFF(HOUR,@p_FECHA_SUSTRAENDO,@p_FECHA_MINUENDO ),--(((86400*(CONVERT(FLOAT, CONVERT(DATETIME, @minuendo,'DD/MM/YYYY HH24:MI:SS'))- CONVERT(FLOAT, CONVERT(DATETIME, @sustraendo,'DD/MM/YYYY HH24:MI:SS'))))/60)/60)- 24*(TRUNC((((86400*(CONVERT(FLOAT, CONVERT(DATETIME, @minuendo,'DD/MM/YYYY HH24:MI:SS'))- CONVERT(FLOAT, CONVERT(DATETIME, @sustraendo,'DD/MM/YYYY HH24:MI:SS'))))/60)/60)/24)) Hrs,
        @minutes = DATEDIFF(MINUTE,@p_FECHA_SUSTRAENDO,@p_FECHA_MINUENDO ),--((86400*(CONVERT(FLOAT, CONVERT(DATETIME, @minuendo,'DD/MM/YYYY HH24:MI:SS'))- CONVERT(FLOAT, CONVERT(DATETIME, @sustraendo,'DD/MM/YYYY HH24:MI:SS'))))/60)-60*(TRUNC(((86400*(CONVERT(FLOAT, CONVERT(DATETIME, @minuendo,'DD/MM/YYYY HH24:MI:SS'))- CONVERT(FLOAT, CONVERT(DATETIME, @sustraendo,'DD/MM/YYYY HH24:MI:SS'))))/60)/60)) Min,
        @seconds = DATEDIFF(SECOND,@p_FECHA_SUSTRAENDO,@p_FECHA_MINUENDO )--(86400*(CONVERT(FLOAT, CONVERT(DATETIME, @minuendo,'DD/MM/YYYY HH24:MI:SS'))- CONVERT(FLOAT, CONVERT(DATETIME, @sustraendo,'DD/MM/YYYY HH24:MI:SS'))))-60*(TRUNC((86400*(CONVERT(FLOAT, CONVERT(DATETIME, @minuendo,'DD/MM/YYYY HH24:MI:SS'))- CONVERT(FLOAT, CONVERT(DATETIME, @sustraendo,'DD/MM/YYYY HH24:MI:SS'))))/60)) Sec


      SET @result = '';
      IF @days > 0 BEGIN
        SET @result = @result + convert(varchar, @days) + 'D';
      END 

      IF @hours > 0 BEGIN
        SET @result = @result +' ' + convert(varchar, @hours) + 'h';
      END 

      SET @result = @result + ' ' + CONVERT(VARCHAR,@minutes) + 'm' + ' ' + CONVERT(VARCHAR,@seconds) + 's' ;

    END;
  END
  ELSE BEGIN
    SET @result = '0s';
  END 

  RETURN(RTRIM(LTRIM(@result)));
END; 
GO