USE SFGPRODU;
--  DDL for Function LINEADENEGOCIO_PRODUCTO_F
--------------------------------------------------------

IF OBJECT_ID('WSXML_SFG.LINEADENEGOCIO_PRODUCTO_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.LINEADENEGOCIO_PRODUCTO_F;
GO

CREATE FUNCTION WSXML_SFG.LINEADENEGOCIO_PRODUCTO_F (@p_CODPRODUCTO NUMERIC(22,0)) RETURNS NUMERIC(22,0) AS
BEGIN
  DECLARE @result NUMERIC(22,0);
 

  SELECT @result = T.CODLINEADENEGOCIO FROM WSXML_SFG.PRODUCTO P
  INNER JOIN WSXML_SFG.TIPOPRODUCTO T ON (P.CODTIPOPRODUCTO = T.ID_TIPOPRODUCTO)
  WHERE P.ID_PRODUCTO = @p_CODPRODUCTO;
  
	IF @@ROWCOUNT = 0 BEGIN
		RETURN 0
	END   

  RETURN @result;

END

