USE SFGPRODU;
--  DDL for Function NOMBRE_PRODUCTO_F
--------------------------------------------------------

IF OBJECT_ID('WSXML_SFG.NOMBRE_PRODUCTO_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.NOMBRE_PRODUCTO_F;
GO

 CREATE FUNCTION WSXML_SFG.NOMBRE_PRODUCTO_F (@uk_NOMPRODUCTO VARCHAR(4000)) RETURNS NUMERIC(22,0) AS
 BEGIN
  DECLARE @result NUMERIC(22,0) = 0;
 
  SELECT @result = p.id_producto FROM WSXML_SFG.PRODUCTO P WHERE P.NOMPRODUCTO = @uk_NOMPRODUCTO;
  
	IF @@ROWCOUNT = 0 BEGIN
		--EXCEPTION WHEN OTHERS THEN   SFGTMPTRACE.TraceLog('No es posible encontrar el producto con nombre ' + ISNULL(@uk_NOMPRODUCTO, ''));
		RETURN 0
	END  
  RETURN @result;

END

