USE SFGPRODU;
--  DDL for Function ORIGENPAGO_NOMBRE_F
--------------------------------------------------------

  IF OBJECT_ID('WSXML_SFG.ORIGENPAGO_NOMBRE_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.ORIGENPAGO_NOMBRE_F;
GO

  CREATE FUNCTION WSXML_SFG.ORIGENPAGO_NOMBRE_F (@pk_ID_ORIGENPAGO NUMERIC(22,0)) RETURNS NVARCHAR(2000) AS
 BEGIN
  DECLARE @result NVARCHAR(255);
 
  SELECT @result = RTRIM(LTRIM(O.DESCRIPCION)) FROM WSXML_SFG.ORIGENPAGO O
  WHERE O.ID_ORIGENPAGO = @pk_ID_ORIGENPAGO;

  RETURN(@result);
END;

