USE SFGPRODU;
--  DDL for Function PARAMETRO_F
--------------------------------------------------------

IF OBJECT_ID('WSXML_SFG.PARAMETRO_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.PARAMETRO_F;
GO

CREATE FUNCTION WSXML_SFG.PARAMETRO_F (@p_NOMPARAMETRO NVARCHAR(2000)) RETURNS NVARCHAR(2000) AS
 BEGIN
  DECLARE @paramresult NVARCHAR(1000);
 
  SELECT @paramresult = VALOR 
  FROM WSXML_SFG.PARAMETRO WHERE NOMPARAMETRO = @p_NOMPARAMETRO;
  

	IF @@ROWCOUNT = 0 BEGIN
		--EXCEPTION WHEN OTHERS THEN  SFGTMPTRACE.TraceLog('Parameter ' + ISNULL(@p_NOMPARAMETRO, '') + ' not obtained');
		RETURN ''
	END
  
  RETURN @paramresult;
END

