USE SFGPRODU;
--  DDL for Function PENULTIMO_CICLOFACTURACION
--------------------------------------------------------

  IF OBJECT_ID('WSXML_SFG.PENULTIMO_CICLOFACTURACION', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.PENULTIMO_CICLOFACTURACION;
GO

  CREATE FUNCTION WSXML_SFG.PENULTIMO_CICLOFACTURACION (@p_FECHA DATETIME) RETURNS NUMERIC(22,0) AS
 BEGIN
  DECLARE @result NUMERIC(22,0);
 
  BEGIN
    SELECT @result = S.ID_CICLOFACTURACIONPDV
    FROM (
		SELECT S1.ID_CICLOFACTURACIONPDV
		--, ROWNUM AS myrow
		, ROW_NUMBER() OVER(ORDER BY S1.FECHAHORAMODIFICACION DESC) myrow
        FROM (
			SELECT ID_CICLOFACTURACIONPDV, FECHAHORAMODIFICACION FROM WSXML_SFG.CICLOFACTURACIONPDV
			WHERE CONVERT(DATETIME, CONVERT(DATE,FECHAEJECUCION)) <= CONVERT(DATETIME, CONVERT(DATE,@p_FECHA))
			  AND ACTIVE = 1
			--ORDER BY FECHAHORAMODIFICACION DESC
			) S1
	) S
    WHERE myrow = 2;
	
	IF @@ROWCOUNT = 0  
		SET @result = NULL;
  END;

  RETURN(@result);
END;

