USE SFGPRODU;
--  DDL for Function PRODUCTO_F
--------------------------------------------------------

  IF OBJECT_ID('WSXML_SFG.PRODUCTO_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.PRODUCTO_F;
GO

CREATE FUNCTION WSXML_SFG.PRODUCTO_F (@p_PRODUCTO NVARCHAR(2000)) RETURNS NUMERIC(22,0) AS
	BEGIN
	DECLARE @result NUMERIC(22,0);
 
	SELECT @result = ID_PRODUCTO FROM WSXML_SFG.PRODUCTO WHERE CAST(CODIGOGTECHPRODUCTO AS INT) = CAST(@p_PRODUCTO AS INT);
	--EXCEPTION WHEN OTHERS THEN
	IF @@ERROR <> 0 BEGIN
		RETURN 0;
	END 
	RETURN @result;
	
END;

