USE SFGPRODU;
--  DDL for Function PUNTODEVENTA_F
--------------------------------------------------------

IF OBJECT_ID('WSXML_SFG.PUNTODEVENTA_F', 'P') IS NOT NULL
    DROP PROCEDURE WSXML_SFG.PUNTODEVENTA_F;
GO

CREATE PROCEDURE WSXML_SFG.PUNTODEVENTA_F (@P_PDV_GTECH NVARCHAR(2000), @CODDUENOPUNTODEVENTA NUMERIC(22,0) = 0, @p_result NUMERIC(22,0) OUT)  AS
 BEGIN
  DECLARE @result      NUMERIC(22,0);
  DECLARE @activestate NUMERIC(22,0);
  DECLARE @contenido VARCHAR(2000);
 
  --Consulta id de due�o de punto de venta  

  DECLARE 	@p_TIPOINFORMATIVO TINYINT,
	@p_TIPOERROR TINYINT,
	@p_TIPOADVERTENCIA TINYINT,
	@p_TIPOCUALQUIERA TINYINT,
	@p_PROCESONOTIFICACION TINYINT,
	@p_ESTADOABIERTA TINYINT,
	@p_ESTADOCERRADA TINYINT

  EXEC WSXML_SFG.SFGALERTA_CONSTANT
	@p_TIPOINFORMATIVO OUT,
	@p_TIPOERROR OUT,
	@p_TIPOADVERTENCIA OUT,
	@p_TIPOCUALQUIERA OUT,
	@p_PROCESONOTIFICACION OUT,
	@p_ESTADOABIERTA OUT,
	@p_ESTADOCERRADA OUT

  IF @CODDUENOPUNTODEVENTA = 0 BEGIN 
      
   SELECT @result = ID_PUNTODEVENTA, @activestate = ACTIVE 
   FROM WSXML_SFG.PUNTODEVENTA WHERE CAST(CODIGOGTECHPUNTODEVENTA AS INT) = CAST(@P_PDV_GTECH AS INT);
   
     IF @activestate = 0 BEGIN
      -- Alert and set active
      UPDATE WSXML_SFG.PUNTODEVENTA SET ACTIVE = 1 WHERE ID_PUNTODEVENTA = @result;
	  SET  @contenido = 'El punto de venta ' + ISNULL(@P_PDV_GTECH, '') + ' fue activado tras encontrar una transaccion activa en el sistema (' + CONVERT(VARCHAR, GETDATE(), 103) + ')'
      EXEC WSXML_SFG.SFGALERTA_GenerarAlerta  @p_TIPOADVERTENCIA, 'LOAD_SALES_FILE', @contenido, 1
     END 
  END
  ELSE BEGIN 
  /*   SELECT ID_PUNTODEVENTA, ACTIVE INTO result, activestate
     FROM PUNTODEVENTA WHERE TO_NUMBER(CODPUNTODEVENTADUENO) = TO_NUMBER(P_PDV_GTECH);*/
     
   /*  SELECT ID_PUNTODEVENTA, ACTIVE
     INTO RESULT, activestate
     FROM PUNTODEVENTA 
     LEFT OUTER JOIN DUENOPUNTODEVENTA ON PUNTODEVENTA.CODDUENOPUNTODEVENTA = DUENOPUNTODEVENTA.ID_DUENOPUNTODEVENTA
     WHERE PUNTODEVENTA.CODDUENOPUNTODEVENTA = CODDUENOPUNTODEVENTA AND TO_NUMBER(PUNTODEVENTA.CODEXTERNOPUNTODEVENTA) = TO_NUMBER(P_PDV_GTECH);                  
   */
   SELECT @RESULT = max(ID_PUNTODEVENTA), @activestate = 1
     FROM WSXML_SFG.PUNTODEVENTA PV
     LEFT OUTER JOIN WSXML_SFG.DUENOPUNTODEVENTA DPV ON PV.CODDUENOPUNTODEVENTA = DPV.ID_DUENOPUNTODEVENTA
     WHERE PV.CODDUENOPUNTODEVENTA = @CODDUENOPUNTODEVENTA AND CAST(PV.CODEXTERNOPUNTODEVENTA AS INT) = CAST(@P_PDV_GTECH AS INT);                  
   
  
     IF @activestate = 0 BEGIN
      -- Alert and set active
      UPDATE WSXML_SFG.PUNTODEVENTA SET ACTIVE = 1 WHERE ID_PUNTODEVENTA = @result;

	  SET @contenido = 'El punto de venta ' + ISNULL(@P_PDV_GTECH, '') + ' fue activado tras encontrar una transaccion activa en el sistema (' + convert(VARCHAR,GETDATE(), 103) + ')'
      EXEC WSXML_SFG.SFGALERTA_GenerarAlerta @p_TIPOCUALQUIERA, 'LOAD_SALES_FILE', @contenido, 1
     END 
  END 
  
  IF @@ROWCOUNT = 0 BEGIN
	set @p_result = 0;
  END
  
  set @p_result = @result;
END; 
GO