USE SFGPRODU;
IF OBJECT_ID('WSXML_SFG.RAZONSOCIAL_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.RAZONSOCIAL_F;
GO

CREATE FUNCTION WSXML_SFG.RAZONSOCIAL_F (@p_CODIGOGTECHRAZONSOCIAL NUMERIC(22,0)) RETURNS NUMERIC(22,0) AS
BEGIN
	DECLARE @result NUMERIC(22,0);
 
	SELECT @result = ID_RAZONSOCIAL FROM WSXML_SFG.RAZONSOCIAL WHERE CODIGOGTECHRAZONSOCIAL = @p_CODIGOGTECHRAZONSOCIAL;

	IF @@ROWCOUNT = 0 BEGIN
		--EXCEPTION WHEN OTHERS THEN  SFGTMPTRACE.TraceLog('Legal name ' + ISNULL(@p_CODIGOGTECHRAZONSOCIAL, '') + ' not found');
		RETURN 0
	END


	RETURN @result;
END

