USE SFGPRODU;
--  DDL for Function REFERENCIABYAGRUPACION_F
--------------------------------------------------------

IF OBJECT_ID('WSXML_SFG.REFERENCIABYAGRUPACION_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.REFERENCIABYAGRUPACION_F;
GO

CREATE FUNCTION WSXML_SFG.REFERENCIABYAGRUPACION_F (@p_CODIGOCADENA NVARCHAR(2000)) RETURNS NVARCHAR(2000) AS
BEGIN
  DECLARE @result NVARCHAR(10);
  DECLARE @v_CODAGRUPACIONPUNTODEVENTA INT;
 
  SELECT @v_CODAGRUPACIONPUNTODEVENTA = AGRUPACIONPUNTODEVENTA.Id_Agrupacionpuntodeventa
  FROM WSXML_SFG.AGRUPACIONPUNTODEVENTA
  WHERE AGRUPACIONPUNTODEVENTA.CODIGOAGRUPACIONGTECH = @p_CODIGOCADENA;

 -- Call the procedure
	EXEC WSXML_SFG.sfgmaestrofacturacioncompconsi_getnumeroreferencia 1,@v_CODAGRUPACIONPUNTODEVENTA,NULL,GETDATE,@result

  IF @@ROWCOUNT = 0 BEGIN
	--SFGTMPTRACE.TraceLog('Error al tratar de calcular la referencia de la cadena ' + ISNULL(@p_CODIGOCADENA, '') + ' : La cadena no existe', 'LOAD_SALES_FILES');
    SET @result = '';
  END
  
  RETURN @result;

END; 
GO
