USE SFGPRODU;
--  DDL for Package Body SFGCONFIGURACIONALIADOARCHIVO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO */ 

  IF OBJECT_ID('WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_CreateConfiguration', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_CreateConfiguration;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_CreateConfiguration(@p_CODALIADOESTRATEGICO         NUMERIC(22,0),
                                @p_CODFORMATOARCHIVOTRANSACCION NUMERIC(22,0),
                                @p_COMENTARIO                   NVARCHAR(2000),
                                @p_CODUSUARIOMODIFICACION       NUMERIC(22,0),
                                @p_ID_CONFIGURACIONALIADOAR_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    SELECT @p_ID_CONFIGURACIONALIADOAR_out = ID_CONFIGURACIONALIADOARCHIVO FROM WSXML_SFG.CONFIGURACIONALIADOARCHIVO
    WHERE CODALIADOESTRATEGICO = @p_CODALIADOESTRATEGICO;

  
	IF @@ROWCOUNT = 0 BEGIN
		INSERT INTO WSXML_SFG.CONFIGURACIONALIADOARCHIVO (
												CODALIADOESTRATEGICO,
												CODFORMATOARCHIVOTRANSACCION,
												COMENTARIO,
												CODUSUARIOMODIFICACION)
		VALUES (
				@p_CODALIADOESTRATEGICO,
				@p_CODFORMATOARCHIVOTRANSACCION,
				@p_COMENTARIO,
				@p_CODUSUARIOMODIFICACION);
		SET @p_ID_CONFIGURACIONALIADOAR_out = SCOPE_IDENTITY();
	END ELSE BEGIN
		UPDATE WSXML_SFG.CONFIGURACIONALIADOARCHIVO SET CODFORMATOARCHIVOTRANSACCION = @p_CODFORMATOARCHIVOTRANSACCION,
			COMENTARIO                   = @p_COMENTARIO,
			CODUSUARIOMODIFICACION       = @p_CODUSUARIOMODIFICACION,
			FECHAHORAMODIFICACION        = GETDATE()
		WHERE ID_CONFIGURACIONALIADOARCHIVO = @p_ID_CONFIGURACIONALIADOAR_out;
	END
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_GetConfigurationCode', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_GetConfigurationCode;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_GetConfigurationCode(@p_CODALIADOESTRATEGICO         NUMERIC(22,0),
                                 @p_CODFORMATOARCHIVOTRANSAC_out NUMERIC(22,0) OUT) AS
BEGIN
  SET NOCOUNT ON;
    SELECT @p_CODFORMATOARCHIVOTRANSAC_out = CODFORMATOARCHIVOTRANSACCION FROM WSXML_SFG.CONFIGURACIONALIADOARCHIVO
    WHERE CODALIADOESTRATEGICO = @p_CODALIADOESTRATEGICO;
	IF @@ROWCOUNT = 0
		RAISERROR('-20054 No existe configuracion de archivos para el aliado especificado', 16, 1);
END;
GO
  
IF OBJECT_ID('WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_GetConfiguredAliados', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_GetConfiguredAliados;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_GetConfiguredAliados AS
  BEGIN
  SET NOCOUNT ON;
      SELECT ID_ALIADOESTRATEGICO, NOMALIADOESTRATEGICO, CODFORMATOARCHIVOTRANSACCION
      FROM WSXML_SFG.ALIADOESTRATEGICO
		INNER JOIN WSXML_SFG.CONFIGURACIONALIADOARCHIVO ON (CODALIADOESTRATEGICO = ID_ALIADOESTRATEGICO)
      ORDER BY NOMALIADOESTRATEGICO;
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_GetFormatFromAliado', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_GetFormatFromAliado;
GO
CREATE     PROCEDURE WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_GetFormatFromAliado(@p_CODALIADOESTRATEGICO NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT ID_FORMATOARCHIVOTRANSACCION,
             NOMFORMATOARCHIVOTRANSACCION,
             CANTIDADLINEASHEADER,
             CANTIDADLINEASFOOTER,
             HEADIDSTARTINDEX,
             HEADIDLENGTH,
             HEADDVSTARTINDEX,
             HEADDVLENGTH,
             HEADDATESTARTINDEX,
             HEADDATELENGTH,
             HEADDATEFORMAT,
             FOOTQUANTITYSTARTINDEX,
             FOOTQUANTITYLENGTH,
             FOOTAMOUNTSTARTINDEX,
             FOOTAMOUNTLENGTH,
             LINERECEIPTSTARTINDEX,
             LINERECEIPTLENGTH,
             LINESUSCRIBERSTARTINDEX,
             LINESUSCRIBERLENGTH,
             LINEAMOUNTSTARTINDEX,
             LINEAMOUNTLENGTH,
             FORCELINEPREFIX,
             CHECKAMOUNT,
             TRIMRIGHTRECEIPT,
             TRIMRIGHTSUSCRIBER,
             CNSDRLINESTARTINDEX,
             CNSDRLINELENGTH,
             CNSDRLINEVALUE,
             CONFIGURACION
      FROM WSXML_SFG.CONFIGURACIONALIADOARCHIVO
      INNER JOIN WSXML_SFG.FORMATOARCHIVOTRANSACCION ON (CODFORMATOARCHIVOTRANSACCION = ID_FORMATOARCHIVOTRANSACCION)
      WHERE CODALIADOESTRATEGICO = @p_CODALIADOESTRATEGICO;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_GetAllFormats', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_GetAllFormats;
GO
CREATE     PROCEDURE WSXML_SFG.SFGCONFIGURACIONALIADOARCHIVO_GetAllFormats AS
  BEGIN
  SET NOCOUNT ON;
      SELECT ID_FORMATOARCHIVOTRANSACCION                       AS ID_FORMATOARCHIVOTRANSACCION,
             NOMFORMATOARCHIVOTRANSACCION                       AS NOMFORMATOARCHIVOTRANSACCION,
             CANTIDADLINEASHEADER                               AS CANTIDADLINEASHEADER,
             CANTIDADLINEASFOOTER                               AS CANTIDADLINEASFOOTER,
             HEADIDSTARTINDEX                                   AS HEADIDSTARTINDEX,
             HEADIDLENGTH                                       AS HEADIDLENGTH,
             HEADDVSTARTINDEX                                   AS HEADDVSTARTINDEX,
             HEADDVLENGTH                                       AS HEADDVLENGTH,
             HEADDATESTARTINDEX                                 AS HEADDATESTARTINDEX,
             HEADDATELENGTH                                     AS HEADDATELENGTH,
             HEADDATEFORMAT                                     AS HEADDATEFORMAT,
             FOOTQUANTITYSTARTINDEX                             AS FOOTQUANTITYSTARTINDEX,
             FOOTQUANTITYLENGTH                                 AS FOOTQUANTITYLENGTH,
             FOOTAMOUNTSTARTINDEX                               AS FOOTAMOUNTSTARTINDEX,
             FOOTAMOUNTLENGTH                                   AS FOOTAMOUNTLENGTH,
             LINERECEIPTSTARTINDEX                              AS LINERECEIPTSTARTINDEX,
             LINERECEIPTLENGTH                                  AS LINERECEIPTLENGTH,
             LINESUSCRIBERSTARTINDEX                            AS LINESUSCRIBERSTARTINDEX,
             LINESUSCRIBERLENGTH                                AS LINESUSCRIBERLENGTH,
             LINEAMOUNTSTARTINDEX                               AS LINEAMOUNTSTARTINDEX,
             LINEAMOUNTLENGTH                                   AS LINEAMOUNTLENGTH,
             FORCELINEPREFIX                                    AS FORCELINEPREFIX,
             CHECKAMOUNT                                        AS CHECKAMOUNT,
             TRIMRIGHTRECEIPT                                   AS TRIMRIGHTRECEIPT,
             TRIMRIGHTSUSCRIBER                                 AS TRIMRIGHTSUSCRIBER,
             CNSDRLINESTARTINDEX                                AS CNSDRLINESTARTINDEX,
             CNSDRLINELENGTH                                    AS CNSDRLINELENGTH,
             CNSDRLINEVALUE                                     AS CNSDRLINEVALUE,
             CONFIGURACION                                      AS CONFIGURACION,
             COALESCE(CAP.PREFIJOESPERADO, CAA.PREFIJOESPERADO) AS PREFIJOESPERADO,
             CAP.FORMATOESPERADO                                AS FORMATOESPERADO,
             CAA.CODALIADOESTRATEGICO                           AS CODALIADOESTRATEGICO,
             AES.NOMALIADOESTRATEGICO                           AS NOMALIADOESTRATEGICO
      FROM WSXML_SFG.CONFIGURACIONALIADOARCHIVO CAA
      INNER JOIN WSXML_SFG.FORMATOARCHIVOTRANSACCION       FAT ON (CAA.CODFORMATOARCHIVOTRANSACCION = FAT.ID_FORMATOARCHIVOTRANSACCION)
      INNER JOIN WSXML_SFG.ALIADOESTRATEGICO               AES ON (CAA.CODALIADOESTRATEGICO         = AES.ID_ALIADOESTRATEGICO)
      LEFT OUTER JOIN WSXML_SFG.CONFIGALIADOARCHIVOPREFIJO CAP ON (CAP.CODCONFIGURACIONALIADOARCHIVO = CAA.ID_CONFIGURACIONALIADOARCHIVO);
  END;

GO


