USE SFGPRODU;
--  DDL for Package Body SFGCIERREANUALTRIBUTARIO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGCIERREANUALTRIBUTARIO */ 

  IF OBJECT_ID('WSXML_SFG.SFGCIERREANUALTRIBUTARIO_AddTributaryInfo', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCIERREANUALTRIBUTARIO_AddTributaryInfo;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCIERREANUALTRIBUTARIO_AddTributaryInfo(@p_ANOREFERENCIA                NUMERIC(22,0),
                             @p_CODPUNTODEVENTA              NUMERIC(22,0),
                             @p_CODPRODUCTO                  NUMERIC(22,0),
                             @p_CODTIPOCONTRATOPDV           NUMERIC(22,0),
                             @p_CODCOMPANIA                  NUMERIC(22,0),
                             @p_COMISION                     FLOAT,
                             @p_IVACOMISION                  FLOAT,
                             @p_TOTALRETENCIONES             FLOAT,
                             @p_CODUSUARIOMODIFICACION       NUMERIC(22,0),
                             @p_ID_CIERREANUALTRIBUTARIO_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    -- Find previously added record through unique key CODPUNTODEVENTA, CODLINEADENEGOCIO, CODTIPOCONTRATOPDV, CODCOMPANIA
    SELECT @p_ID_CIERREANUALTRIBUTARIO_out = ID_CIERREANUALTRIBUTARIO FROM WSXML_SFG.CIERREANUALTRIBUTARIO
    WHERE ANOREFERENCIA      = @p_ANOREFERENCIA
      AND CODPUNTODEVENTA    = @p_CODPUNTODEVENTA
      AND CODPRODUCTO        = @p_CODPRODUCTO
      AND CODTIPOCONTRATOPDV = @p_CODTIPOCONTRATOPDV
      AND CODCOMPANIA        = @p_CODCOMPANIA;
    
	IF @@ROWCOUNT = 0
	BEGIN
		INSERT INTO WSXML_SFG.CIERREANUALTRIBUTARIO (
										   ANOREFERENCIA,
										   CODPUNTODEVENTA,
										   CODPRODUCTO,
										   CODTIPOCONTRATOPDV,
										   CODCOMPANIA,
										   COMISION,
										   IVACOMISION,
										   TOTALRETENCIONES,
										   CODUSUARIOMODIFICACION)
		VALUES (
				@p_ANOREFERENCIA,
				@p_CODPUNTODEVENTA,
				@p_CODPRODUCTO,
				@p_CODTIPOCONTRATOPDV,
				@p_CODCOMPANIA,
				@p_COMISION,
				@p_IVACOMISION,
				@p_TOTALRETENCIONES,
				@p_CODUSUARIOMODIFICACION);
		SET @p_ID_CIERREANUALTRIBUTARIO_out = SCOPE_IDENTITY();
	END ELSE BEGIN
		-- Update existing record
		UPDATE WSXML_SFG.CIERREANUALTRIBUTARIO SET COMISION         = COMISION         + @p_COMISION,
										 IVACOMISION      = IVACOMISION      + @p_IVACOMISION,
										 TOTALRETENCIONES = TOTALRETENCIONES + @p_TOTALRETENCIONES
		WHERE ID_CIERREANUALTRIBUTARIO = @p_ID_CIERREANUALTRIBUTARIO_out;
	END
  END;
  GO

  IF OBJECT_ID('WSXML_SFG.SFGCIERREANUALTRIBUTARIO_AddRetencionInfo', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCIERREANUALTRIBUTARIO_AddRetencionInfo;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCIERREANUALTRIBUTARIO_AddRetencionInfo(@p_CODCIERRETRIBUTARIO         NUMERIC(22,0),
                             @p_CODRETENCIONTRIBUTARIA      NUMERIC(22,0),
                             @p_VALORRETENCION              FLOAT,
                             @p_ID_CIERREANUALRETENCION_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    SELECT @p_ID_CIERREANUALRETENCION_out = ID_CIERREANUALRETENCION FROM WSXML_SFG.CIERREANUALRETENCION
    WHERE CODCIERREANUALTRIBUTARIO = @p_CODCIERRETRIBUTARIO
      AND CODRETENCIONTRIBUTARIA   = @p_CODRETENCIONTRIBUTARIA;
    
	IF @@ROWCOUNT = 0
	BEGIN
		INSERT INTO WSXML_SFG.CIERREANUALRETENCION ( CODCIERREANUALTRIBUTARIO, CODRETENCIONTRIBUTARIA, VALORRETENCION)
		VALUES ( @p_CODCIERRETRIBUTARIO, @p_CODRETENCIONTRIBUTARIA, @p_VALORRETENCION);
		SET @p_ID_CIERREANUALRETENCION_out = SCOPE_IDENTITY();
	END ELSE BEGIN
		UPDATE WSXML_SFG.CIERREANUALRETENCION SET VALORRETENCION = VALORRETENCION + @p_VALORRETENCION
		WHERE ID_CIERREANUALRETENCION = @p_ID_CIERREANUALRETENCION_out;
	END
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCIERREANUALTRIBUTARIO_AddRetencionUVTInfo', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCIERREANUALTRIBUTARIO_AddRetencionUVTInfo;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCIERREANUALTRIBUTARIO_AddRetencionUVTInfo(@p_CODCIERRETRIBUTARIO      NUMERIC(22,0),
                                @p_CODRETENCIONUVT          NUMERIC(22,0),
                                @p_VALORRETENCION           FLOAT,
                                @p_ID_CIERREANUALRETUVT_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    SELECT @p_ID_CIERREANUALRETUVT_out = ID_CIERREANUALRETUVT FROM WSXML_SFG.CIERREANUALRETUVT
    WHERE CODCIERREANUALTRIBUTARIO = @p_CODCIERRETRIBUTARIO
      AND CODRETENCIONUVT          = @p_CODRETENCIONUVT;

	IF @@ROWCOUNT = 0
	BEGIN
		INSERT INTO WSXML_SFG.CIERREANUALRETUVT ( CODCIERREANUALTRIBUTARIO, CODRETENCIONUVT, VALORRETENCION)
		VALUES ( @p_CODCIERRETRIBUTARIO, @p_CODRETENCIONUVT, @p_VALORRETENCION);
		SET @p_ID_CIERREANUALRETUVT_out = SCOPE_IDENTITY();
	END ELSE BEGIN	
		UPDATE WSXML_SFG.CIERREANUALRETUVT SET VALORRETENCION = VALORRETENCION + @p_VALORRETENCION
		WHERE ID_CIERREANUALRETUVT = @p_ID_CIERREANUALRETUVT_out;
	END
  END;

GO
