USE SFGPRODU;
--  DDL for Package Body SFGCOSTOASOCIADO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGCOSTOASOCIADO */ 

 IF OBJECT_ID('WSXML_SFG.SFGCOSTOASOCIADO_GetValorPorRegistroyCosto', 'FN') IS NOT NULL
  DROP FUNCTION WSXML_SFG.SFGCOSTOASOCIADO_GetValorPorRegistroyCosto;
GO

CREATE   FUNCTION WSXML_SFG.SFGCOSTOASOCIADO_GetValorPorRegistroyCosto( @p_CODREGISTROFACTURACION    NUMERIC(22,0),
                                     @p_CODCOSTOASOCIADO          NUMERIC(22,0)) RETURNS FLOAT AS
 BEGIN
    DECLARE @p_VALOR_out FLOAT;
   
    SELECT @p_VALOR_out = SUM(COSTOASOCIADOREGFACTURACION.VALORTRANSACCIONES)
    FROM WSXML_SFG.COSTOASOCIADOREGFACTURACION 
    WHERE CODREGISTROFACTURACION = @p_CODREGISTROFACTURACION
    AND CODCOSTOASOCIADO = @p_CODCOSTOASOCIADO;
    
    RETURN ISNULL(@p_VALOR_out,0);
END;

