USE SFGPRODU;
--  DDL for Package Body SFGEXCEPCIONPDV
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGEXCEPCIONPDV */ 

IF OBJECT_ID('WSXML_SFG.SFGEXCEPCIONPDV_PermitirInactivacion', 'FN') IS NOT NULL
  DROP FUNCTION WSXML_SFG.SFGEXCEPCIONPDV_PermitirInactivacion;
GO

CREATE FUNCTION WSXML_SFG.SFGEXCEPCIONPDV_PermitirInactivacion(@p_CODPUNTODEVENTA NUMERIC(22,0)) RETURNS BIT AS
 BEGIN

	DECLARE @EXISTEPDV NUMERIC(22,0) = 0;
	DECLARE @TIPO NUMERIC(22,0);

   

    DECLARE TIPOVINCULACIONPAGO CURSOR FOR SELECT ID_TIPOVINCULACIONPAGO FROM WSXML_SFG.TIPOVINCULACIONPAGO;    OPEN TIPOVINCULACIONPAGO;

	DECLARE @ID_TIPOVINCULACIONPAGO NUMERIC(38,0)
	FETCH NEXT FROM TIPOVINCULACIONPAGO INTO @ID_TIPOVINCULACIONPAGO

    WHILE @@FETCH_STATUS=0
    BEGIN
      SET @TIPO  = @ID_TIPOVINCULACIONPAGO

	   -- Verifica el PDV
	  IF @ID_TIPOVINCULACIONPAGO = 1 BEGIN
		SELECT @EXISTEPDV = COUNT(*)
           FROM WSXML_SFG.EXCEPCIONPDV
           WHERE WSXML_SFG.EXCEPCIONPDV.CODPUNTODEVENTA = @p_CODPUNTODEVENTA
           AND EXCEPCIONPDV.CODTIPOVINCULACIONPAGO = @TIPO
           AND EXCEPCIONPDV.ACTIVE = 1;
           IF @EXISTEPDV > 0 BEGIN
              RETURN 0;
           END 
	  END

	  -- Verifica el RUT (NIT)
	  IF @ID_TIPOVINCULACIONPAGO = 2 BEGIN
		SELECT @EXISTEPDV = COUNT(*)  
          FROM WSXML_SFG.EXCEPCIONPDV, WSXML_SFG.PUNTODEVENTA
          WHERE EXCEPCIONPDV.CODPUNTODEVENTA = PUNTODEVENTA.ID_PUNTODEVENTA
          AND EXCEPCIONPDV.CODTIPOVINCULACIONPAGO = @TIPO
          AND EXCEPCIONPDV.ACTIVE = 1
          AND PUNTODEVENTA.IDENTIFICACION =
              (SELECT PUNTODEVENTA.IDENTIFICACION
              FROM WSXML_SFG.PUNTODEVENTA
              WHERE PUNTODEVENTA.ID_PUNTODEVENTA =  @p_CODPUNTODEVENTA
              --AND
			  );
           IF @EXISTEPDV > 0 BEGIN
              RETURN 0;
           END 

	  END

	   -- Verifica la CADENA
	   IF @ID_TIPOVINCULACIONPAGO = 3 BEGIN
			SELECT @EXISTEPDV = COUNT(*)  
			FROM WSXML_SFG.EXCEPCIONPDV, WSXML_SFG.PUNTODEVENTA
			WHERE EXCEPCIONPDV.CODPUNTODEVENTA = PUNTODEVENTA.ID_PUNTODEVENTA
			  AND EXCEPCIONPDV.CODTIPOVINCULACIONPAGO = @TIPO
			  AND EXCEPCIONPDV.ACTIVE = 1
			  AND PUNTODEVENTA.CODAGRUPACIONPUNTODEVENTA =
				  (SELECT PUNTODEVENTA.CODAGRUPACIONPUNTODEVENTA
				  FROM WSXML_SFG.PUNTODEVENTA
				  WHERE PUNTODEVENTA.ID_PUNTODEVENTA =  @p_CODPUNTODEVENTA
				  --AND
				  );
			   IF @EXISTEPDV > 0 BEGIN
				  RETURN 0;
			   END 
	   END

       RETURN 1;


	FETCH NEXT FROM TIPOVINCULACIONPAGO INTO @ID_TIPOVINCULACIONPAGO
	END;

  CLOSE TIPOVINCULACIONPAGO;
  DEALLOCATE TIPOVINCULACIONPAGO;



    RETURN 0;
  END;
