USE SFGPRODU;
--  DDL for Package Body SFGINF_INVCHAINBP00
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGINF_INVCHAINBP00 */ 

  IF OBJECT_ID('WSXML_SFG.SFGINF_INVCHAINBP00_GetReportData', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGINF_INVCHAINBP00_GetReportData;
GO

CREATE     PROCEDURE WSXML_SFG.SFGINF_INVCHAINBP00_GetReportData(@p_CODCICLOFACTURACIONPDV NUMERIC(22,0),
                          @p_CODLINEADENEGOCIO      NUMERIC(22,0),
                          @pg_CADENA                NVARCHAR(2000),
                          @pg_ALIADOESTRATEGICO     NVARCHAR(2000),
                         @pg_PRODUCTO              NVARCHAR(2000)
                          ) AS
  BEGIN
  SET NOCOUNT ON;
	
    SELECT '00CHN' AS RECORD_TYPE,
           VPVF.CODIGOAGRUPACIONGTECH   AS CHAIN,
           round(SUM(VPVF.VALORVENTA),19)         AS ACCEPTEDTRANSACTIONS,
           round(SUM(VPVF.VALORANULACION),19)     AS CNCELLEDTRANSACTIONS,
           round(SUM(VPVF.VALORCOMISION),19)      AS COMISSION_WITHOUTVAT,
           round(SUM(VPVF.VATCOMISION),19)        AS COMISSION_VAT,
           round(SUM(VPVF.VALORCOMISIONBRUTA),19) AS COMISSION_WITHVAT,
           round(SUM(VPVF.RETENCION_RENTA),19)    AS TAX_RENTA,
           round(SUM(VPVF.RETENCION_RETEICA),19)  AS TAX_INDCOME,
           round(SUM(VPVF.RETENCION_RETEIVA),19)  AS TAX_IVA,
           round(SUM(VPVF.RETENCION_RETECREE),19)  AS TAX_CREE,
           round(SUM(VPVF.VALORCOMISIONNETA),19)  AS COMISSION_FINAL,
           round(SUM((VPVF.FACTURADOENCONTRAGTECH - VPVF.FACTURADOAFAVORGTECH) +
               (VPVF.FACTURADOENCONTRAFIDUCIA - VPVF.FACTURADOAFAVORFIDUCIA)),19)
                                        AS TOTALBILLING
    FROM WSXML_SFG.VW_SHOW_PDVFACTURACION VPVF
    WHERE VPVF.ID_CICLOFACTURACIONPDV  = @p_CODCICLOFACTURACIONPDV
      AND VPVF.CODLINEADENEGOCIO       = @p_CODLINEADENEGOCIO
      -- Filters
      AND VPVF.CODAGRUPACIONPUNTODEVENTA = CASE WHEN @pg_CADENA = '-1' THEN VPVF.CODAGRUPACIONPUNTODEVENTA ELSE WSXML_SFG.AGRUPACION_F(@pg_CADENA) END
      AND VPVF.CODALIADOESTRATEGICO = CASE WHEN @pg_ALIADOESTRATEGICO = '-1' THEN VPVF.CODALIADOESTRATEGICO ELSE WSXML_SFG.ALIADOESTRATEGICO_F(@pg_ALIADOESTRATEGICO) END
      AND VPVF.ID_PRODUCTO = CASE WHEN @pg_PRODUCTO = '-1' THEN VPVF.ID_PRODUCTO ELSE WSXML_SFG.PRODUCTO_F(@pg_PRODUCTO) END
      -- Conditions
      AND VPVF.CODAGRUPACIONPUNTODEVENTA <> WSXML_SFG.AGRUPACION_F(0)
      GROUP BY VPVF.CODIGOAGRUPACIONGTECH
      ORDER BY VPVF.CODIGOAGRUPACIONGTECH;
	
  END;

