USE SFGPRODU;
--  DDL for Package Body SFGINF_INVPOSBP00
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGINF_INVPOSBP00 */ 

  IF OBJECT_ID('WSXML_SFG.SFGINF_INVPOSBP00_GetReportData', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGINF_INVPOSBP00_GetReportData;
GO

CREATE     PROCEDURE WSXML_SFG.SFGINF_INVPOSBP00_GetReportData(@p_CODCICLOFACTURACIONPDV NUMERIC(22,0),
                          @p_CODLINEADENEGOCIO      NUMERIC(22,0),
                          @pg_CADENA                NVARCHAR(2000),
                          @pg_ALIADOESTRATEGICO     NVARCHAR(2000),
                         @pg_PRODUCTO              NVARCHAR(2000)
                          ) AS
  BEGIN
  SET NOCOUNT ON;
        
    SELECT '00POS' AS RECORD_TYPE,
           VPVF.CODIGOGTECHPUNTODEVENTA AS POS,
           VPVF.NUMEROTERMINAL          AS TERM,
           SUM(VPVF.VALORVENTA)         AS ACCEPTEDTRANSACTIONS,
           SUM(VPVF.VALORANULACION)     AS CNCELLEDTRANSACTIONS,
           SUM(VPVF.VALORCOMISION)      AS COMISSION_WITHOUTVAT,
           SUM(VPVF.VATCOMISION)        AS COMISSION_VAT,
           SUM(VPVF.VALORCOMISIONBRUTA) AS COMISSION_WITHVAT,
           SUM(VPVF.RETENCION_RENTA)    AS TAX_RENTA,
           SUM(VPVF.RETENCION_RETEICA)  AS TAX_INDCOME,
           SUM(VPVF.RETENCION_RETEIVA)  AS TAX_IVA,
           SUM(VPVF.RETENCION_RETECREE)  AS TAX_CREE,
           SUM(VPVF.VALORCOMISIONNETA)  AS COMISSION_FINAL,
           SUM((VPVF.FACTURADOENCONTRAGTECH - VPVF.FACTURADOAFAVORGTECH) +
               (VPVF.FACTURADOENCONTRAFIDUCIA - VPVF.FACTURADOAFAVORFIDUCIA))
                                        AS TOTALBILLING
    FROM WSXML_SFG.VW_SHOW_PDVFACTURACION VPVF
    WHERE VPVF.ID_CICLOFACTURACIONPDV = @p_CODCICLOFACTURACIONPDV
      AND VPVF.CODLINEADENEGOCIO      = @p_CODLINEADENEGOCIO
      -- Filters
      AND VPVF.CODAGRUPACIONPUNTODEVENTA = CASE WHEN @pg_CADENA = '-1' THEN VPVF.CODAGRUPACIONPUNTODEVENTA ELSE WSXML_SFG.AGRUPACION_F(@pg_CADENA) END
      AND VPVF.CODALIADOESTRATEGICO = CASE WHEN @pg_ALIADOESTRATEGICO = '-1' THEN VPVF.CODALIADOESTRATEGICO ELSE WSXML_SFG.ALIADOESTRATEGICO_F(@pg_ALIADOESTRATEGICO) END
      AND VPVF.ID_PRODUCTO = CASE WHEN @pg_PRODUCTO = '-1' THEN VPVF.ID_PRODUCTO ELSE WSXML_SFG.PRODUCTO_F(@pg_PRODUCTO) END
      -- Conditions
      AND VPVF.CODAGRUPACIONPUNTODEVENTA = WSXML_SFG.AGRUPACION_F(0)
      GROUP BY VPVF.CODIGOGTECHPUNTODEVENTA, VPVF.NUMEROTERMINAL
      ORDER BY VPVF.CODIGOGTECHPUNTODEVENTA;
		  
  END;

