USE SFGPRODU;
--  DDL for Package Body SFGINF_CERTIFICADOSRETEFUENTE
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGINF_CERTIFICADOSRETEFUENTE */ 

  IF OBJECT_ID('WSXML_SFG.SFGINF_CERTIFICADOSRETEFUENTE_GetCertificadosInfo', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGINF_CERTIFICADOSRETEFUENTE_GetCertificadosInfo;
GO
CREATE     PROCEDURE WSXML_SFG.SFGINF_CERTIFICADOSRETEFUENTE_GetCertificadosInfo(@p_ANOGENERACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT RSC.ID_RAZONSOCIAL          AS CODRAZONSOCIAL,
             RSC.NOMRAZONSOCIAL          AS NOMRAZONSOCIAL,
             RSC.IDENTIFICACION          AS IDENTIFICACION,
             RSC.DIGITOVERIFICACION      AS DIGITOVERIFICACION,
             CTO.FECHACONTRATO           AS FECHACONTRATO,
             CRE.CODCOMPANIA             AS CODCOMPANIA,
             CRE.CODTIPOCONTRATOPDV      AS CODTIPOCONTRATOPDV,
             PCT.CODTIPOCONTRATOPRODUCTO AS CODTIPOCONTRATOPRODUCTO,
             DEPARTAMENTO.NOMDEPARTAMENTO AS DEPARTAMENTO,
             SUM(CASE WHEN CODLINEADENEGOCIO = 1 THEN CRE.COMISION ELSE 0 END) AS COMISIONRETEUVT,
             SUM(CASE WHEN CODLINEADENEGOCIO <> 1 THEN CRE.COMISION ELSE 0 END) AS COMISIONOTROS,
             SUM(CRE.COMISION)           AS COMISION,
             SUM(ISNULL(UVT.RETEUVT, 0))    AS RETEUVT,
             SUM(ISNULL(RET.RETEFUENTE, 0)) AS RETEFUENTE
      FROM WSXML_SFG.CIERREANUALTRIBUTARIO CRE
      INNER JOIN WSXML_SFG.PUNTODEVENTA         PDV ON (PDV.ID_PUNTODEVENTA         = CRE.CODPUNTODEVENTA)
      INNER JOIN WSXML_SFG.RAZONSOCIAL          RSC ON (RSC.ID_RAZONSOCIAL          = PDV.CODRAZONSOCIAL)
      INNER JOIN WSXML_SFG.PRODUCTOCONTRATO     PCT ON (PCT.CODPRODUCTO             = CRE.CODPRODUCTO)
      INNER JOIN WSXML_SFG.TIPOCONTRATOPRODUCTO TCP ON (TCP.ID_TIPOCONTRATOPRODUCTO = PCT.CODTIPOCONTRATOPRODUCTO)
      INNER JOIN WSXML_SFG.PRODUCTO             PRD ON (PRD.ID_PRODUCTO             = CRE.CODPRODUCTO)
      INNER JOIN WSXML_SFG.TIPOPRODUCTO         TPR ON (TPR.ID_TIPOPRODUCTO         = PRD.CODTIPOPRODUCTO)
      -- Fecha del contrato
      LEFT OUTER JOIN (SELECT CODRAZONSOCIAL, MIN(FECHACONTRATO) AS FECHACONTRATO
                       FROM WSXML_SFG.RAZONSOCIALCONTRATO GROUP BY CODRAZONSOCIAL) CTO ON (CTO.CODRAZONSOCIAL = RSC.ID_RAZONSOCIAL)
      LEFT OUTER JOIN (SELECT CODCIERREANUALTRIBUTARIO, SUM(VALORRETENCION) AS RETEUVT
                       FROM CIERREANUALRETUVT
                       GROUP BY CODCIERREANUALTRIBUTARIO) UVT ON (UVT.CODCIERREANUALTRIBUTARIO = CRE.ID_CIERREANUALTRIBUTARIO)
      LEFT OUTER JOIN (SELECT CODCIERREANUALTRIBUTARIO, SUM(CASE WHEN CODRETENCIONTRIBUTARIA = 1 THEN VALORRETENCION ELSE 0 END) AS RETEFUENTE,
                                                        SUM(CASE WHEN CODRETENCIONTRIBUTARIA = 2 THEN VALORRETENCION ELSE 0 END) AS RETEICA,
                                                        SUM(CASE WHEN CODRETENCIONTRIBUTARIA = 3 THEN VALORRETENCION ELSE 0 END) AS RETEIVA
                       FROM CIERREANUALRETENCION
                       GROUP BY CODCIERREANUALTRIBUTARIO
					   ) RET ON (RET.CODCIERREANUALTRIBUTARIO = CRE.ID_CIERREANUALTRIBUTARIO)
      INNER JOIN WSXML_SFG.CIUDAD ON RSC.CODCIUDAD = CIUDAD.ID_CIUDAD
      INNER JOIN WSXML_SFG.DEPARTAMENTO ON CIUDAD.CODDEPARTAMENTO = DEPARTAMENTO.ID_DEPARTAMENTO
      WHERE CRE.ANOREFERENCIA = @p_ANOGENERACION AND CRE.CODTIPOCONTRATOPDV=1
      GROUP BY RSC.ID_RAZONSOCIAL, RSC.NOMRAZONSOCIAL, RSC.IDENTIFICACION, RSC.DIGITOVERIFICACION, CTO.FECHACONTRATO, CRE.CODCOMPANIA, CRE.CODTIPOCONTRATOPDV, PCT.CODTIPOCONTRATOPRODUCTO, TCP.ORDEN,DEPARTAMENTO.NOMDEPARTAMENTO
      ORDER BY RSC.ID_RAZONSOCIAL, CRE.CODCOMPANIA, CRE.CODTIPOCONTRATOPDV, TCP.ORDEN;
  END;


GO


