USE SFGPRODU;
--  DDL for Package Body SFGINF_CIS
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGINF_CIS */ 

  IF OBJECT_ID('WSXML_SFG.SFGINF_CIS_GetCISJuegos', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGINF_CIS_GetCISJuegos;
GO

CREATE     PROCEDURE WSXML_SFG.SFGINF_CIS_GetCISJuegos(@p_CODCICLOFACTURACIONPDV NUMERIC(22,0),
                         @p_CODLINEADENEGOCIO      NUMERIC(22,0),
                         @pg_CADENA                NVARCHAR(2000),
                         @pg_ALIADOESTRATEGICO     NVARCHAR(2000),
                        @pg_PRODUCTO              NVARCHAR(2000)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT FECHAARCHIVO AS FECHAARCHIVO,
            SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 1 AND PRODUCTO.CODIGOGTECHPRODUCTO NOT IN ('19999') THEN NUMINGRESOS - NUMANULACIONES ELSE 0 END) AS NUMINGRESOS1,
            SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 1 AND PRODUCTO.CODIGOGTECHPRODUCTO NOT IN ('19999') THEN INGRESOS - ANULACIONES ELSE 0 END)       AS INGRESOS1,
            SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 1 AND PRODUCTO.CODIGOGTECHPRODUCTO NOT IN ('19999') THEN INGRESOSBRUTOSNOREDONDEO ELSE 0 END)     AS INGRESOSBRUTOS1,
            SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 1 AND PRODUCTO.CODIGOGTECHPRODUCTO NOT IN ('19999') THEN REVENUETOTAL ELSE 0 END)                 AS REVENUE1,
            SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 1 AND PRODUCTO.CODIGOGTECHPRODUCTO NOT IN ('19999') THEN INGRESOCORPORATIVO ELSE 0 END)           AS CORPORATIVO1,
            SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 1 AND PRODUCTO.CODIGOGTECHPRODUCTO = '19999' THEN NUMINGRESOS - NUMANULACIONES ELSE 0 END) AS NUMINGRESOS11,
            SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 1 AND PRODUCTO.CODIGOGTECHPRODUCTO = '19999' THEN INGRESOS - ANULACIONES ELSE 0 END)       AS INGRESOS11,
            SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 1 AND PRODUCTO.CODIGOGTECHPRODUCTO = '19999' THEN INGRESOSBRUTOSNOREDONDEO ELSE 0 END)     AS INGRESOSBRUTOS11,
            SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 1 AND PRODUCTO.CODIGOGTECHPRODUCTO = '19999' THEN REVENUETOTAL ELSE 0 END)                 AS REVENUE11,
            SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 1 AND PRODUCTO.CODIGOGTECHPRODUCTO = '19999' THEN INGRESOCORPORATIVO ELSE 0 END)           AS CORPORATIVO11,

            SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 2 THEN NUMINGRESOS - NUMANULACIONES ELSE 0 END) AS NUMINGRESOS2,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 2 THEN INGRESOS - ANULACIONES ELSE 0 END)       AS INGRESOS2,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 2 THEN INGRESOSBRUTOSNOREDONDEO ELSE 0 END)     AS INGRESOSBRUTOS2,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 2 THEN REVENUETOTAL ELSE 0 END)                 AS REVENUE2,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 2 THEN INGRESOCORPORATIVO ELSE 0 END)           AS CORPORATIVO2,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 3 THEN NUMINGRESOS - NUMANULACIONES ELSE 0 END) AS NUMINGRESOS3,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 3 THEN INGRESOS - ANULACIONES ELSE 0 END)       AS INGRESOS3,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 3 THEN INGRESOSBRUTOSNOREDONDEO ELSE 0 END)     AS INGRESOSBRUTOS3,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 3 THEN REVENUETOTAL ELSE 0 END)                 AS REVENUE3,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 3 THEN INGRESOCORPORATIVO ELSE 0 END)           AS CORPORATIVO3,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 4 THEN NUMINGRESOS - NUMANULACIONES ELSE 0 END) AS NUMINGRESOS4,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 4 THEN INGRESOS - ANULACIONES ELSE 0 END)       AS INGRESOS4,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 4 THEN INGRESOSBRUTOSNOREDONDEO ELSE 0 END)     AS INGRESOSBRUTOS4,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 4 THEN REVENUETOTAL ELSE 0 END)                 AS REVENUE4,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 4 THEN INGRESOCORPORATIVO ELSE 0 END)           AS CORPORATIVO4,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 5 THEN NUMINGRESOS - NUMANULACIONES ELSE 0 END) AS NUMINGRESOS5,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 5 THEN INGRESOS - ANULACIONES ELSE 0 END)       AS INGRESOS5,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 5 THEN INGRESOSBRUTOSNOREDONDEO ELSE 0 END)     AS INGRESOSBRUTOS5,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 5 THEN REVENUETOTAL ELSE 0 END)                 AS REVENUE5,
             SUM(CASE WHEN PRF.CODTIPOPRODUCTO = 5 THEN INGRESOCORPORATIVO ELSE 0 END)           AS CORPORATIVO5
      FROM WSXML_SFG.VW_REVENUE_DIARIO PRF
      INNER JOIN WSXML_SFG.PRODUCTO ON PRF.CODPRODUCTO = PRODUCTO.ID_PRODUCTO
      WHERE CODCICLOFACTURACIONPDV = @p_CODCICLOFACTURACIONPDV
      GROUP BY FECHAARCHIVO ORDER BY FECHAARCHIVO;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGINF_CIS_GetCISServComerciales', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGINF_CIS_GetCISServComerciales;
GO

CREATE     PROCEDURE WSXML_SFG.SFGINF_CIS_GetCISServComerciales(@p_CODCICLOFACTURACIONPDV NUMERIC(22,0),
                                  @p_CODLINEADENEGOCIO      NUMERIC(22,0),
                                  @pg_CADENA                NVARCHAR(2000),
                                  @pg_ALIADOESTRATEGICO     NVARCHAR(2000),
                                 @pg_PRODUCTO              NVARCHAR(2000)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT FECHAARCHIVO AS FECHAARCHIVO,
             SUM(CASE WHEN CODLINEADENEGOCIO = 2 THEN NUMINGRESOS - NUMANULACIONES ELSE 0 END) AS NUMINGRESOS2,
             SUM(CASE WHEN CODLINEADENEGOCIO = 2 THEN INGRESOS - ANULACIONES ELSE 0 END)       AS INGRESOS2,
             SUM(CASE WHEN CODLINEADENEGOCIO = 2 THEN INGRESOSBRUTOSNOREDONDEO ELSE 0 END)     AS INGRESOSBRUTOS2,
             SUM(CASE WHEN CODLINEADENEGOCIO = 2 THEN REVENUETOTAL ELSE 0 END)                 AS REVENUE2,
             SUM(CASE WHEN CODLINEADENEGOCIO = 2 THEN INGRESOCORPORATIVO ELSE 0 END)           AS CORPORATIVO2,
             SUM(CASE WHEN CODLINEADENEGOCIO = 3 THEN NUMINGRESOS - NUMANULACIONES ELSE 0 END) AS NUMINGRESOS3,
             SUM(CASE WHEN CODLINEADENEGOCIO = 3 THEN INGRESOS - ANULACIONES ELSE 0 END)       AS INGRESOS3,
             SUM(CASE WHEN CODLINEADENEGOCIO = 3 THEN INGRESOSBRUTOSNOREDONDEO ELSE 0 END)     AS INGRESOSBRUTOS3,
             SUM(CASE WHEN CODLINEADENEGOCIO = 3 THEN REVENUETOTAL ELSE 0 END)                 AS REVENUE3,
             SUM(CASE WHEN CODLINEADENEGOCIO = 3 THEN INGRESOCORPORATIVO ELSE 0 END)           AS CORPORATIVO3,
             SUM(CASE WHEN CODLINEADENEGOCIO = 4 THEN NUMINGRESOS - NUMANULACIONES ELSE 0 END) AS NUMINGRESOS4,
             SUM(CASE WHEN CODLINEADENEGOCIO = 4 THEN INGRESOS - ANULACIONES ELSE 0 END)       AS INGRESOS4,
             SUM(CASE WHEN CODLINEADENEGOCIO = 4 THEN INGRESOSBRUTOSNOREDONDEO ELSE 0 END)     AS INGRESOSBRUTOS4,
             SUM(CASE WHEN CODLINEADENEGOCIO = 4 THEN REVENUETOTAL ELSE 0 END)                 AS REVENUE4,
             SUM(CASE WHEN CODLINEADENEGOCIO = 4 THEN INGRESOCORPORATIVO ELSE 0 END)           AS CORPORATIVO4
      FROM WSXML_SFG.VW_REVENUE_DIARIO
      WHERE CODCICLOFACTURACIONPDV = @p_CODCICLOFACTURACIONPDV
      GROUP BY FECHAARCHIVO ORDER BY FECHAARCHIVO;
  END;

GO


