USE SFGPRODU;
--  DDL for Package Body SFGINF_ANULACIONESMENSUAL
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGINF_ANULACIONESMENSUAL */ 

  IF OBJECT_ID('WSXML_SFG.SFGINF_ANULACIONESMENSUAL_GetReporteAnulacionesData', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGINF_ANULACIONESMENSUAL_GetReporteAnulacionesData;
GO

CREATE     PROCEDURE WSXML_SFG.SFGINF_ANULACIONESMENSUAL_GetReporteAnulacionesData(@p_CODCICLOFACTURACIONPDV NUMERIC(22,0),
                                      @p_CODLINEADENEGOCIO      NUMERIC(22,0),
                                      @pg_CADENA                NVARCHAR(2000),
                                      @pg_ALIADOESTRATEGICO     NVARCHAR(2000),
                                     @pg_PRODUCTO              NVARCHAR(2000)) AS
 BEGIN
    DECLARE @sFECHACCLO DATETIME;
    DECLARE @xPRIMERCLO NUMERIC(22,0);
   
  SET NOCOUNT ON;
    SELECT @sFECHACCLO = FECHAEJECUCION FROM WSXML_SFG.CICLOFACTURACIONPDV WHERE ID_CICLOFACTURACIONPDV = @p_CODCICLOFACTURACIONPDV;
    -- Obtener el primer ciclo del mes. Las anulaciones vendran a partir de los archivos con el codigo
    SELECT @xPRIMERCLO = MIN(ID_CICLOFACTURACIONPDV) FROM WSXML_SFG.CICLOFACTURACIONPDV
    WHERE CONVERT(DATETIME, CONVERT(VARCHAR(7), FECHAEJECUCION, 120) + '-01') = CONVERT(DATETIME, CONVERT(VARCHAR(7), @sFECHACCLO, 120) + '-01') AND ACTIVE = 1;
    -- Obtener anulaciones realizadas por transaccion al ciclo establecido
      SELECT WSXML_SFG.SFG_PACKAGE_GETNUMEROCDC (CTR.FECHAARCHIVO) AS CDC,
             PDV.CODIGOGTECHPUNTODEVENTA                AS POS,
             PDV.NUMEROTERMINAL                         AS TERM,
             PDV.NOMPUNTODEVENTA                        AS PUNTODEVENTA,
             PRD.CODIGOGTECHPRODUCTO                    AS PRD,
             PRD.NOMPRODUCTO                            AS PRODUCTO,
             RFR.NUMEROREFERENCIA                       AS REFERENCIA,
             RFR.FECHAHORATRANSACCION                   AS FECHAHORATRANSACCION,
             RFR.VALORTRANSACCION                       AS VALORTRANSACCION,
             RFR.FECHAHORAANULACION                     AS FECHAHORAANULACION
      FROM WSXML_SFG.ENTRADAARCHIVOCONTROL CTR
      INNER JOIN WSXML_SFG.REGISTROFACTURACION    REG ON (CODENTRADAARCHIVOCONTROL   = ID_ENTRADAARCHIVOCONTROL)
      INNER JOIN WSXML_SFG.REGISTROFACTREFERENCIA RFR ON (RFR.CODREGISTROFACTURACION = REG.ID_REGISTROFACTURACION)
      INNER JOIN WSXML_SFG.PUNTODEVENTA           PDV ON (PDV.ID_PUNTODEVENTA        = REG.CODPUNTODEVENTA)
      INNER JOIN WSXML_SFG.PRODUCTO               PRD ON (PRD.ID_PRODUCTO            = REG.CODPRODUCTO)
      INNER JOIN WSXML_SFG.TIPOPRODUCTO           TPR ON (TPR.ID_TIPOPRODUCTO        = PRD.CODTIPOPRODUCTO)
      WHERE CTR.CODCICLOFACTURACIONPDV = @xPRIMERCLO
        AND TPR.CODLINEADENEGOCIO      = @p_CODLINEADENEGOCIO
        AND CONVERT(DATETIME, CONVERT(VARCHAR(7), RFR.FECHAHORATRANSACCION, 120) + '-01') <> CONVERT(DATETIME, CONVERT(VARCHAR(7), RFR.FECHAHORAANULACION, 120) + '-01')
        AND RFR.ANULADO = 1;
  END;


GO


