USE SFGPRODU;
--  DDL for Package Body SFGINF_DSPAYMENTS
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGINF_DSPAYMENTS */ 

  /* Valores a recaudar */
  
 IF OBJECT_ID('WSXML_SFG.SFGINF_DSPAYMENTS_GetReportData', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGINF_DSPAYMENTS_GetReportData;
GO

CREATE     PROCEDURE WSXML_SFG.SFGINF_DSPAYMENTS_GetReportData(@p_CODCICLOFACTURACIONPDV NUMERIC(22,0),
                          @p_CODLINEADENEGOCIO      NUMERIC(22,0),
                          @pg_CADENA                NVARCHAR(2000),
                          @pg_ALIADOESTRATEGICO     NVARCHAR(2000),
                         @pg_PRODUCTO              NVARCHAR(2000)
                          ) AS
  BEGIN
  SET NOCOUNT ON;
    -- Particularidad: Union entre Agrupaciones y Terminales con Saldo > 0
	
      SELECT CODIGOGTECHPUNTODEVENTA,
             VALORCOMISIONNETA
      FROM (SELECT CODIGOGTECHPUNTODEVENTA, VALORCOMISIONNETA
              FROM WSXML_SFG.VW_SHOW_LDNFACTURACION
             WHERE ID_CICLOFACTURACIONPDV = @p_CODCICLOFACTURACIONPDV
               AND CODLINEADENEGOCIO      = @p_CODLINEADENEGOCIO
               AND @pg_ALIADOESTRATEGICO   = @pg_ALIADOESTRATEGICO
               AND @pg_PRODUCTO            = @pg_PRODUCTO
               AND @pg_CADENA              = @pg_CADENA
               AND CODTIPOPUNTODEVENTA IN (2, 3)
               AND VALORCOMISIONNETA > 0

             UNION

            SELECT HEAD.CODIGOGTECHPUNTODEVENTA, SUM(VALORCOMISIONNETA) AS VALORCOMISIONNETA
              FROM WSXML_SFG.VW_SHOW_LDNFACTURACION PRF
             INNER JOIN AGRUPACIONPUNTODEVENTA ON (CODAGRUPACIONPUNTODEVENTA = ID_AGRUPACIONPUNTODEVENTA)
             INNER JOIN PUNTODEVENTA HEAD ON (CODPUNTODEVENTACABEZA = HEAD.ID_PUNTODEVENTA)
             WHERE ID_CICLOFACTURACIONPDV = @p_CODCICLOFACTURACIONPDV
               AND CODLINEADENEGOCIO      = @p_CODLINEADENEGOCIO
               AND @pg_ALIADOESTRATEGICO   = @pg_ALIADOESTRATEGICO
               AND @pg_PRODUCTO            = @pg_PRODUCTO
               AND @pg_CADENA              = @pg_CADENA
               AND PRF.CODTIPOPUNTODEVENTA = 1
             GROUP BY HEAD.CODIGOGTECHPUNTODEVENTA
            HAVING SUM(VALORCOMISIONNETA) > 0) s
      ORDER BY CAST(CODIGOGTECHPUNTODEVENTA AS INT);
	  
  END;


