USE SFGPRODU;
--  DDL for Package Body SFGINCENTIVOCOMISIONGLOBAL
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGINCENTIVOCOMISIONGLOBAL */ 

  IF OBJECT_ID('WSXML_SFG.SFGINCENTIVOCOMISIONGLOBAL_SetIncentivo', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGINCENTIVOCOMISIONGLOBAL_SetIncentivo;
GO

CREATE     PROCEDURE WSXML_SFG.SFGINCENTIVOCOMISIONGLOBAL_SetIncentivo(@p_CODPERIODICIDAD              NUMERIC(22,0),
                         @p_VALORFIJO                    FLOAT,
                         @p_CODPUNTODEVENTATRANSACCION   NUMERIC(22,0),
                         @p_CODPRODUCTOTRANSACCION       NUMERIC(22,0),
                         @p_CODUSUARIOMODIFICACION       NUMERIC(22,0),
                         @p_ID_INCENTIVOCOMISIONGLBL_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;

    INSERT INTO WSXML_SFG.INCENTIVOCOMISIONGLOBAL (
                                         CODPERIODICIDAD,
                                         VALORFIJO,
                                         CODPUNTODEVENTATRANSACCION,
                                         CODPRODUCTOTRANSACCION,
                                         CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODPERIODICIDAD,
            @p_VALORFIJO,
            @p_CODPUNTODEVENTATRANSACCION,
            @p_CODPRODUCTOTRANSACCION,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_INCENTIVOCOMISIONGLBL_out = SCOPE_IDENTITY();

    --Inactivar los valores antiguos
    UPDATE WSXML_SFG.INCENTIVOCOMISIONGLOBAL SET ACTIVE = 0
    WHERE @p_CODPRODUCTOTRANSACCION=@p_CODPRODUCTOTRANSACCION
    AND INCENTIVOCOMISIONGLOBAL.ID_INCENTIVOCOMISIONGLOBAL<>@p_ID_INCENTIVOCOMISIONGLBL_out;


  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGINCENTIVOCOMISIONGLOBAL_SetIncentivoDependencia', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGINCENTIVOCOMISIONGLOBAL_SetIncentivoDependencia;
GO

CREATE     PROCEDURE WSXML_SFG.SFGINCENTIVOCOMISIONGLOBAL_SetIncentivoDependencia(@p_CODINCENTIVOCOMISIONGLOBAL NUMERIC(22,0),
                                    @p_FECHAINICIOVALIDEZ         DATETIME,
                                    @p_VALORFIJO                  FLOAT,
                                    @p_CODUSUARIOMODIFICACION     NUMERIC(22,0)) AS
 BEGIN
    DECLARE @cCOUNTDIFERENCIALES NUMERIC(22,0);
    DECLARE @existingdep NUMERIC(22,0);
   
  SET NOCOUNT ON;
    SELECT @cCOUNTDIFERENCIALES = COUNT(1) FROM WSXML_SFG.INCENTIVOCOMISIONHISTORICO WHERE CODINCENTIVOCOMISIONGLOBAL = @p_CODINCENTIVOCOMISIONGLOBAL;
    IF @cCOUNTDIFERENCIALES = 0 BEGIN
      UPDATE WSXML_SFG.INCENTIVOCOMISIONGLOBAL SET VALORFIJO = @p_VALORFIJO WHERE ID_INCENTIVOCOMISIONGLOBAL = @p_CODINCENTIVOCOMISIONGLOBAL;
    END 
    BEGIN
      SELECT @existingdep = ID_INCENTIVOCOMISIONHISTORICO FROM WSXML_SFG.INCENTIVOCOMISIONHISTORICO
      WHERE CODINCENTIVOCOMISIONGLOBAL = @p_CODINCENTIVOCOMISIONGLOBAL AND FECHAINICIOVALIDEZ = CONVERT(DATETIME, CONVERT(DATE,@p_FECHAINICIOVALIDEZ));
      UPDATE WSXML_SFG.INCENTIVOCOMISIONHISTORICO SET VALORFIJO = @p_VALORFIJO WHERE ID_INCENTIVOCOMISIONHISTORICO = @existingdep;
		IF @@ROWCOUNT = 0
		  INSERT INTO WSXML_SFG.INCENTIVOCOMISIONHISTORICO (
												  CODINCENTIVOCOMISIONGLOBAL,
												  FECHAINICIOVALIDEZ,
												  VALORFIJO,
												  CODUSUARIOMODIFICACION)
		  VALUES (
				  @p_CODINCENTIVOCOMISIONGLOBAL,
				  CONVERT(DATETIME, CONVERT(DATE,@p_FECHAINICIOVALIDEZ)),
				  @p_VALORFIJO,
				  @p_CODUSUARIOMODIFICACION);
    END;
  END;

GO

