USE SFGPRODU;
--  DDL for Package Body SFGINF_FACGTECH
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGINF_FACGTECH */ 

  /* Total a recaudar por concepto GTECH */
  IF OBJECT_ID('WSXML_SFG.SFGINF_FACGTECH_GetReportData', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGINF_FACGTECH_GetReportData;
GO

CREATE     PROCEDURE WSXML_SFG.SFGINF_FACGTECH_GetReportData(@p_CODCICLOFACTURACIONPDV NUMERIC(22,0),
                          @p_CODLINEADENEGOCIO      NUMERIC(22,0),
                          @pg_CADENA                NVARCHAR(2000),
                          @pg_ALIADOESTRATEGICO     NVARCHAR(2000),
                         @pg_PRODUCTO              NVARCHAR(2000)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT FECHAINICIO,
             NUMEROTERMINAL,
             CASE WHEN SALDOGTECH > 0 THEN SALDOGTECH ELSE 0 END AS SALDOGTECH,
             REFERENCIA,
             ACUMULADO
      FROM (SELECT CONVERT(DATETIME,FECHACICLO) + 2 AS FECHAINICIO,
                   NUMEROTERMINAL,
                   SALDOGTECH,
                   REFERENCIA,
                   SUM(SALDOGTECH) OVER (ORDER BY CAST(NUMEROTERMINAL AS NUMERIC(38,0))) AS ACUMULADO
            FROM (
				SELECT CFP.FECHAEJECUCION                 AS FECHACICLO,
                         VLD.CODTIPOPUNTODEVENTA            AS TIPOAGRUPACION,
						 CASE WHEN VLD.CODTIPOPUNTODEVENTA = 1 THEN '9' + RIGHT(REPLICATE('0', 4) + MIN(VLD.CODIGOAGRUPACIONGTECH), 4)
                              ELSE MIN(VLD.NUMEROTERMINAL)
                         END AS NUMEROTERMINAL,
                         SUM(VLD.NUEVOSALDOENCONTRAGTECH -
                             VLD.NUEVOSALDOAFAVORGTECH)     AS SALDOGTECH,
                         VLD.REFERENCIAGTECH                AS REFERENCIA
                  FROM WSXML_SFG.VW_SHOW_LDNFACTURACION VLD
                  INNER JOIN WSXML_SFG.CICLOFACTURACIONPDV CFP ON (CFP.ID_CICLOFACTURACIONPDV = VLD.ID_CICLOFACTURACIONPDV)
                  WHERE VLD.ID_CICLOFACTURACIONPDV = @p_CODCICLOFACTURACIONPDV
                    AND VLD.CODLINEADENEGOCIO      = @p_CODLINEADENEGOCIO
                    AND @pg_ALIADOESTRATEGICO       = @pg_ALIADOESTRATEGICO
                    AND @pg_PRODUCTO                = @pg_PRODUCTO
                    -- Filters
                    AND VLD.CODAGRUPACIONPUNTODEVENTA = CASE WHEN @pg_CADENA = '-1' THEN VLD.CODAGRUPACIONPUNTODEVENTA ELSE WSXML_SFG.AGRUPACION_F(@pg_CADENA) END
                  GROUP BY CFP.FECHAEJECUCION, VLD.CODTIPOPUNTODEVENTA, VLD.REFERENCIAGTECH
			) T
            --ORDER BY CAST(NUMEROTERMINAL AS NUMERIC(38,5))
		) S

END 
GO


