USE SFGPRODU;
--  DDL for Package Body SFGPRODCONTRATOHISTORICO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGPRODCONTRATOHISTORICO */ 

  IF OBJECT_ID('WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDependence', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDependence;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDependence(@p_CODPRODUCTOCONTRATO          NUMERIC(22,0),
                          @p_FECHAINICIOVALIDEZ           DATETIME,
                          @p_CODTIPOCONTRATOPRODUCTO      NUMERIC(22,0),
                          @p_CODRANGOCOMISION             NUMERIC(22,0),
                          @p_CODUSUARIOMODIFICACION       NUMERIC(22,0),
                          @p_ID_PRODCONTRATOHISTORICO_out NUMERIC(22,0) OUT) AS
 BEGIN
    DECLARE @cFECHADETERMINA DATETIME = CONVERT(DATETIME, CONVERT(DATE,@p_FECHAINICIOVALIDEZ));
   
  SET NOCOUNT ON;
    SELECT @p_ID_PRODCONTRATOHISTORICO_out = ID_PRODCONTRATOHISTORICO FROM WSXML_SFG.PRODCONTRATOHISTORICO
    WHERE CODPRODUCTOCONTRATO = @p_CODPRODUCTOCONTRATO AND FECHAINICIOVALIDEZ = @cFECHADETERMINA;
    UPDATE WSXML_SFG.PRODCONTRATOHISTORICO SET CODTIPOCONTRATOPRODUCTO = @p_CODTIPOCONTRATOPRODUCTO,
                                     CODRANGOCOMISION        = @p_CODRANGOCOMISION,
                                     CODUSUARIOMODIFICACION  = @p_CODUSUARIOMODIFICACION,
                                     FECHAHORAMODIFICACION   = GETDATE()
    WHERE ID_PRODCONTRATOHISTORICO = @p_ID_PRODCONTRATOHISTORICO_out;
  
	IF @@ROWCOUNT = 0 
	BEGIN
		INSERT INTO WSXML_SFG.PRODCONTRATOHISTORICO (
										   CODPRODUCTOCONTRATO,
										   FECHAINICIOVALIDEZ,
										   CODTIPOCONTRATOPRODUCTO,
										   CODRANGOCOMISION,
										   CODUSUARIOMODIFICACION)
		VALUES (
				@p_CODPRODUCTOCONTRATO,
				@cFECHADETERMINA,
				@p_CODTIPOCONTRATOPRODUCTO,
				@p_CODRANGOCOMISION,
				@p_CODUSUARIOMODIFICACION);
		SET @p_ID_PRODCONTRATOHISTORICO_out = SCOPE_IDENTITY();
	END
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDependenceFromProduct', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDependenceFromProduct;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDependenceFromProduct(@p_CODPRODUCTO             NUMERIC(22,0),
                                     @p_FECHAINICIOVALIDEZ      DATETIME,
                                     @p_CODTIPOCONTRATOPRODUCTO NUMERIC(22,0),
                                     @p_CODRANGOCOMISION        NUMERIC(22,0),
                                     @p_CODUSUARIOMODIFICACION  NUMERIC(22,0)) AS
 BEGIN
    DECLARE @cCODPRODUCTOCONTRATO NUMERIC(22,0);
    DECLARE @cCOUNTDIFERENCIALES  NUMERIC(22,0);
    DECLARE @cout NUMERIC(22,0);
   
  SET NOCOUNT ON;
    BEGIN
      SELECT @cCODPRODUCTOCONTRATO = ID_PRODUCTOCONTRATO FROM WSXML_SFG.PRODUCTOCONTRATO WHERE CODPRODUCTO = @p_CODPRODUCTO;
		IF @@ROWCOUNT = 0 BEGIN
		
		  EXEC WSXML_SFG.SFGPRODUCTOCONTRATO_SetContrato @p_CODPRODUCTO, @p_CODTIPOCONTRATOPRODUCTO, @p_CODRANGOCOMISION, @p_CODUSUARIOMODIFICACION, @cCODPRODUCTOCONTRATO OUT
		  --RAISE_APPLICATION_ERROR(-20054, 'No se puede establecer dependencia de un producto que no tiene contrato');
		END
    END;
    SELECT @cCOUNTDIFERENCIALES = COUNT(1) FROM WSXML_SFG.PRODCONTRATOHISTORICO WHERE CODPRODUCTOCONTRATO = @cCODPRODUCTOCONTRATO;
    /*IF cCOUNTDIFERENCIALES = 0 THEN
      UPDATE PRODUCTOCONTRATO SET CODRANGOCOMISION = p_CODRANGOCOMISION WHERE ID_PRODUCTOCONTRATO = cCODPRODUCTOCONTRATO;
    END IF;*/
    EXEC WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDependence @cCODPRODUCTOCONTRATO, @p_FECHAINICIOVALIDEZ, @p_CODTIPOCONTRATOPRODUCTO, @p_CODRANGOCOMISION, @p_CODUSUARIOMODIFICACION, @cout OUT
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDifferentialDependence', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDifferentialDependence;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDifferentialDependence(@p_CODPRODUCTOCONTRATOCOMDIF    NUMERIC(22,0),
                                      @p_FECHAINICIOVALIDEZ           DATETIME,
                                      @p_CODRANGOCOMISION             NUMERIC(22,0),
                                      @p_CODUSUARIOMODIFICACION       NUMERIC(22,0),
                                      @p_ID_PRODCONTRATOCOMDIFHST_out NUMERIC(22,0) OUT) AS
 BEGIN
    DECLARE @cFECHADETERMINA DATETIME = CONVERT(DATETIME, CONVERT(DATE,@p_FECHAINICIOVALIDEZ));
   
  SET NOCOUNT ON;
    SELECT @p_ID_PRODCONTRATOCOMDIFHST_out = ID_PRODCONTRATOCOMDIFHISTORICO FROM WSXML_SFG.PRODCONTRATOCOMDIFHISTORICO
    WHERE CODPRODUCTOCONTRATOCOMDIF = @p_CODPRODUCTOCONTRATOCOMDIF AND FECHAINICIOVALIDEZ = @cFECHADETERMINA;
    UPDATE WSXML_SFG.PRODCONTRATOCOMDIFHISTORICO SET CODRANGOCOMISION       = @p_CODRANGOCOMISION,
                                           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
                                           FECHAHORAMODIFICACION  = GETDATE()
    WHERE ID_PRODCONTRATOCOMDIFHISTORICO = @p_ID_PRODCONTRATOCOMDIFHST_out;
    
	IF @@ROWCOUNT = 0 
	BEGIN
		INSERT INTO WSXML_SFG.PRODCONTRATOCOMDIFHISTORICO (
												 CODPRODUCTOCONTRATOCOMDIF,
												 FECHAINICIOVALIDEZ,
												 CODRANGOCOMISION,
												 CODUSUARIOMODIFICACION)
		VALUES (
				@p_CODPRODUCTOCONTRATOCOMDIF,
				@cFECHADETERMINA,
				@p_CODRANGOCOMISION,
				@p_CODUSUARIOMODIFICACION);
		SET @p_ID_PRODCONTRATOCOMDIFHST_out = SCOPE_IDENTITY();
	END
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDifferentialDependenceData', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDifferentialDependenceData;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDifferentialDependenceData(@p_CODPRODUCTO               NUMERIC(22,0),
                                          @p_CODREDPDV                 NUMERIC(22,0),
                                          @p_CODAGRUPACIONPUNTODEVENTA NUMERIC(22,0),
                                          @p_FECHAINICIOVALIDEZ        DATETIME,
                                          @p_CODRANGOCOMISION          NUMERIC(22,0),
                                          @p_CODUSUARIOMODIFICACION    NUMERIC(22,0)) AS
 BEGIN
    DECLARE @cCODPRODUCTOCONTRATO       NUMERIC(22,0);
    DECLARE @cCODPRODUCTOCONTRATOCOMDIF NUMERIC(22,0);
    DECLARE @cCOUNTDIFERENCIALES        NUMERIC(22,0);
    DECLARE @cout NUMERIC(22,0);
   
  SET NOCOUNT ON;
    BEGIN
		SELECT @cCODPRODUCTOCONTRATO = ID_PRODUCTOCONTRATO FROM WSXML_SFG.PRODUCTOCONTRATO WHERE CODPRODUCTO = @p_CODPRODUCTO;
		IF @@ROWCOUNT = 0 
			RAISERROR('-20054 No se puede establecer dependencia de un producto que no tiene contrato', 16, 1);
    END;
    IF @p_CODREDPDV IS NULL
      BEGIN
        SELECT @cCODPRODUCTOCONTRATOCOMDIF = ID_PRODUCTOCONTRATOCOMDIF FROM WSXML_SFG.PRODUCTOCONTRATOCOMDIF
        WHERE CODPRODUCTOCONTRATO       = @cCODPRODUCTOCONTRATO
          AND CODAGRUPACIONPUNTODEVENTA = @p_CODAGRUPACIONPUNTODEVENTA;
		IF @@ROWCOUNT = 0
		BEGIN
			EXEC WSXML_SFG.SFGPRODUCTOCONTRATO_SetContratoComisionDiferencial  @p_CODPRODUCTO, @p_CODREDPDV, @p_CODAGRUPACIONPUNTODEVENTA, @p_CODRANGOCOMISION, @p_CODUSUARIOMODIFICACION, @cCODPRODUCTOCONTRATOCOMDIF OUT
			--RAISE_APPLICATION_ERROR(-20054, 'No se puede establecer dependencia diferencial de un producto que no tiene contrato diferencial');
		END
      END;
    ELSE IF @p_CODAGRUPACIONPUNTODEVENTA IS NULL
      BEGIN
        SELECT @cCODPRODUCTOCONTRATOCOMDIF = ID_PRODUCTOCONTRATOCOMDIF FROM WSXML_SFG.PRODUCTOCONTRATOCOMDIF
        WHERE CODPRODUCTOCONTRATO = @cCODPRODUCTOCONTRATO
          AND CODREDPDV           = @p_CODREDPDV;
        IF @@ROWCOUNT = 0
		BEGIN
			EXEC WSXML_SFG.SFGPRODUCTOCONTRATO_SetContratoComisionDiferencial @p_CODPRODUCTO, @p_CODREDPDV, @p_CODAGRUPACIONPUNTODEVENTA, @p_CODRANGOCOMISION, @p_CODUSUARIOMODIFICACION, @cCODPRODUCTOCONTRATOCOMDIF OUT
			--RAISE_APPLICATION_ERROR(-20054, 'No se puede establecer dependencia diferencial de un producto que no tiene contrato diferencial');
		END
      END;
    ELSE
      RAISERROR('-20085 No es posible asignar dos reglas de comision diferencial al mismo producto', 16, 1);
    
    SELECT @cCOUNTDIFERENCIALES = COUNT(1) FROM WSXML_SFG.PRODCONTRATOCOMDIFHISTORICO WHERE CODPRODUCTOCONTRATOCOMDIF = @cCODPRODUCTOCONTRATOCOMDIF;
    IF @cCOUNTDIFERENCIALES = 0 BEGIN
      UPDATE WSXML_SFG.PRODUCTOCONTRATOCOMDIF SET CODRANGOCOMISION = @p_CODRANGOCOMISION WHERE ID_PRODUCTOCONTRATOCOMDIF = @cCODPRODUCTOCONTRATOCOMDIF;
    END 
    EXEC WSXML_SFG.SFGPRODCONTRATOHISTORICO_AddDifferentialDependence @cCODPRODUCTOCONTRATOCOMDIF, @p_FECHAINICIOVALIDEZ, @p_CODRANGOCOMISION, @p_CODUSUARIOMODIFICACION, @cout OUT
  END;

GO


