USE SFGPRODU;
--  DDL for Package Body SFGPDVPOLITICAPAGO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGPDVPOLITICAPAGO */ 

  IF OBJECT_ID('WSXML_SFG.SFGPDVPOLITICAPAGO_SetPolitica', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPDVPOLITICAPAGO_SetPolitica;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPDVPOLITICAPAGO_SetPolitica(@p_CODPUNTODEVENTA        NUMERIC(22,0),
                        @p_CODLINEADENEGOCIO      NUMERIC(22,0),
                        @p_CODPOLITICAPAGO        NUMERIC(22,0),
                        @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                        @p_ID_PDVPOLITICAPAGO_out NUMERIC(22,0) OUT) AS
 BEGIN
    DECLARE @l_exists NUMERIC(22,0);
   
  SET NOCOUNT ON;
    BEGIN
		
		  SELECT @l_exists = ID_PDVPOLITICAPAGO FROM WSXML_SFG.PDVPOLITICAPAGO
		  WHERE CODPUNTODEVENTA   = @p_CODPUNTODEVENTA
			AND CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
			AND ACTIVE = 1;
		  IF @l_exists > 0 BEGIN
			UPDATE WSXML_SFG.PDVPOLITICAPAGO SET FECHAHORAMODIFICACION  = GETDATE(),
									   CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
									   ACTIVE = 0
			WHERE ID_PDVPOLITICAPAGO = @l_exists;
		  END 
		IF @@ROWCOUNT = 0
		  SELECT NULL;
    END;
    INSERT INTO WSXML_SFG.PDVPOLITICAPAGO (
                                 CODPUNTODEVENTA,
                                 CODLINEADENEGOCIO,
                                 CODPOLITICAPAGO,
                                 CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODPUNTODEVENTA,
            @p_CODLINEADENEGOCIO,
            @p_CODPOLITICAPAGO,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_PDVPOLITICAPAGO_out = SCOPE_IDENTITY();
  END;
GO 

  IF OBJECT_ID('WSXML_SFG.SFGPDVPOLITICAPAGO_GetPolitica', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPDVPOLITICAPAGO_GetPolitica;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPDVPOLITICAPAGO_GetPolitica(@p_CODPUNTODEVENTA    NUMERIC(22,0),
                        @p_CODLINEADENEGOCIO  NUMERIC(22,0),
                        @p_FECHAVERIFICACION  DATETIME,
                        @p_VERIFICARAHORA_out NUMERIC(22,0) OUT) AS
 BEGIN

    DECLARE @FUNCION VARCHAR(2000);
    DECLARE @RESULTADO VARCHAR(5);
   
  SET NOCOUNT ON;
      SELECT @FUNCION = C.FUNCION 
	  FROM WSXML_SFG.PDVPOLITICAPAGO A
      INNER JOIN WSXML_SFG.POLITICAPAGO B ON A.CODPOLITICAPAGO = B.ID_POLITICAPAGO
      INNER JOIN WSXML_SFG.PERIODICIDADPAGO C ON B.CODPERIODICIDADPAGO = C.ID_PERIODICIDADPAGO
      WHERE A.CODPUNTODEVENTA =@p_CODPUNTODEVENTA AND A.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO;

      EXECUTE sp_executesql @FUNCION, N'@RESULTADO output, @p_FECHAVERIFICACION', @RESULTADO OUTPUT,
      @p_FECHAVERIFICACION;

      IF @RESULTADO = upper('true') BEGIN
          SET @p_VERIFICARAHORA_out = 1;
      END 
      IF @RESULTADO = upper('false') BEGIN
          SET @p_VERIFICARAHORA_out = 0;
      END 
 END;

GO


