USE SFGPRODU;
--  DDL for Package Body SFGRANGOCOMISIONCONTRATO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGRANGOCOMISIONCONTRATO */ 

  IF OBJECT_ID('WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetListTipoComision', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetListTipoComision;
GO
CREATE     PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetListTipoComision AS
  BEGIN
  SET NOCOUNT ON;
      SELECT ID_TIPOCOMISION, NOMTIPOCOMISION
        FROM WSXML_SFG.TIPOCOMISION
       WHERE ID_TIPOCOMISION IN (1, 2);
  END;
  GO

  IF OBJECT_ID('WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetListRangoComision', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetListRangoComision;
GO
CREATE     PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetListRangoComision  AS
  BEGIN
  SET NOCOUNT ON;
      SELECT ID_RANGOCOMISION, NOMRANGOCOMISION 
       FROM WSXML_SFG.RANGOCOMISION
       where RANGOCOMISION.CODTIPOCOMISION IN (1,2) and active = 1
       ORDER BY NOMRANGOCOMISION;
  END;
  GO

  IF OBJECT_ID('WSXML_SFG.SFGRANGOCOMISIONCONTRATO_SaveProductoContratoTarifa', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_SaveProductoContratoTarifa;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_SaveProductoContratoTarifa(@p_CODPRODUCTOCONTRATO          NUMERIC(22,0),
                                       @p_CODTARIFAVALOR               NUMERIC(22,0),
                                       @p_VALOR                        NUMERIC(22,0),
                                       @p_FECHAHORAMODIFICACION        DATETIME,
                                       @p_CODUSUARIOMODIFCACION        NUMERIC(22,0),
                                       @p_CODRANGOCOMISION             NUMERIC(22,0),
                                       @pk_ID_PRODUCTOCONTRATOTARI_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.PRODUCTOCONTRATOTARIFA
      (
       CODPRODUCTOCONTRATO,
       CODTARIFAVALOR,
       VALOR,
       FECHAHORAMODIFICACION,
       CODUSUARIOMODIFICACION,
       CODRANGOCOMISION)
    VALUES
      (
       @p_CODPRODUCTOCONTRATO,
       @p_CODTARIFAVALOR,
       @p_VALOR,
       @p_FECHAHORAMODIFICACION,
       @p_CODUSUARIOMODIFCACION,
       @p_CODRANGOCOMISION);
    SET @pk_ID_PRODUCTOCONTRATOTARI_out = SCOPE_IDENTITY();
  END;
  GO

  IF OBJECT_ID('WSXML_SFG.SFGRANGOCOMISIONCONTRATO_UpdateProductoContratoTarifa', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_UpdateProductoContratoTarifa;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_UpdateProductoContratoTarifa(@pk_ID_PRODUCTOCONTRATOTARI   NUMERIC(22,0),
                                       @p_FECHAHORAMODIFICACION        DATETIME,
                                       @p_CODUSUARIOMODIFCACION        NUMERIC(22,0),
                                       @p_CODRANGOCOMISION             NUMERIC(22,0)) 
                                       
  AS 
  BEGIN
  SET NOCOUNT ON;
   
  UPDATE   WSXML_SFG.PRODUCTOCONTRATOTARIFA
  SET CODRANGOCOMISION = @p_CODRANGOCOMISION,
      FECHAHORAMODIFICACION = @p_FECHAHORAMODIFICACION,
      CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFCACION
  WHERE PRODUCTOCONTRATOTARIFA.ID_PRODUCTOCONTRATOTARIFA = @pk_ID_PRODUCTOCONTRATOTARI;
  
  END;
  GO

  IF OBJECT_ID('WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetIdTarifaValor', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetIdTarifaValor;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetIdTarifaValor(@NombreTarifavalor  nvarchar(2000),
                             @id_tarifavalor_out NUMERIC(22,0) out)
  
   as
  begin
  set nocount on;
    select @id_tarifavalor_out = id_tarifavalor
      from WSXML_SFG.tarifavalor
     where nomtarifavalor = @NombreTarifavalor;
  end;

  GO


  IF OBJECT_ID('WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetRangoComisionByNomComision', 'P') is not null
  drop PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetRangoComisionByNomComision;
GO

  IF OBJECT_ID('WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetRangoComisionByNomComision', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetRangoComisionByNomComision;
GO
create     PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetRangoComisionByNomComision(@p_NOMRANGOCOMISION nvarchar(2000),
                                          @p_CODTIPOCOMISION NUMERIC(22,0),
                                          @P_CODRANGOCOMISION_OUT NUMERIC(22,0) out)
  
   as
  BEGIN
  SET NOCOUNT ON;
    
      SELECT @P_CODRANGOCOMISION_OUT = isnull(min(ID_RANGOCOMISION), 0)
        FROM WSXML_SFG.RANGOCOMISION
       WHERE NOMRANGOCOMISION = @p_NOMRANGOCOMISION 
       AND CODTIPOCOMISION = @p_CODTIPOCOMISION;
  END;
 GO
  
  IF OBJECT_ID('WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetIdProductoContratoTarifa', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetIdProductoContratoTarifa;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRANGOCOMISIONCONTRATO_GetIdProductoContratoTarifa(@p_CODTARIFAVALOR NUMERIC(22,0),
                                        @p_CODPRODUCTO NUMERIC(22,0),
                                        @P_IDPRODUCTOCONTRATOTAR_OUT NUMERIC(22,0) OUT)
  
  
  AS
  BEGIN
  SET NOCOUNT ON;
     SELECT @P_IDPRODUCTOCONTRATOTAR_OUT = isnull(PRODUCTOCONTRATOTARIFA.ID_PRODUCTOCONTRATOTARIFA, 0)
     FROM WSXML_SFG.PRODUCTOCONTRATOTARIFA
 INNER JOIN WSXML_SFG.PRODUCTOCONTRATO ON PRODUCTOCONTRATO.ID_PRODUCTOCONTRATO = PRODUCTOCONTRATOTARIFA.CODPRODUCTOCONTRATO
 WHERE PRODUCTOCONTRATOTARIFA.CODTARIFAVALOR = @p_CODTARIFAVALOR AND PRODUCTOCONTRATO.CODPRODUCTO = @p_CODPRODUCTO;  
  
   
END 
GO


