USE SFGPRODU;
--  DDL for Package Body SFGSERVICIO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGSERVICIO */ 

  IF OBJECT_ID('WSXML_SFG.SFGSERVICIO_GetServicios', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGSERVICIO_GetServicios;
GO
CREATE     PROCEDURE WSXML_SFG.SFGSERVICIO_GetServicios AS
  BEGIN
  SET NOCOUNT ON;
      	
      SELECT ID_SERVICIO, NOMSERVICIO, AGRUPAMIENTO FROM WSXML_SFG.SERVICIO;
		  
  END;

  IF OBJECT_ID('WSXML_SFG.SFGSERVICIO_GetLineasDeNegocio', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGSERVICIO_GetLineasDeNegocio;
GO

  IF OBJECT_ID('WSXML_SFG.SFGSERVICIO_GetLineasDeNegocio', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGSERVICIO_GetLineasDeNegocio;
GO
CREATE PROCEDURE WSXML_SFG.SFGSERVICIO_GetLineasDeNegocio(@p_CODSERVICIO NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
        
      SELECT ID_LINEADENEGOCIO, NOMLINEADENEGOCIO FROM WSXML_SFG.LINEADENEGOCIO WHERE CODSERVICIO = @p_CODSERVICIO;
		  
  END;
GO 
  IF OBJECT_ID('WSXML_SFG.SFGSERVICIO_GetProductos', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGSERVICIO_GetProductos;
GO
CREATE     PROCEDURE WSXML_SFG.SFGSERVICIO_GetProductos(@p_CODLINEADENEGOCIO NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
        
      SELECT ID_PRODUCTO, NOMPRODUCTO, CODTIPOPRODUCTO FROM WSXML_SFG.PRODUCTO
      INNER JOIN WSXML_SFG.TIPOPRODUCTO ON (CODTIPOPRODUCTO = ID_TIPOPRODUCTO)
      WHERE CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
      ORDER BY NOMPRODUCTO;
		  
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGSERVICIO_GetPuntosAjustes', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGSERVICIO_GetPuntosAjustes;
GO
CREATE     PROCEDURE WSXML_SFG.SFGSERVICIO_GetPuntosAjustes AS
  BEGIN
  SET NOCOUNT ON;
        
      SELECT ID_PUNTODEVENTA, ISNULL(CODIGOGTECHPUNTODEVENTA, '') + ' (' + ISNULL(NUMEROTERMINAL, '') + ')'
      FROM WSXML_SFG.PUNTODEVENTA WHERE ACTIVE = 1
      ORDER BY CAST(CODIGOGTECHPUNTODEVENTA AS INT);
		  

END 

