USE SFGPRODU;
--  DDL for Package Body SFGSERVICIOSAPCUENTA
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGSERVICIOSAPCUENTA */ 

  IF OBJECT_ID('WSXML_SFG.SFGSERVICIOSAPCUENTA_GetServicioCuenta', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGSERVICIOSAPCUENTA_GetServicioCuenta;
GO
CREATE     PROCEDURE WSXML_SFG.SFGSERVICIOSAPCUENTA_GetServicioCuenta AS
  BEGIN
  SET NOCOUNT ON;
    SELECT NULL;
  END;

