USE SFGPRODU;
--  DDL for Package Body SFGTEMPORALUNOSOLOUSO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGTEMPORALUNOSOLOUSO */ 

IF OBJECT_ID('WSXML_SFG.SFGTEMPORALUNOSOLOUSO_NoConformidadSGSI568', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTEMPORALUNOSOLOUSO_NoConformidadSGSI568;
GO

CREATE PROCEDURE WSXML_SFG.SFGTEMPORALUNOSOLOUSO_NoConformidadSGSI568 AS
 BEGIN
  DECLARE @tmpid NUMERIC(22,0);
   
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.REGISTROFACTREFERENCIA (
			--[ID_REGISTROFACTREFERENCIA],
			[CODREGISTROFACTURACION],
			[NUMEROREFERENCIA],
			[FECHAHORATRANSACCION],
			[VALORTRANSACCION],
			[ESTADO],
			[ANULADO],
			[FECHAHORAANULACION],
			[CODREGISTROANULADO],
			[SUBAGENTE],
			[RECIBO],
			[SUSCRIPTOR],
			[CODTRANSACCIONALIADO],
			[BINTARJETA],
			[TIPOTRANSACCION],
			[FEECROSSREF] ,
			[RESPUESTABANCO] ,
			[ARRN],
			[FECHATRANSBANCO],
			[CAMPO_FUTURO1],
			[ARRN_GIRO_DEPOSITO],
			[TRANS_CODE],
			[VRCOMISION],
			[IVACOMISION]
	)
    SELECT CODREGISTROFACTURACION, NUMEROREFERENCIA, FECHAHORATRANSACCION, VALORTRANSACCION, ESTADO, ANULADO, FECHAHORAANULACION, CODREGISTROANULADO,	SUBAGENTE,	RECIBO,	SUSCRIPTOR,	CODTRANSACCIONALIADO,	BINTARJETA,	TIPOTRANSACCION,	FEECROSSREF, RESPUESTABANCO, ARRN, FECHATRANSBANCO, CAMPO_FUTURO1, ARRN_GIRO_DEPOSITO, TRANS_CODE, VRCOMISION, IVACOMISION
	FROM WSXML_SFG.TMPREGISTROFACTREFERENCIA ;

	
	SET  @tmpid = SCOPE_IDENTITY() ;
   --execute sp_executesql   @'alter sequence REGFACTURACIONREFERENCIA_SEQ increment by 1125 nocache';
   --select @tmpid = REGFACTURACIONREFERENCIA_SEQ.nextval;
   --execute sp_executesql   @'alter sequence REGFACTURACIONREFERENCIA_SEQ increment by 1 cache 20';
END;
GO
