USE SFGPRODU;
--  DDL for Package Body SFGTRIBUTARIOALIADOESTRATEGICO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGTRIBUTARIOALIADOESTRATEGICO */ 

  IF OBJECT_ID('WSXML_SFG.SFGTRIBUTARIOALIADOESTRATEGICO_SetTributarioAliado', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTRIBUTARIOALIADOESTRATEGICO_SetTributarioAliado;
GO

CREATE     PROCEDURE WSXML_SFG.SFGTRIBUTARIOALIADOESTRATEGICO_SetTributarioAliado(@p_CODALIADOESTRATEGICO         NUMERIC(22,0),
                                @p_VALORVAT                     FLOAT,
                                @p_CODUSUARIOMODIFICACION       NUMERIC(22,0),
                                @p_ID_TRIBUTARIOALIADOESTRA_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    SELECT @p_ID_TRIBUTARIOALIADOESTRA_out = ID_TRIBUTARIOALIADOESTRATEGICO
    FROM WSXML_SFG.TRIBUTARIOALIADOESTRATEGICO
    WHERE CODALIADOESTRATEGICO = @p_CODALIADOESTRATEGICO;
    UPDATE WSXML_SFG.TRIBUTARIOALIADOESTRATEGICO SET VALORVAT               = @p_VALORVAT,
                                           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
                                           FECHAHORAMODIFICACION  = GETDATE()
    WHERE ID_TRIBUTARIOALIADOESTRATEGICO = @p_ID_TRIBUTARIOALIADOESTRA_out;
 
	IF @@ROWCOUNT = 0 BEGIN
    INSERT INTO WSXML_SFG.TRIBUTARIOALIADOESTRATEGICO (
                                             CODALIADOESTRATEGICO,
                                             VALORVAT,
                                             CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODALIADOESTRATEGICO,
            @p_VALORVAT,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_TRIBUTARIOALIADOESTRA_out = SCOPE_IDENTITY();
	END

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGTRIBUTARIOALIADOESTRATEGICO_GetVatValue', 'FN') IS NOT NULL
  DROP FUNCTION WSXML_SFG.SFGTRIBUTARIOALIADOESTRATEGICO_GetVatValue;
GO

CREATE     FUNCTION WSXML_SFG.SFGTRIBUTARIOALIADOESTRATEGICO_GetVatValue(@p_CODPRODUCTO NUMERIC(22,0), @p_CODREGIMEN NUMERIC(22,0), @p_CODCIUDAD NUMERIC(22,0)) RETURNS FLOAT AS
 BEGIN
    DECLARE @cEXCPCION NUMERIC(22,0);
    DECLARE @cVALORVAT FLOAT = 0;
   
    SELECT @cEXCPCION = COUNT(1) FROM WSXML_SFG.TRIBUTARIOALIADOEXCEPCION WHERE CODREGIMEN = @p_CODREGIMEN;
    IF @cEXCPCION = 0 BEGIN
      SELECT @cVALORVAT = CASE WHEN TCE.ID_TRIBUTARIOCIUDADEXCEPCION > 0 THEN 0 ELSE TAE.VALORVAT END 
	  FROM WSXML_SFG.PRODUCTO PRD
      INNER JOIN WSXML_SFG.TRIBUTARIOALIADOESTRATEGICO    TAE ON (TAE.CODALIADOESTRATEGICO = PRD.CODALIADOESTRATEGICO)
      LEFT OUTER JOIN WSXML_SFG.TRIBUTARIOCIUDADEXCEPCION TCE ON (TCE.CODCIUDAD            = @p_CODCIUDAD)
      WHERE ID_PRODUCTO = @p_CODPRODUCTO;
    END
    ELSE BEGIN
      SET @cVALORVAT = 0;
    END 
   
	IF @@ROWCOUNT = 0
    RETURN 0;

	 RETURN @cVALORVAT;
  END;
  GO


  IF OBJECT_ID('WSXML_SFG.SFGTRIBUTARIOALIADOESTRATEGICO_SetRetencionAliado', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTRIBUTARIOALIADOESTRATEGICO_SetRetencionAliado;
GO

CREATE     PROCEDURE WSXML_SFG.SFGTRIBUTARIOALIADOESTRATEGICO_SetRetencionAliado(@p_CODALIADOESTRATEGICO         NUMERIC(22,0),
                               @p_CODRETENCIONTRIBUTARIA       NUMERIC(22,0),
                               @p_VALOR                        FLOAT,
                               @p_CODUSUARIOMODIFICACION       NUMERIC(22,0),
                               @p_ID_RETENCIONALIADOESTRAT_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    SELECT @p_ID_RETENCIONALIADOESTRAT_out = ID_RETENCIONALIADOESTRATEGICO
    FROM WSXML_SFG.RETENCIONALIADOESTRATEGICO
    WHERE CODALIADOESTRATEGICO   = @p_CODALIADOESTRATEGICO
      AND CODRETENCIONTRIBUTARIA = @p_CODRETENCIONTRIBUTARIA;
    UPDATE WSXML_SFG.RETENCIONALIADOESTRATEGICO SET VALOR                  = @p_VALOR,
                                          CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
                                          FECHAHORAMODIFICACION  = GETDATE()
    WHERE ID_RETENCIONALIADOESTRATEGICO = @p_ID_RETENCIONALIADOESTRAT_out;
  
	IF @@ROWCOUNT = 0
    INSERT INTO WSXML_SFG.RETENCIONALIADOESTRATEGICO (
                                            CODALIADOESTRATEGICO,
                                            CODRETENCIONTRIBUTARIA,
                                            VALOR,
                                            CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODALIADOESTRATEGICO,
            @p_CODRETENCIONTRIBUTARIA,
            @p_VALOR,
            @p_CODUSUARIOMODIFICACION);
  END;

GO

