USE SFGPRODU;
--  DDL for Package Body SFGTIPODISTRIBUCION
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGTIPODISTRIBUCION */ 


  IF OBJECT_ID('WSXML_SFG.SFGTIPODISTRIBUCION_CONSTANT', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPODISTRIBUCION_CONSTANT;
GO

CREATE  PROCEDURE WSXML_SFG.SFGTIPODISTRIBUCION_CONSTANT(
  @ASIGNADOGRNT 		TINYINT OUTPUT,
  @SUGERIDOXSFG         TINYINT OUTPUT,
  @SUGERIDOXPDV 		TINYINT OUTPUT
) AS
  BEGIN
  SET NOCOUNT ON;
	
  set @ASIGNADOGRNT = 1;
  set @SUGERIDOXSFG = 2;
  set @SUGERIDOXPDV = 3;
 END;
GO


--END SFGTIPODISTRIBUCION;


