USE SFGPRODU;
--  DDL for Package Body SFGUSIARCHIVOS
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGUSIARCHIVOS */ 

-- Creates a new record in the TIPORANGO table

IF OBJECT_ID('WSXML_SFG.SFGUSIARCHIVOS_GetIdUsiTipoArchivoByName', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGUSIARCHIVOS_GetIdUsiTipoArchivoByName;
GO

CREATE PROCEDURE WSXML_SFG.SFGUSIARCHIVOS_GetIdUsiTipoArchivoByName(
                              @p_NOMBREARCHIVO NVARCHAR(2000),
                              @p_ID_USITIPOARCHIVO_out NUMERIC(22,0) OUT)
AS
BEGIN
SET NOCOUNT ON;
   SELECT @p_ID_USITIPOARCHIVO_out = USITIPOARCHIVO.ID_USITIPOARCHIVO
   FROM WSXML_SFG.USITIPOARCHIVO
   WHERE USITIPOARCHIVO.NOMBREARCHIVO = @p_NOMBREARCHIVO;
END;
GO

IF OBJECT_ID('WSXML_SFG.SFGUSIARCHIVOS_GetIdUsiArchivo', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGUSIARCHIVOS_GetIdUsiArchivo;
GO

CREATE PROCEDURE WSXML_SFG.SFGUSIARCHIVOS_GetIdUsiArchivo(
                         @p_IDUSIARCHIVODETALLE NUMERIC(22,0),
                         @pk_ID_USIARCHIVO NUMERIC(22,0) OUT)

AS 
BEGIN
SET NOCOUNT ON;
  SELECT @pk_ID_USIARCHIVO = USIARCHIVODETALLE.CODUSIARCHIVO
  FROM WSXML_SFG.USIARCHIVODETALLE
  WHERE USIARCHIVODETALLE.ID_USIARCHIVODETALLE = @p_IDUSIARCHIVODETALLE;
 END;

