USE SFGPRODU;
--  DDL for Function TIPOOPERACIONVENTA_F
--------------------------------------------------------

  IF OBJECT_ID('WSXML_SFG.TIPOOPERACIONVENTA_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.TIPOOPERACIONVENTA_F;
GO

  CREATE FUNCTION WSXML_SFG.TIPOOPERACIONVENTA_F (@p_NOMTIPOOPERACIONVENTA NVARCHAR(2000)) RETURNS NUMERIC(22,0) AS
 BEGIN
  DECLARE @result NUMERIC(22,0) = 0;
 
    SELECT @result = ID_TIPOOPERACIONVENTA FROM WSXML_SFG.TIPOOPERACIONVENTA WHERE NOMTIPOOPERACIONVENTA = @p_NOMTIPOOPERACIONVENTA;
	
	IF @@ROWCOUNT = 0  BEGIN
		--INSERT INTO WSXML_SFG.TIPOOPERACIONVENTA ( NOMTIPOOPERACIONVENTA) VALUES ( @p_NOMTIPOOPERACIONVENTA)
		SET @result = 0;--SCOPE_IDENTITY();
	END
  RETURN @result;
END; 

