USE SFGPRODU;
--  DDL for Function TIPOTARJETA_F
--------------------------------------------------------

  IF OBJECT_ID('WSXML_SFG.TIPOTARJETA_F', 'FN') IS NOT NULL
    DROP FUNCTION WSXML_SFG.TIPOTARJETA_F;
GO

  CREATE FUNCTION WSXML_SFG.TIPOTARJETA_F (@p_NOMTIPOTARJETA VARCHAR(4000) /* Use -meta option TIPOTARJETA.NOMTIPOTARJETA%TYPE */) 
  RETURNS NUMERIC(22,0) AS
 BEGIN
  DECLARE @returnvalue NUMERIC(22,0);
 
  SELECT @returnvalue = ID_TIPOTARJETA FROM WSXML_SFG.TIPOTARJETA WHERE RTRIM(LTRIM(UPPER(NOMTIPOTARJETA))) = RTRIM(LTRIM(UPPER(@p_NOMTIPOTARJETA)));
  
  IF @@ROWCOUNT = 0 BEGIN
	RETURN CAST('-20054: No existe el tipo de tarjeta' AS INT);
  END
  RETURN @returnvalue;
  
END;

