USE SFGPRODU;
--  DDL for Package Body SFGAGRUPACIONPRODUCTO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGAGRUPACIONPRODUCTO */ 

  IF OBJECT_ID('WSXML_SFG.SFGAGRUPACIONPRODUCTO_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGAGRUPACIONPRODUCTO_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGAGRUPACIONPRODUCTO_AddRecord(@p_NOMAGRUPACIONPRODUCTO     NVARCHAR(2000),
                      @p_CODTIPOPRODUCTO           NUMERIC(22,0),
                      @p_CODUSUARIOMODIFICACION    NUMERIC(22,0),
                      @p_ID_AGRUPACIONPRODUCTO_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.AGRUPACIONPRODUCTO (
                                    NOMAGRUPACIONPRODUCTO,
                                    CODTIPOPRODUCTO,
                                    CODUSUARIOMODIFICACION)
    VALUES (
            @p_NOMAGRUPACIONPRODUCTO,
            @p_CODTIPOPRODUCTO,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_AGRUPACIONPRODUCTO_out = SCOPE_IDENTITY();
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGAGRUPACIONPRODUCTO_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGAGRUPACIONPRODUCTO_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGAGRUPACIONPRODUCTO_UpdateRecord(@pk_ID_AGRUPACIONPRODUCTO NUMERIC(22,0),
                         @p_NOMAGRUPACIONPRODUCTO  NVARCHAR(2000),
                         @p_CODTIPOPRODUCTO        NUMERIC(22,0),
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.AGRUPACIONPRODUCTO
       SET NOMAGRUPACIONPRODUCTO  = @p_NOMAGRUPACIONPRODUCTO,
           CODTIPOPRODUCTO        = @p_CODTIPOPRODUCTO,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION
     WHERE ID_AGRUPACIONPRODUCTO = @pk_ID_AGRUPACIONPRODUCTO;
	 
	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGAGRUPACIONPRODUCTO_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGAGRUPACIONPRODUCTO_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGAGRUPACIONPRODUCTO_GetRecord(@pk_ID_AGRUPACIONPRODUCTO NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.AGRUPACIONPRODUCTO WHERE ID_AGRUPACIONPRODUCTO = @pk_ID_AGRUPACIONPRODUCTO;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
   
      SELECT ID_AGRUPACIONPRODUCTO,
             NOMAGRUPACIONPRODUCTO,
             CODTIPOPRODUCTO,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION
      FROM WSXML_SFG.AGRUPACIONPRODUCTO
      WHERE ID_AGRUPACIONPRODUCTO = @pk_ID_AGRUPACIONPRODUCTO;
  
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGAGRUPACIONPRODUCTO_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGAGRUPACIONPRODUCTO_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGAGRUPACIONPRODUCTO_GetList AS
  BEGIN
  SET NOCOUNT ON;
   
      SELECT ID_AGRUPACIONPRODUCTO,
             NOMAGRUPACIONPRODUCTO,
             CODTIPOPRODUCTO,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION
      FROM WSXML_SFG.AGRUPACIONPRODUCTO;
	  
  END;
GO






