USE SFGPRODU;
--  DDL for Package Body SFGAGENTETAREAEJECUCION
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGAGENTETAREAEJECUCION */ 

  IF OBJECT_ID('WSXML_SFG.SFGAGENTETAREAEJECUCION_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGAGENTETAREAEJECUCION_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGAGENTETAREAEJECUCION_AddRecord(@p_FECHAHORAEJECUCION          DATETIME,
                      @p_AGENTE_EJECUTOR             VARCHAR(4000),
                      @p_ID_AGENTETAREAEJECUCION_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.AGENTETAREAEJECUCION
      ( FECHAHORAEJECUCION, AGENTE_EJECUTOR)
    VALUES
      (
       @p_FECHAHORAEJECUCION,
       @p_AGENTE_EJECUTOR);
    SET @p_ID_AGENTETAREAEJECUCION_out = SCOPE_IDENTITY();
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGAGENTETAREAEJECUCION_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGAGENTETAREAEJECUCION_GetRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGAGENTETAREAEJECUCION_GetRecord(@pk_ID_AGENTETAREAEJECUCION NUMERIC(22,0)
                      ) AS
  BEGIN
  SET NOCOUNT ON;
     
	SELECT ID_AGENTETAREAEJECUCION, FECHAHORAEJECUCION, AGENTE_EJECUTOR
        FROM WSXML_SFG.AGENTETAREAEJECUCION
       WHERE ID_AGENTETAREAEJECUCION = @pk_ID_AGENTETAREAEJECUCION; 
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGAGENTETAREAEJECUCION_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGAGENTETAREAEJECUCION_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGAGENTETAREAEJECUCION_GetList AS
  BEGIN
  SET NOCOUNT ON;
       SELECT ID_AGENTETAREAEJECUCION, FECHAHORAEJECUCION, AGENTE_EJECUTOR
        FROM WSXML_SFG.AGENTETAREAEJECUCION
       ORDER BY FECHAHORAEJECUCION DESC; 
	  
  END;
GO






