USE SFGPRODU;
--  DDL for Package Body SFGALERTAAVANCE
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGALERTAAVANCE */ 

  IF OBJECT_ID('WSXML_SFG.SFGALERTAAVANCE_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGALERTAAVANCE_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGALERTAAVANCE_AddRecord(@p_CODALERTA              NUMERIC(22,0),
                      @p_CONTENIDOAVANCE        NVARCHAR(2000),
                      @p_CODUSUARIODESTINO      NUMERIC(22,0),
                      @p_CODESTADOALERTA        NUMERIC(22,0),
                      @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                      @p_ID_ALERTAAVANCE_out    NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.ALERTAAVANCE (
                              CODALERTA,
                              CONTENIDOAVANCE,
                              CODUSUARIODESTINO,
                              CODESTADOALERTA,
                              CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODALERTA,
            @p_CONTENIDOAVANCE,
            @p_CODUSUARIODESTINO,
            @p_CODESTADOALERTA,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_ALERTAAVANCE_out = SCOPE_IDENTITY();
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGALERTAAVANCE_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGALERTAAVANCE_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGALERTAAVANCE_UpdateRecord(@pk_ID_ALERTAAVANCE       NUMERIC(22,0),
                         @p_CODALERTA              NUMERIC(22,0),
                         @p_CONTENIDOAVANCE        NVARCHAR(2000),
                         @p_CODUSUARIODESTINO      NUMERIC(22,0),
                         @p_CODESTADOALERTA        NUMERIC(22,0),
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.ALERTAAVANCE
       SET CODALERTA              = @p_CODALERTA,
           CONTENIDOAVANCE        = @p_CONTENIDOAVANCE,
           CODUSUARIODESTINO      = @p_CODUSUARIODESTINO,
           CODESTADOALERTA        = @p_CODESTADOALERTA,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           ACTIVE                 = @p_ACTIVE
     WHERE ID_ALERTAAVANCE = @pk_ID_ALERTAAVANCE;

    IF @@rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @@rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGALERTAAVANCE_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGALERTAAVANCE_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGALERTAAVANCE_GetRecord(@pk_ID_ALERTAAVANCE NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.ALERTAAVANCE WHERE ID_ALERTAAVANCE = @pk_ID_ALERTAAVANCE;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
		 
		SELECT AA.ID_ALERTAAVANCE,
             AA.CODALERTA,
             AA.CONTENIDOAVANCE,
             AA.CODUSUARIODESTINO,
             U.NOMUSUARIO,
             AA.CODESTADOALERTA,
             E.NOMESTADOALERTA,
             AA.FECHAHORAMODIFICACION,
             AA.CODUSUARIOMODIFICACION,
             AA.ACTIVE
		FROM WSXML_SFG.ALERTAAVANCE AA
		LEFT OUTER JOIN WSXML_SFG.USUARIO U
			ON (U.ID_USUARIO = AA.CODUSUARIODESTINO)
		LEFT OUTER JOIN WSXML_SFG.ESTADOALERTA E
			ON (E.ID_ESTADOALERTA = AA.CODESTADOALERTA)
		WHERE AA.ID_ALERTAAVANCE = @pk_ID_ALERTAAVANCE;
		
  END;
GO


IF OBJECT_ID('WSXML_SFG.SFGALERTAAVANCE_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGALERTAAVANCE_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGALERTAAVANCE_GetList(@p_active NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
		 
		SELECT AA.ID_ALERTAAVANCE,
             AA.CODALERTA,
             AA.CONTENIDOAVANCE,
             AA.CODUSUARIODESTINO,
             U.NOMUSUARIO,
             AA.CODESTADOALERTA,
             E.NOMESTADOALERTA,
             AA.FECHAHORAMODIFICACION,
             AA.CODUSUARIOMODIFICACION,
             AA.ACTIVE
		FROM WSXML_SFG.ALERTAAVANCE AA
		LEFT OUTER JOIN WSXML_SFG.USUARIO U
			ON (U.ID_USUARIO = AA.CODUSUARIODESTINO)
		LEFT OUTER JOIN WSXML_SFG.ESTADOALERTA E
			ON (E.ID_ESTADOALERTA = AA.CODESTADOALERTA)
		WHERE AA.ACTIVE = CASE WHEN @p_active = -1 THEN AA.ACTIVE ELSE @p_active END;
		
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGALERTAAVANCE_GetListByHeader', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGALERTAAVANCE_GetListByHeader;
GO
CREATE     PROCEDURE WSXML_SFG.SFGALERTAAVANCE_GetListByHeader(@p_active NUMERIC(22,0), @p_CODALERTA NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
	 
      SELECT AA.ID_ALERTAAVANCE,
             AA.CODALERTA,
             AA.CONTENIDOAVANCE,
             AA.CODUSUARIODESTINO,
             U.NOMUSUARIO NOMUSUARIODESTINO,
             AA.CODESTADOALERTA,
             E.NOMESTADOALERTA,
             AA.FECHAHORAMODIFICACION,
             AA.CODUSUARIOMODIFICACION,
             AA.ACTIVE
      FROM WSXML_SFG.ALERTAAVANCE AA
      LEFT OUTER JOIN WSXML_SFG.USUARIO U
        ON (U.ID_USUARIO = AA.CODUSUARIODESTINO)
      LEFT OUTER JOIN WSXML_SFG.ESTADOALERTA E
        ON (E.ID_ESTADOALERTA = AA.CODESTADOALERTA)
      WHERE AA.CODALERTA = @p_CODALERTA
        AND AA.ACTIVE = CASE WHEN @p_active = -1 THEN AA.ACTIVE ELSE @p_active END
      ORDER BY AA.FECHAHORAMODIFICACION DESC;
	  
  END;
GO

-- Dependencia del siguiente procedimiento




  IF OBJECT_ID('WSXML_SFG.SFGALERTAAVANCE_GestionarAlerta', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGALERTAAVANCE_GestionarAlerta;
GO

CREATE     PROCEDURE WSXML_SFG.SFGALERTAAVANCE_GestionarAlerta(@p_CODALERTA              NUMERIC(22,0),
                            @p_CONTENIDOAVANCE        NVARCHAR(2000),
                            @p_CODUSUARIODESTINO      NUMERIC(22,0),
                            @p_CODESTADOALERTA        NUMERIC(22,0),
                            @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                            @p_ID_ALERTAAVANCE_out    NUMERIC(22,0) OUT) AS
 BEGIN
    DECLARE @cALERTAUSUARIODESTINO NUMERIC(22,0);
    DECLARE @cALERTAESTADO NUMERIC(22,0);
   
  SET NOCOUNT ON;
  
    --AddRecord(@p_CODALERTA, @p_CONTENIDOAVANCE, @p_CODUSUARIODESTINO, @p_CODESTADOALERTA, @p_CODUSUARIOMODIFICACION, @p_ID_ALERTAAVANCE_out);
	EXEC WSXML_SFG.SFGALERTAAVANCE_AddRecord 
		@p_CODALERTA, @p_CONTENIDOAVANCE, @p_CODUSUARIODESTINO, @p_CODESTADOALERTA, @p_CODUSUARIOMODIFICACION, @p_ID_ALERTAAVANCE_out
    
	-- Solo cambia en caso del cambio de estado o cambio de persona
    SELECT @cALERTAESTADO = CODESTADOALERTA, @cALERTAUSUARIODESTINO = CODUSUARIODESTINO
    FROM WSXML_SFG.ALERTA WHERE ID_ALERTA = @p_CODALERTA;
    IF @cALERTAESTADO <> @p_CODESTADOALERTA OR @cALERTAUSUARIODESTINO <> @p_CODUSUARIODESTINO BEGIN
      -- Actualizar
      UPDATE WSXML_SFG.ALERTA SET CODUSUARIODESTINO      = @p_CODUSUARIODESTINO,
                        CODESTADOALERTA        = @p_CODESTADOALERTA,
                        CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
                        FECHAHORAMODIFICACION  = GETDATE()
      WHERE ID_ALERTA = @p_CODALERTA;

      -- Si se ha cambiado de usuario, notificar al nuevo usuario
      IF @cALERTAUSUARIODESTINO <> @p_CODUSUARIODESTINO BEGIN
          DECLARE @cEMAIL NVARCHAR(1000);
          DECLARE @cNOMTIPOALERTA NVARCHAR(50);
          DECLARE @cCONTENIDO NVARCHAR(1000);
          DECLARE @sub NVARCHAR(1000);
          DECLARE @msg NVARCHAR(1000);
          DECLARE @cNOMBREORIGEN NVARCHAR(1000);
          DECLARE @SUCCESS NUMERIC(38,0);
        BEGIN
			DECLARE @p_ID_ENVIOCORREO_out INT
          
			SELECT @cEMAIL = EMAIL FROM WSXML_SFG.USUARIO WHERE ID_USUARIO = @p_CODUSUARIODESTINO;
          
			SELECT @cNOMTIPOALERTA = NOMTIPOALERTA, @cCONTENIDO = CONTENIDO 
			FROM WSXML_SFG.ALERTA
				LEFT OUTER JOIN WSXML_SFG.TIPOALERTA ON CODTIPOALERTA = ID_TIPOALERTA
			WHERE ID_ALERTA = @p_CODALERTA;
          
			SELECT @cNOMBREORIGEN = NOMBRE FROM WSXML_SFG.USUARIO WHERE ID_USUARIO = @cALERTAUSUARIODESTINO;
			SET @sub = 'Notificacion de asignacion de alerta tipo ' + ISNULL(@cNOMTIPOALERTA, '');
			SET @msg = 'El usuario ' + ISNULL(@cNOMBREORIGEN, '') + ' le ha asignado una alerta de tipo ' + ISNULL(@cNOMTIPOALERTA, '') + ': ' + ISNULL(CHAR(13), '') + ISNULL(CHAR(13), '') + ISNULL(@cCONTENIDO, '');
			--SUCCESS := SFG_PACKAGE.ENVIARCORREO(cEMAIL, sub, msg);
			EXEC WSXML_SFG.SFGENVIOCORREO_AddCorreo
				NULL, @cEMAIL, @sub, @msg, NULL, @p_CODUSUARIOMODIFICACION, @p_ID_ENVIOCORREO_out OUTPUT
			--EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
        END;
      END 
    END 
  END;
GO






