USE SFGPRODU;
--  DDL for Package Body SFGACUMULADOBALOTO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGACUMULADOBALOTO */ 
  
IF OBJECT_ID('WSXML_SFG.SFGACUMULADOBALOTO_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGACUMULADOBALOTO_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGACUMULADOBALOTO_UpdateRecord(@pk_ID_ACUMULADOBALOTO    NUMERIC(22,0),
                         @p_JUEGOPRODUCTO          NUMERIC(22,0),
                         @p_ACUMULADOSINGANADOR    NUMERIC(22,0),
                         @p_ACUMULADOCONGANADOR    NUMERIC(22,0),
                         @p_FECHASORTEO            DATETIME) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.ACUMULADOBALOTO
       SET JUEGOPRODUCTO = @p_JUEGOPRODUCTO,
           ACUMULADOSINGANADOR = @p_ACUMULADOSINGANADOR,
           ACUMULADOCONGANADOR = @p_ACUMULADOCONGANADOR,
           FECHASORTEO = CONVERT(DATETIME, CONVERT(DATE,@p_FECHASORTEO))
     WHERE ID_ACUMULADOBALOTO = @pk_ID_ACUMULADOBALOTO;
	
	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO
  
IF OBJECT_ID('WSXML_SFG.SFGACUMULADOBALOTO_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGACUMULADOBALOTO_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGACUMULADOBALOTO_AddRecord(@p_JUEGOPRODUCTO          NUMERIC(22,0),
                      @p_ACUMULADOSINGANADOR    NUMERIC(22,0),
                      @p_ACUMULADOCONGANADOR    NUMERIC(22,0),
                      @p_FECHASORTEO            DATETIME,
                      @p_ID_ACUMULADOBALOTO_out NUMERIC(22,0) OUT) AS
 BEGIN

  DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.ACUMULADOBALOTO WHERE CONVERT(DATE,FECHASORTEO) = CONVERT(DATE,@p_FECHASORTEO) and JUEGOPRODUCTO=@p_JUEGOPRODUCTO;
    IF @l_count = 0 BEGIN
		/*SELECT @p_ID_ACUMULADOBALOTO_out = ACUMULADOBALOTO_seq.nextval;
        INSERT INTO WSXML_SFG.ACUMULADOBALOTO(ID_ACUMULADOBALOTO,
                                    JUEGOPRODUCTO,
                                    ACUMULADOSINGANADOR,
                                    ACUMULADOCONGANADOR,
                                    FECHASORTEO,
                                    FECHAREGISTRO)
        VALUES (@p_ID_ACUMULADOBALOTO_out,
                @p_JUEGOPRODUCTO,
                @p_ACUMULADOSINGANADOR,
                @p_ACUMULADOCONGANADOR,
                CONVERT(DATETIME, CONVERT(DATE,@p_FECHASORTEO)),
                CONVERT(DATETIME, CONVERT(DATE,GETDATE())));
		*/
		INSERT INTO WSXML_SFG.ACUMULADOBALOTO(
                                    JUEGOPRODUCTO,
                                    ACUMULADOSINGANADOR,
                                    ACUMULADOCONGANADOR,
                                    FECHASORTEO,
                                    FECHAREGISTRO)
        VALUES (
                @p_JUEGOPRODUCTO,
                @p_ACUMULADOSINGANADOR,
                @p_ACUMULADOCONGANADOR,
                CONVERT(DATETIME, CONVERT(DATE,@p_FECHASORTEO)),
                CONVERT(DATETIME, CONVERT(DATE,GETDATE())));
				
		SET @p_ID_ACUMULADOBALOTO_out = SCOPE_IDENTITY() ;
    END 
     IF @l_count >= 1 BEGIN
        SELECT @p_ID_ACUMULADOBALOTO_out = ID_ACUMULADOBALOTO FROM WSXML_SFG.ACUMULADOBALOTO WHERE CONVERT(DATE,FECHASORTEO) = CONVERT(DATE,@p_FECHASORTEO) and JUEGOPRODUCTO=@p_JUEGOPRODUCTO;
		EXEC WSXML_SFG.SFGACUMULADOBALOTO_UpdateRecord @p_ID_ACUMULADOBALOTO_out,@p_JUEGOPRODUCTO,@p_ACUMULADOSINGANADOR,@p_ACUMULADOCONGANADOR,@p_FECHASORTEO
        --SFGACUMULADOBALOTO.UpdateRecord(@p_ID_ACUMULADOBALOTO_out,@p_JUEGOPRODUCTO,@p_ACUMULADOSINGANADOR,@p_ACUMULADOCONGANADOR,@p_FECHASORTEO);
     END 


  END;
GO



IF OBJECT_ID('WSXML_SFG.SFGACUMULADOBALOTO_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGACUMULADOBALOTO_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGACUMULADOBALOTO_GetRecord(@pk_ID_ACUMULADOBALOTO NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.ACUMULADOBALOTO WHERE ID_ACUMULADOBALOTO = @pk_ID_ACUMULADOBALOTO;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

      SELECT ID_ACUMULADOBALOTO,
             JUEGOPRODUCTO,
             ACUMULADOSINGANADOR,
             ACUMULADOCONGANADOR,
             FECHASORTEO
      FROM WSXML_SFG.ACUMULADOBALOTO
      WHERE ID_ACUMULADOBALOTO = @pk_ID_ACUMULADOBALOTO;
	  
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGACUMULADOBALOTO_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGACUMULADOBALOTO_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGACUMULADOBALOTO_GetList AS
  BEGIN
  SET NOCOUNT ON;
     SELECT ID_ACUMULADOBALOTO,
             JUEGOPRODUCTO,
             ACUMULADOSINGANADOR,
             ACUMULADOSINGANADOR,
             ACUMULADOCONGANADOR
      FROM WSXML_SFG.ACUMULADOBALOTO;
	  
  END;
GO






