USE SFGPRODU;
--  DDL for Package Body SFGCATEGORIA_ACIERTOS_L1LIAB01
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGCATEGORIA_ACIERTOS_L1LIAB01 */ 

  --Add Record in the table CATEGORIA_ACIERTOS_L1LIAB01
  IF OBJECT_ID('WSXML_SFG.SFGCATEGORIA_ACIERTOS_L1LIAB01_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCATEGORIA_ACIERTOS_L1LIAB01_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCATEGORIA_ACIERTOS_L1LIAB01_AddRecord(@p_NOMBRECATEGORIA        VARCHAR(4000),
					  @p_NOMBRECORTOCATEGORIA   VARCHAR(4000),
					  @p_CIFRAS_ACERTADAS       NUMERIC(22,0),
					  @p_CIFRAS_APOSTADAS       NUMERIC(22,0),
					  @p_FECHAHORAMODIFICACION  DATETIME,
					  @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
					  @p_ACTIVE                 NUMERIC(22,0),
					  @p_ID_CATEGO_ACIER_L1LIAB01_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.CATEGORIA_ACIERTOS_L1LIAB01 (
											 NOMBRECATEGORIA,
											 NOMBRECORTOCATEGORIA,
											 CIFRAS_ACERTADAS,
											 CIFRAS_APOSTADAS,
											 FECHAHORAMODIFICACION,
											 CODUSUARIOMODIFICACION,
											 ACTIVE)
    VALUES (
			@p_NOMBRECATEGORIA,
			@p_NOMBRECORTOCATEGORIA,
			@p_CIFRAS_ACERTADAS,
			@p_CIFRAS_APOSTADAS,
			@p_FECHAHORAMODIFICACION,
			@p_CODUSUARIOMODIFICACION,
			@p_ACTIVE);
    SET @p_ID_CATEGO_ACIER_L1LIAB01_out = SCOPE_IDENTITY();
  END;
GO

  --Find Record on the table CATEGORIA_ACIERTOS_L1LIAB01
  IF OBJECT_ID('WSXML_SFG.SFGCATEGORIA_ACIERTOS_L1LIAB01_FindRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCATEGORIA_ACIERTOS_L1LIAB01_FindRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCATEGORIA_ACIERTOS_L1LIAB01_FindRecord(@p_NOMBRECORTOCATEGORIA   VARCHAR(4000),
					  @p_ID_CATEGO_ACIER_L1LIAB01_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    SELECT @p_ID_CATEGO_ACIER_L1LIAB01_out = ID_CATEGORIA_ACIERTOS_L1LIAB01
    FROM WSXML_SFG.CATEGORIA_ACIERTOS_L1LIAB01 WHERE NOMBRECORTOCATEGORIA = @p_NOMBRECORTOCATEGORIA;
  IF @@ROWCOUNT  = 0
    
      SET @p_ID_CATEGO_ACIER_L1LIAB01_out = 0;
  END;
GO






