USE SFGPRODU;
--  DDL for Package Body SFGCALIFICACIONCARTERA
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGCALIFICACIONCARTERA */ 

IF OBJECT_ID('WSXML_SFG.SFGCALIFICACIONCARTERA_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCALIFICACIONCARTERA_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCALIFICACIONCARTERA_AddRecord(@p_CALIFICACION               FLOAT,
                      @p_CODUSUARIOMODIFICACION  NUMERIC(22,0),
                      @p_ID_CALIFICACIONCARTERA_out    NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    insert into WSXML_SFG.calificacioncartera
      (
           calificacion
           , codusuariomodificacion
           )
    values
      (
 CASE WHEN @p_CALIFICACION IS NULL OR @p_CALIFICACION < 0 THEN 0 ELSE @p_CALIFICACION END
           , @p_CODUSUARIOMODIFICACION
           );
    SET @p_ID_CALIFICACIONCARTERA_out = SCOPE_IDENTITY();


  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGCALIFICACIONCARTERA_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCALIFICACIONCARTERA_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCALIFICACIONCARTERA_UpdateRecord(@pk_ID_CALIFICACIONCARTERA      NUMERIC(22,0),
                         @p_CALIFICACION              FLOAT,
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;

    update WSXML_SFG.calificacioncartera
       set
           fechahoramodificacion = GETDATE(),
           calificacion = @p_CALIFICACION,
           codusuariomodificacion = @p_CODUSUARIOMODIFICACION,
           active = @p_ACTIVE
     where id_calificacioncartera = @pk_ID_CALIFICACIONCARTERA;


    IF @@rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @@rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCALIFICACIONCARTERA_DeactivateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCALIFICACIONCARTERA_DeactivateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCALIFICACIONCARTERA_DeactivateRecord(@pk_ID_CALIFICACIONCARTERA NUMERIC(22,0), @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.calificacioncartera
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = 0
     WHERE ID_CALIFICACIONCARTERA = @pk_ID_CALIFICACIONCARTERA;

    UPDATE WSXML_SFG.DETALLECALIFICACION
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = 0
     WHERE CODCALIFICACIONCARTERA = @pk_ID_CALIFICACIONCARTERA;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCALIFICACIONCARTERA_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCALIFICACIONCARTERA_GetRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCALIFICACIONCARTERA_GetRecord(@pk_ID_CALIFICACIONCARTERA NUMERIC(22,0)
                                       ) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;

    SELECT @l_count = COUNT(*) FROM WSXML_SFG.CALIFICACIONCARTERA
    WHERE ID_CALIFICACIONCARTERA = @pk_ID_CALIFICACIONCARTERA;

    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
	 
      SELECT ID_CALIFICACIONCARTERA,
             CALIFICACION,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.CALIFICACIONCARTERA
       WHERE ID_CALIFICACIONCARTERA = @pk_ID_CALIFICACIONCARTERA;
	 
  END;
GO

  -- Devuelve los registros de menor a mayor cupo
  IF OBJECT_ID('WSXML_SFG.SFGCALIFICACIONCARTERA_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCALIFICACIONCARTERA_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGCALIFICACIONCARTERA_GetList(@p_active NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
	  
      SELECT ID_CALIFICACIONCARTERA,
             CALIFICACION,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.CALIFICACIONCARTERA
       WHERE ACTIVE = CASE WHEN @p_active = -1 THEN ACTIVE ELSE @p_active END
       ORDER BY CALIFICACION DESC;
	

  END;
GO





