USE SFGPRODU;
--  DDL for Package Body SFGCALENDARIO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGCALENDARIO */ 

IF OBJECT_ID('WSXML_SFG.SFGCALENDARIO_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCALENDARIO_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCALENDARIO_AddRecord(@p_NOMCALENDARIO           NVARCHAR(2000),
                      @p_CODUSUARIOMODIFICACION  NUMERIC(22,0),
                      @p_ID_CALENDARIO_out       NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.CALENDARIO (
                              NOMCALENDARIO,
                              CODUSUARIOMODIFICACION)
    VALUES (
            @p_NOMCALENDARIO,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_CALENDARIO_out = SCOPE_IDENTITY();
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGCALENDARIO_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCALENDARIO_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCALENDARIO_UpdateRecord(@pk_ID_CALENDARIO         NUMERIC(22,0),
                         @p_NOMCALENDARIO          NVARCHAR(2000),
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.CALENDARIO
       SET NOMCALENDARIO          = @p_NOMCALENDARIO,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = @p_ACTIVE
     WHERE ID_CALENDARIO          = @pk_ID_CALENDARIO;

    IF @@rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @@rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCALENDARIO_AsignarPDV', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCALENDARIO_AsignarPDV;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCALENDARIO_AsignarPDV(@pk_ID_CALENDARIO         NUMERIC(22,0),
                       @p_CODPUNTODEVENTA        NUMERIC(22,0),
                       @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
 BEGIN
    DECLARE @dID_PUNTODEVENTACALENDARIO NUMERIC(22,0);
   
  SET NOCOUNT ON;

    BEGIN
		BEGIN TRY
		  SELECT @dID_PUNTODEVENTACALENDARIO = ID_PUNTODEVENTACALENDARIO FROM WSXML_SFG.PUNTODEVENTACALENDARIO
		   WHERE CODCALENDARIO = @pk_ID_CALENDARIO
			 AND CODPUNTODEVENTA = @p_CODPUNTODEVENTA;

			IF @@ROWCOUNT = 0
				SET @dID_PUNTODEVENTACALENDARIO = 0;
		END TRY
		BEGIN CATCH
		  SET @dID_PUNTODEVENTACALENDARIO = 0;
		END CATCH
    END;

    IF @dID_PUNTODEVENTACALENDARIO = 0 BEGIN
      INSERT INTO WSXML_SFG.PUNTODEVENTACALENDARIO (
                                          CODCALENDARIO,
                                          CODPUNTODEVENTA,
                                          CODUSUARIOMODIFICACION)
      VALUES (
              @pk_ID_CALENDARIO,
              @p_CODPUNTODEVENTA,
              @p_CODUSUARIOMODIFICACION);

    END
    ELSE BEGIN
      UPDATE WSXML_SFG.PUNTODEVENTACALENDARIO
         SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
             FECHAHORAMODIFICACION  = GETDATE()
       WHERE ID_PUNTODEVENTACALENDARIO = @dID_PUNTODEVENTACALENDARIO;
    END 
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGCALENDARIO_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCALENDARIO_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGCALENDARIO_GetRecord(@pk_ID_CALENDARIO NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;

    SELECT @l_count = count(*) FROM WSXML_SFG.CALENDARIO
     WHERE ID_CALENDARIO = @pk_ID_CALENDARIO;

    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

	  
      SELECT ID_CALENDARIO,
             NOMCALENDARIO,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.CALENDARIO
       WHERE ID_CALENDARIO = @pk_ID_CALENDARIO;
	
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGCALENDARIO_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCALENDARIO_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGCALENDARIO_GetList(@p_active NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
	  
      SELECT ID_CALENDARIO,
             NOMCALENDARIO,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.CALENDARIO
       WHERE ACTIVE = CASE WHEN @p_active = -1 THEN ACTIVE ELSE @p_active END;
	
  END;

