USE SFGPRODU;
--  DDL for Package Body SFGCUENTALINEADENEGOCIO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGCUENTALINEADENEGOCIO */ 

  IF OBJECT_ID('WSXML_SFG.SFGCUENTALINEADENEGOCIO_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCUENTALINEADENEGOCIO_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCUENTALINEADENEGOCIO_AddRecord(@p_CODLINEADENEGOCIO      NUMERIC(22,0),
                      @p_CODCUENTAGTECH         NUMERIC(22,0),
                      @p_CODCUENTAFIDUCIA       NUMERIC(22,0),
                      @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                      @p_ID_CUENTALDN_out       NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.CUENTALINEADENEGOCIO (
                                      CODLINEADENEGOCIO,
                                      CODCUENTAGTECH,
                                      CODCUENTAFIDUCIA,
                                      CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODLINEADENEGOCIO,
            @p_CODCUENTAGTECH,
            @p_CODCUENTAFIDUCIA,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_CUENTALDN_out = SCOPE_IDENTITY();
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCUENTALINEADENEGOCIO_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCUENTALINEADENEGOCIO_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCUENTALINEADENEGOCIO_UpdateRecord(@pk_ID_CUENTALDN          NUMERIC(22,0),
                         @p_CODLINEADENEGOCIO      NUMERIC(22,0),
                         @p_CODCUENTAGTECH         NUMERIC(22,0),
                         @p_CODCUENTAFIDUCIA       NUMERIC(22,0),
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.CUENTALINEADENEGOCIO
       SET CODLINEADENEGOCIO      = @p_CODLINEADENEGOCIO,
           CODCUENTAGTECH         = @p_CODCUENTAGTECH,
           CODCUENTAFIDUCIA       = @p_CODCUENTAFIDUCIA,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = @p_ACTIVE
     WHERE ID_CUENTALINEADENEGOCIO = @pk_ID_CUENTALDN;

	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT;
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCUENTALINEADENEGOCIO_DeactivateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCUENTALINEADENEGOCIO_DeactivateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCUENTALINEADENEGOCIO_DeactivateRecord(@pk_ID_CUENTALDN NUMERIC(22,0), @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.CUENTALINEADENEGOCIO
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = 0
     WHERE ID_CUENTALINEADENEGOCIO = @pk_ID_CUENTALDN;

	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT;
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCUENTALINEADENEGOCIO_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCUENTALINEADENEGOCIO_GetRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCUENTALINEADENEGOCIO_GetRecord(@pk_ID_CUENTALDN NUMERIC(22,0)
                                                                     ) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.CUENTALINEADENEGOCIO
     WHERE ID_CUENTALINEADENEGOCIO = @pk_ID_CUENTALDN;

    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
	 
      SELECT ID_CUENTALINEADENEGOCIO,
             CODLINEADENEGOCIO,
             CODCUENTAGTECH,
             CODCUENTAFIDUCIA,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.CUENTALINEADENEGOCIO
       WHERE ID_CUENTALINEADENEGOCIO = @pk_ID_CUENTALDN;
	   
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCUENTALINEADENEGOCIO_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCUENTALINEADENEGOCIO_GetList;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCUENTALINEADENEGOCIO_GetList(@p_active NUMERIC(22,0)
                                                                   ) AS
  BEGIN
  SET NOCOUNT ON;
    
      SELECT ID_CUENTALINEADENEGOCIO,
             CODLINEADENEGOCIO,
             CODCUENTAGTECH,
             CODCUENTAFIDUCIA,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.CUENTALINEADENEGOCIO
       WHERE ACTIVE = CASE WHEN @p_active = -1 THEN ACTIVE ELSE @p_active END;
	   
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCUENTALINEADENEGOCIO_GetCuentaDefecto', 'FN') IS NOT NULL
  DROP FUNCTION WSXML_SFG.SFGCUENTALINEADENEGOCIO_GetCuentaDefecto;
GO

CREATE FUNCTION WSXML_SFG.SFGCUENTALINEADENEGOCIO_GetCuentaDefecto(@p_CODLINEADENEGOCIO NUMERIC(22,0)) 
                 RETURNS NUMERIC(22,0) AS
 BEGIN
    DECLARE @cCODCUENTALINEADENEGOCIO NUMERIC(22,0);
   
    SELECT @cCODCUENTALINEADENEGOCIO = ID_CUENTALINEADENEGOCIO FROM WSXML_SFG.CUENTALINEADENEGOCIO
     WHERE CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
       AND DEFECTO = 1;

    IF(@@rowcount = 0)
	  BEGIN
	   SET @cCODCUENTALINEADENEGOCIO = 0
      END
    RETURN @cCODCUENTALINEADENEGOCIO;
 
  END;
GO






