USE SFGPRODU;
--  DDL for Package Body SFGCIUDADRETENCION
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGCIUDADRETENCION */ 

  IF OBJECT_ID('WSXML_SFG.SFGCIUDADRETENCION_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCIUDADRETENCION_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCIUDADRETENCION_AddRecord(@p_CODCIUDAD              NUMERIC(22,0),
                      @p_CODRETENCIONTRIBUTARIA NUMERIC(22,0),
                      @p_FECHAINICIOVALIDEZ     DATETIME,
                      @p_FECHAFINVALIDEZ        DATETIME,
                      @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                      @p_ID_CIUDADRETENCION_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.CIUDADRETENCION (
                                 CODCIUDAD,
                                 CODRETENCIONTRIBUTARIA,
                                 FECHAINICIOVALIDEZ,
                                 FECHAFINVALIDEZ,
                                 CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODCIUDAD,
            @p_CODRETENCIONTRIBUTARIA,
            @p_FECHAINICIOVALIDEZ,
            @p_FECHAFINVALIDEZ,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_CIUDADRETENCION_out = SCOPE_IDENTITY();
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCIUDADRETENCION_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCIUDADRETENCION_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCIUDADRETENCION_UpdateRecord(@pk_ID_CIUDADRETENCION    NUMERIC(22,0),
                         @p_CODCIUDAD              NUMERIC(22,0),
                         @p_CODRETENCIONTRIBUTARIA NUMERIC(22,0),
                         @p_FECHAINICIOVALIDEZ     DATETIME,
                         @p_FECHAFINVALIDEZ        DATETIME,
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.CIUDADRETENCION
       SET CODCIUDAD              = @p_CODCIUDAD,
           CODRETENCIONTRIBUTARIA = @p_CODRETENCIONTRIBUTARIA,
           FECHAINICIOVALIDEZ     = @p_FECHAINICIOVALIDEZ,
           FECHAFINVALIDEZ        = @p_FECHAFINVALIDEZ,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = @p_ACTIVE
     WHERE ID_CIUDADRETENCION = @pk_ID_CIUDADRETENCION;

	 DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCIUDADRETENCION_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCIUDADRETENCION_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGCIUDADRETENCION_GetRecord(@pk_ID_CIUDADRETENCION NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.CIUDADRETENCION WHERE ID_CIUDADRETENCION = @pk_ID_CIUDADRETENCION;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
	 
      SELECT ID_CIUDADRETENCION,
             CODCIUDAD,
             CODRETENCIONTRIBUTARIA,
             FECHAINICIOVALIDEZ,
             FECHAFINVALIDEZ,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.CIUDADRETENCION
       WHERE ID_CIUDADRETENCION = @pk_ID_CIUDADRETENCION;
	
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCIUDADRETENCION_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCIUDADRETENCION_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGCIUDADRETENCION_GetList(@p_active NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
	 
      SELECT ID_CIUDADRETENCION,
             CODCIUDAD,
             CODRETENCIONTRIBUTARIA,
             FECHAINICIOVALIDEZ,
             FECHAFINVALIDEZ,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.CIUDADRETENCION
       WHERE ACTIVE = CASE WHEN @p_active = -1 THEN ACTIVE ELSE @p_active END;
	
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCIUDADRETENCION_GetListByRetencion', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCIUDADRETENCION_GetListByRetencion;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCIUDADRETENCION_GetListByRetencion(@p_ACTIVE                 NUMERIC(22,0),
                              @p_CODRETENCIONTRIBUTARIA NUMERIC(22,0)
                                                     ) AS
  BEGIN
  SET NOCOUNT ON;
    
      SELECT CR.ID_CIUDADRETENCION,
             CR.CODCIUDAD,
             C.NOMCIUDAD,
             C.CODDEPARTAMENTO,
             D.NOMDEPARTAMENTO,
             CR.CODRETENCIONTRIBUTARIA,
             CR.FECHAINICIOVALIDEZ,
             CR.FECHAFINVALIDEZ,
             CR.CODUSUARIOMODIFICACION,
             CR.ACTIVE
      FROM WSXML_SFG.CIUDADRETENCION CR
      LEFT OUTER JOIN CIUDAD C ON (C.ID_CIUDAD = CR.CODCIUDAD)
      LEFT OUTER JOIN DEPARTAMENTO D ON (D.ID_DEPARTAMENTO = C.CODDEPARTAMENTO)
      WHERE CR.CODRETENCIONTRIBUTARIA = @p_CODRETENCIONTRIBUTARIA
        AND CR.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN CR.ACTIVE ELSE @p_ACTIVE END;
	
  END;
GO






