USE SFGPRODU;
--  DDL for Package Body SFGCONTROL_PREMIOS_FIDUCIA
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGCONTROL_PREMIOS_FIDUCIA */ 

  --Add Record in the table CONTROL_L1LIAB01
IF OBJECT_ID('WSXML_SFG.SFGCONTROL_PREMIOS_FIDUCIA_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCONTROL_PREMIOS_FIDUCIA_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCONTROL_PREMIOS_FIDUCIA_AddRecord(@p_FECHA_ARCHIVO                DATETIME,
                      @p_VALORREGISTROS               NUMERIC(22,0),
                      @p_NUMREGISTROS                 NUMERIC(22,0),
                      @p_NOMBREARCHIVO                VARCHAR(4000),
                      @p_RUTAARCHIVO                  VARCHAR(4000),
                      @p_FECHAHORAMODIFICACION        DATETIME,
                      @p_CODUSUARIOMODIFICACION       NUMERIC(22,0),
                      @p_ACTIVE                       NUMERIC(22,0),
                      @p_ID_CONTROL_PREMIOS_FIDUC_out NUMERIC(22,0) OUT) AS

 BEGIN
 SET NOCOUNT ON;

  INSERT INTO WSXML_SFG.CONTROL_PREMIOS_FIDUCIA
      (FECHA_ARCHIVO,
       VALORREGISTROS,
       NUMREGISTROS,
       NOMBREARCHIVO,
       RUTAARCHIVO,
       FECHAHORAMODIFICACION,
       CODUSUARIOMODIFICACION,
       ACTIVE)
    VALUES
      (@p_FECHA_ARCHIVO,
       @p_VALORREGISTROS,
       @p_NUMREGISTROS,
       @p_NOMBREARCHIVO,
       @p_RUTAARCHIVO,
       @p_FECHAHORAMODIFICACION,
       @p_CODUSUARIOMODIFICACION,
       @p_ACTIVE);

    SET @p_ID_CONTROL_PREMIOS_FIDUC_out = SCOPE_IDENTITY();
  END;
GO

  --Find Record on the table CONTROL_L1LIAB01
IF OBJECT_ID('WSXML_SFG.SFGCONTROL_PREMIOS_FIDUCIA_FindRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCONTROL_PREMIOS_FIDUCIA_FindRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCONTROL_PREMIOS_FIDUCIA_FindRecord(@p_FECHA_ARCHIVO     DATETIME,
                       @p_ID_CONTROL_PREMIOS_FIDUC_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    SELECT @p_ID_CONTROL_PREMIOS_FIDUC_out = ID_CONTROL_PREMIOS_FIDUCIA
      FROM WSXML_SFG.CONTROL_PREMIOS_FIDUCIA
     WHERE FECHA_ARCHIVO = @p_FECHA_ARCHIVO;

/*  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      SET @p_ID_CONTROL_PREMIOS_FIDUC_out = 0;
*/
      IF(@@rowcount = 0)
	  BEGIN
	   SET @p_ID_CONTROL_PREMIOS_FIDUC_out = 0
      END

  END;
GO

  --Delete Record on the table CONTROL_L1LIAB01
  IF OBJECT_ID('WSXML_SFG.SFGCONTROL_PREMIOS_FIDUCIA_DeleteRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCONTROL_PREMIOS_FIDUCIA_DeleteRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCONTROL_PREMIOS_FIDUCIA_DeleteRecord(@p_FECHA_ARCHIVO_A_REVERSAR DATETIME) AS
  BEGIN
  SET NOCOUNT ON;
    DELETE FROM WSXML_SFG.CONTROL_PREMIOS_FIDUCIA
     WHERE FECHA_ARCHIVO = @p_FECHA_ARCHIVO_A_REVERSAR;
  END;
GO






