USE SFGPRODU;
--  DDL for Package Body SFGCATEGORIACUPO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGCATEGORIACUPO */ 

IF OBJECT_ID('WSXML_SFG.SFGCATEGORIACUPO_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCATEGORIACUPO_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCATEGORIACUPO_AddRecord(@p_NOMCATEGORIACUPO        NVARCHAR(2000),
                      @p_VALORCUPO               FLOAT,
                      @p_CODUSUARIOMODIFICACION  NUMERIC(22,0),
                      @p_CALIFICACIONCARTERA     NUMERIC(22,0),
                      @p_ID_CATEGORIACUPO_out    NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;

    INSERT INTO WSXML_SFG.CATEGORIACUPO (
                                 NOMCATEGORIACUPO,
                                 VALORCUPO,
                                 CODUSUARIOMODIFICACION,
                                 CALIFICACIONCARTERA)

    VALUES (
            @p_NOMCATEGORIACUPO,
            CASE WHEN @p_VALORCUPO IS NULL OR @p_VALORCUPO < 0 THEN 0 ELSE @p_VALORCUPO END,
            @p_CODUSUARIOMODIFICACION,
            @p_CALIFICACIONCARTERA);
    SET @p_ID_CATEGORIACUPO_out = SCOPE_IDENTITY();

  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGCATEGORIACUPO_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCATEGORIACUPO_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCATEGORIACUPO_UpdateRecord(@pk_ID_CATEGORIACUPO      NUMERIC(22,0),
                         @p_NOMCATEGORIACUPO       NVARCHAR(2000),
                         @p_VALORCUPO              FLOAT,
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0),
                         @p_CALIFICACIONCARTERA     NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;

    UPDATE WSXML_SFG.CATEGORIACUPO
       SET NOMCATEGORIACUPO          = @p_NOMCATEGORIACUPO,
           VALORCUPO                 = @p_VALORCUPO,
           CODUSUARIOMODIFICACION    = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION     = GETDATE(),
           ACTIVE                    = @p_ACTIVE,
           CALIFICACIONCARTERA       = @p_CALIFICACIONCARTERA
     WHERE ID_CATEGORIACUPO = @pk_ID_CATEGORIACUPO;

    IF @@rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @@rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCATEGORIACUPO_DeactivateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCATEGORIACUPO_DeactivateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCATEGORIACUPO_DeactivateRecord(@pk_ID_CATEGORIACUPO NUMERIC(22,0), @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.CATEGORIACUPO
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = 0
     WHERE ID_CATEGORIACUPO = @pk_ID_CATEGORIACUPO;
    UPDATE WSXML_SFG.DETALLECATEGORIACUPO
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = 0
     WHERE CODCATEGORIACUPO = @pk_ID_CATEGORIACUPO;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCATEGORIACUPO_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCATEGORIACUPO_GetRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCATEGORIACUPO_GetRecord(@pk_ID_CATEGORIACUPO NUMERIC(22,0)
                                  ) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;

    SELECT @l_count = COUNT(*) FROM WSXML_SFG.CATEGORIACUPO
    WHERE ID_CATEGORIACUPO = @pk_ID_CATEGORIACUPO;

    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
	  
      SELECT ID_CATEGORIACUPO,
             NOMCATEGORIACUPO,
             VALORCUPO,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE,
             CALIFICACIONCARTERA
        FROM WSXML_SFG.CATEGORIACUPO
       WHERE ID_CATEGORIACUPO = @pk_ID_CATEGORIACUPO;
	
  END;
GO

  -- Devuelve los registros de menor a mayor cupo
  IF OBJECT_ID('WSXML_SFG.SFGCATEGORIACUPO_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCATEGORIACUPO_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGCATEGORIACUPO_GetList(@p_active NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
	  
      SELECT ID_CATEGORIACUPO,
             NOMCATEGORIACUPO,
             VALORCUPO,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE,
             CALIFICACIONCARTERA
        FROM WSXML_SFG.CATEGORIACUPO
       WHERE ACTIVE = CASE WHEN @p_active = -1 THEN ACTIVE ELSE @p_active END
       ORDER BY VALORCUPO ASC;
	
  END;
GO






