USE SFGPRODU;
--  DDL for Package Body SFGCRITERIODISTRIBUCION
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGCRITERIODISTRIBUCION */ 

  
  IF OBJECT_ID('WSXML_SFG.SFGCRITERIODISTRIBUCION_CONSTANT', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCRITERIODISTRIBUCION_CONSTANT;
GO
CREATE     PROCEDURE WSXML_SFG.SFGCRITERIODISTRIBUCION_CONSTANT(
	    @MENORAMAYOR SMALLINT OUT,
		@MAYORAMENOR SMALLINT OUT,
		@PORCENTAJEVENTAS SMALLINT OUT,
		@PORCENTAJECARTER SMALLINT OUT,
		@DISTRIBUCINIGUAL SMALLINT OUT,
		@PUNTOCENTRALIZAD SMALLINT OUT
	
	) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;

    SET @MENORAMAYOR = 1;
	SET @MAYORAMENOR = 2;
	SET @PORCENTAJEVENTAS = 3;
	SET @PORCENTAJECARTER = 4;
	SET @DISTRIBUCINIGUAL = 5;
	SET @PUNTOCENTRALIZAD = 6;

  END;
GO


IF OBJECT_ID('WSXML_SFG.SFGCRITERIODISTRIBUCION_GetCriterioFaltante', 'FN') IS NOT NULL
  DROP FUNCTION WSXML_SFG.SFGCRITERIODISTRIBUCION_GetCriterioFaltante;
GO

CREATE     FUNCTION WSXML_SFG.SFGCRITERIODISTRIBUCION_GetCriterioFaltante(@p_CODPUNTODEVENTA NUMERIC(22,0), @p_CODTIPOVINCULACIONPAGO NUMERIC(22,0)) RETURNS NUMERIC(22,0) AS
  BEGIN
    RETURN 1;
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGCRITERIODISTRIBUCION_GetCriterioExcedente', 'FN') IS NOT NULL
  DROP FUNCTION WSXML_SFG.SFGCRITERIODISTRIBUCION_GetCriterioExcedente;
GO

CREATE     FUNCTION WSXML_SFG.SFGCRITERIODISTRIBUCION_GetCriterioExcedente(@p_CODPUNTODEVENTA NUMERIC(22,0), @p_CODTIPOVINCULACIONPAGO NUMERIC(22,0)) RETURNS NUMERIC(22,0) AS
  BEGIN
    --SET @p_PARAMETRO_out = 1;
    RETURN 5;
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGCRITERIODISTRIBUCION_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCRITERIODISTRIBUCION_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGCRITERIODISTRIBUCION_GetRecord(@pk_ID_CRITERIODISTRIBUCION NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.CRITERIODISTRIBUCION WHERE ID_CRITERIODISTRIBUCION = @pk_ID_CRITERIODISTRIBUCION;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
	   
      SELECT ID_CRITERIODISTRIBUCION,
             NOMCRITERIODISTRIBUCION
        FROM WSXML_SFG.CRITERIODISTRIBUCION
       WHERE ID_CRITERIODISTRIBUCION = @pk_ID_CRITERIODISTRIBUCION;
	
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGCRITERIODISTRIBUCION_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCRITERIODISTRIBUCION_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGCRITERIODISTRIBUCION_GetList AS
  BEGIN
  SET NOCOUNT ON;
	  
      SELECT ID_CRITERIODISTRIBUCION,
             NOMCRITERIODISTRIBUCION
        FROM WSXML_SFG.CRITERIODISTRIBUCION;
			
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGCRITERIODISTRIBUCION_CreateCursor', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGCRITERIODISTRIBUCION_CreateCursor;
GO

CREATE     PROCEDURE WSXML_SFG.SFGCRITERIODISTRIBUCION_CreateCursor(@p_PARAMETRO NUMERIC(22,0), @p_CODLINEADENEGOCIO NUMERIC(22,0), @p_CODCRITERIODISTRIBUCION NUMERIC(22,0), @p_CODTIPOVINCULACIONPAGO NUMERIC(22,0), @p_FIDUCIA NUMERIC(22,0), @generalCursor cursor varying OUT, @countCursor NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
  
  SET @countCursor = 0;
	
	DECLARE @p_PUNTODEVENTA TINYINT, @p_AGRUPACNXNIT INT, @p_AGRUPACNXCAD INT
	EXEC WSXML_SFG.SFGTIPOVINCULACIONPAGO_CONSTANT @p_PUNTODEVENTA OUTPUT, @p_AGRUPACNXNIT OUTPUT, @p_AGRUPACNXCAD OUTPUT

	DECLARE @MENORAMAYOR SMALLINT,@MAYORAMENOR SMALLINT,@PORCENTAJEVENTAS SMALLINT,@PORCENTAJECARTER SMALLINT,@DISTRIBUCINIGUAL SMALLINT,@PUNTOCENTRALIZAD SMALLINT

	EXEC WSXML_SFG.SFGCRITERIODISTRIBUCION_CONSTANT  
		@MENORAMAYOR OUT,
		@MAYORAMENOR OUT,
		@PORCENTAJEVENTAS OUT,
		@PORCENTAJECARTER OUT,
		@DISTRIBUCINIGUAL OUT,
		@PUNTOCENTRALIZAD OUT

    IF @p_CODCRITERIODISTRIBUCION = @MENORAMAYOR BEGIN
       IF @p_CODTIPOVINCULACIONPAGO = @p_AGRUPACNXNIT BEGIN
          IF @p_FIDUCIA = 0 BEGIN--Es Gtech
		  
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA, CODMAESTROFACTURACIONPDV, (SALDOAFAVORGTECH - SALDOCONTRAGTECH) AS SALDOACTUAL 
					FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.IDENTIFICACION = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORGTECH - SALDOCONTRAGTECH) ASC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END
          ELSE BEGIN --es Fiducia
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA, CODMAESTROFACTURACIONPDV, (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.IDENTIFICACION = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) ASC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END 
       END
       ELSE IF @p_CODTIPOVINCULACIONPAGO= @p_AGRUPACNXCAD BEGIN
          IF @p_FIDUCIA = 0 BEGIN--Es Gtech
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA, CODMAESTROFACTURACIONPDV, (SALDOAFAVORGTECH - SALDOCONTRAGTECH) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.CODAGRUPACIONPUNTODEVENTA = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORGTECH - SALDOCONTRAGTECH) ASC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END
          ELSE BEGIN --es Fiducia
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA,CODMAESTROFACTURACIONPDV, (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) AS SALDOACTUAL 
					FROM WSXML_SFG.SALDOPDV SPV
						INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
						INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.CODAGRUPACIONPUNTODEVENTA = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) ASC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END 
       END 
    END
    ELSE IF @p_CODCRITERIODISTRIBUCION = @MAYORAMENOR BEGIN
      IF @p_CODTIPOVINCULACIONPAGO = @p_AGRUPACNXNIT BEGIN
          IF @p_FIDUCIA = 0 BEGIN--Es Gtech
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA, CODMAESTROFACTURACIONPDV, (SALDOAFAVORGTECH - SALDOCONTRAGTECH) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.IDENTIFICACION = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORGTECH - SALDOCONTRAGTECH) DESC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END
          ELSE BEGIN --es Fiducia
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA, CODMAESTROFACTURACIONPDV, (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.IDENTIFICACION = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) DESC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END 
       END
       ELSE IF @p_CODTIPOVINCULACIONPAGO= @p_AGRUPACNXCAD BEGIN
          IF @p_FIDUCIA = 0 BEGIN--Es Gtech
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA, CODMAESTROFACTURACIONPDV, (SALDOAFAVORGTECH - SALDOCONTRAGTECH) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.CODAGRUPACIONPUNTODEVENTA = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORGTECH - SALDOCONTRAGTECH) DESC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END
          ELSE BEGIN --es Fiducia
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA,CODMAESTROFACTURACIONPDV, (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.CODAGRUPACIONPUNTODEVENTA = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) DESC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END 
       END 
    END
    ELSE IF @p_CODCRITERIODISTRIBUCION = @PORCENTAJECARTER AND @p_FIDUCIA = 1 BEGIN
         IF @p_CODTIPOVINCULACIONPAGO = @p_AGRUPACNXNIT BEGIN
          IF @p_FIDUCIA = 0 BEGIN--Es Gtech
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA, CODMAESTROFACTURACIONPDV, (SALDOAFAVORGTECH - SALDOCONTRAGTECH) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.IDENTIFICACION = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORGTECH - SALDOCONTRAGTECH) ASC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END
          ELSE BEGIN --es Fiducia
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA, CODMAESTROFACTURACIONPDV, (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.IDENTIFICACION = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) ASC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END 
       END
       ELSE IF @p_CODTIPOVINCULACIONPAGO= @p_AGRUPACNXCAD BEGIN
          IF @p_FIDUCIA = 0 BEGIN--Es Gtech
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA, CODMAESTROFACTURACIONPDV, (SALDOAFAVORGTECH - SALDOCONTRAGTECH) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.CODAGRUPACIONPUNTODEVENTA = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORGTECH - SALDOCONTRAGTECH) ASC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END
          ELSE BEGIN --es Fiducia
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR
					
                    SELECT PDV.ID_PUNTODEVENTA,CODMAESTROFACTURACIONPDV, (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.CODAGRUPACIONPUNTODEVENTA = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) ASC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END 
       END 
    END
    ELSE IF @p_CODCRITERIODISTRIBUCION = @DISTRIBUCINIGUAL AND @p_FIDUCIA = 1 BEGIN
       IF @p_CODTIPOVINCULACIONPAGO = @p_AGRUPACNXNIT BEGIN
          IF @p_FIDUCIA = 0 BEGIN--Es Gtech
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA, CODMAESTROFACTURACIONPDV, (SALDOAFAVORGTECH - SALDOCONTRAGTECH) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.IDENTIFICACION = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORGTECH - SALDOCONTRAGTECH) ASC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END
          ELSE BEGIN --es Fiducia
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA, CODMAESTROFACTURACIONPDV, (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.IDENTIFICACION = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) ASC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END 
       END
       ELSE IF @p_CODTIPOVINCULACIONPAGO= @p_AGRUPACNXCAD BEGIN
          IF @p_FIDUCIA = 0 BEGIN--Es Gtech
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA, CODMAESTROFACTURACIONPDV, (SALDOAFAVORGTECH - SALDOCONTRAGTECH) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.CODAGRUPACIONPUNTODEVENTA = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORGTECH - SALDOCONTRAGTECH) ASC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END
          ELSE BEGIN --es Fiducia
					SET @generalCursor = CURSOR FORWARD_ONLY STATIC FOR 
					
                    SELECT PDV.ID_PUNTODEVENTA,CODMAESTROFACTURACIONPDV, (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) AS SALDOACTUAL FROM WSXML_SFG.SALDOPDV SPV
                    INNER JOIN WSXML_SFG.PUNTODEVENTA PDV ON (PDV.ID_PUNTODEVENTA = SPV.CODPUNTODEVENTA)
                    INNER JOIN WSXML_SFG.DETALLESALDOPDV DSP ON (DSP.ID_DETALLESALDOPDV = SPV.CODDETALLESALDOPDV)
                    WHERE PDV.CODAGRUPACIONPUNTODEVENTA = @p_PARAMETRO AND SPV.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
                    ORDER BY (SALDOAFAVORFIDUCIA - SALDOCONTRAFIDUCIA) ASC;
					
					OPEN @generalCursor
					SET @countCursor = @@CURSOR_ROWS
          END 
       END 
    END 
    /*IF generalCursor%ISOPEN THEN
      CLOSE generalCursor;
    END IF;*/
  END;
GO







