USE SFGPRODU;
--  DDL for Package Body SFGDESCOMISIONLINEADENEGOCIO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO */ 

  IF OBJECT_ID('WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_AddRecord(@p_CODLINEADENEGOCIO          NUMERIC(22,0),
                      @p_CODLINEADENEGOCIODESCUENTO NUMERIC(22,0),
                      @p_CODUSUARIOMODIFICACION     NUMERIC(22,0),
                      @p_ID_DESCOMISIONLDN_out      NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.DESCOMISIONLINEADENEGOCIO (
                                           CODLINEADENEGOCIO,
                                           CODLINEADENEGOCIODESCUENTO,
                                           CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODLINEADENEGOCIO,
            @p_CODLINEADENEGOCIODESCUENTO,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_DESCOMISIONLDN_out = SCOPE_IDENTITY();
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_UpdateRecord(@pk_ID_DESCOMISIONLDN         NUMERIC(22,0),
                         @p_CODLINEADENEGOCIO          NUMERIC(22,0),
                         @p_CODLINEADENEGOCIODESCUENTO NUMERIC(22,0),
                         @p_CODUSUARIOMODIFICACION     NUMERIC(22,0),
                         @p_ACTIVE                     NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.DESCOMISIONLINEADENEGOCIO
       SET CODLINEADENEGOCIO          = @p_CODLINEADENEGOCIO,
           CODLINEADENEGOCIODESCUENTO = @p_CODLINEADENEGOCIODESCUENTO,
           CODUSUARIOMODIFICACION     = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION      = GETDATE(),
           ACTIVE                     = @p_ACTIVE
     WHERE ID_DESCOMISIONLINEADENEGOCIO = @pk_ID_DESCOMISIONLDN;

    IF @@rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @@rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_DeactivateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_DeactivateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_DeactivateRecord(@pk_ID_DESCOMISIONLDN NUMERIC(22,0), 
                                                                                 @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.DESCOMISIONLINEADENEGOCIO
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = 0
     WHERE ID_DESCOMISIONLINEADENEGOCIO = @pk_ID_DESCOMISIONLDN;

    IF @@rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @@rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_GetRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_GetRecord(@pk_ID_DESCOMISIONLDN NUMERIC(22,0)
                                                                          ) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
   
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.DESCOMISIONLINEADENEGOCIO
     WHERE ID_DESCOMISIONLINEADENEGOCIO = @pk_ID_DESCOMISIONLDN;

    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
	
      SELECT ID_DESCOMISIONLINEADENEGOCIO,
             CODLINEADENEGOCIO,
             CODLINEADENEGOCIODESCUENTO,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.DESCOMISIONLINEADENEGOCIO
       WHERE ID_DESCOMISIONLINEADENEGOCIO = @pk_ID_DESCOMISIONLDN;
	   
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_GetList;
GO

CREATE     PROCEDURE WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_GetList(@p_active NUMERIC(22,0)
                                                                        ) AS
  BEGIN
  SET NOCOUNT ON;
    
      SELECT ID_DESCOMISIONLINEADENEGOCIO,
             CODLINEADENEGOCIO,
             CODLINEADENEGOCIODESCUENTO,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.DESCOMISIONLINEADENEGOCIO
       WHERE ACTIVE = CASE WHEN @p_active = -1 THEN ACTIVE ELSE @p_active END;
	   
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_GetLineaDeNegocioDescuento', 'FN') IS NOT NULL
   DROP FUNCTION WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_GetLineaDeNegocioDescuento;
 GO

CREATE FUNCTION WSXML_SFG.SFGDESCOMISIONLINEADENEGOCIO_GetLineaDeNegocioDescuento(@pk_ID_DESCOMISIONLINEADENEGOCI NUMERIC(22,0)) 
           RETURNS NUMERIC(22,0) AS
 BEGIN
    DECLARE @cCODLINEADENEGOCIO NUMERIC(22,0);
   
    SELECT @cCODLINEADENEGOCIO = CODLINEADENEGOCIODESCUENTO FROM WSXML_SFG.DESCOMISIONLINEADENEGOCIO
      WHERE ID_DESCOMISIONLINEADENEGOCIO = @pk_ID_DESCOMISIONLINEADENEGOCI;
     -- RETURN @cCODLINEADENEGOCIO;

    IF(@@rowcount = 0)
	  BEGIN
	   SET @cCODLINEADENEGOCIO = 0
      END
    RETURN @cCODLINEADENEGOCIO;


   --EXCEPTION WHEN OTHERS THEN
   -- RETURN NULL;
    /*
	  IF (@cCODLINEADENEGOCIO IS NULL)
	     SET @cCODLINEADENEGOCIO = 0
	RETURN @cCODLINEADENEGOCIO
	*/
   END;
GO






