USE SFGPRODU;
--  DDL for Package Body SFGDETALLECATEGORIAPAGO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGDETALLECATEGORIAPAGO */ 

  IF OBJECT_ID('WSXML_SFG.SFGDETALLECATEGORIAPAGO_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGDETALLECATEGORIAPAGO_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGDETALLECATEGORIAPAGO_AddRecord(@p_CODCATEGORIAPAGO            NUMERIC(22,0),
                      @p_CODOPERACIONPDV             NUMERIC(22,0),
                      @p_DESIGUALDAD                 CHAR,
                      @p_VALOR                       FLOAT,
                      @p_CODUSUARIOMODIFICACION      NUMERIC(22,0),
                      @p_ID_DETALLECATEGORIAPAGO_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    /* TODO implementation required */
    INSERT INTO WSXML_SFG.DETALLECATEGORIAPAGO (
                                        CODCATEGORIAPAGO,
                                        CODOPERACIONPDV,
                                        DESIGUALDAD,
                                        VALOR,
                                        CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODCATEGORIAPAGO,
            @p_CODOPERACIONPDV,
            @p_DESIGUALDAD,
            @p_VALOR,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_DETALLECATEGORIAPAGO_out = SCOPE_IDENTITY();
  --  NULL;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGDETALLECATEGORIAPAGO_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGDETALLECATEGORIAPAGO_UpdateRecord;
GO
  CREATE PROCEDURE WSXML_SFG.SFGDETALLECATEGORIAPAGO_UpdateRecord(@pk_ID_DETALLECATEGORIAPAGO NUMERIC(22,0),
                         @p_CODCATEGORIAPAGO         NUMERIC(22,0),
                         @p_CODOPERACIONPDV          NUMERIC(22,0),
                         @p_DESIGUALDAD              CHAR,
                         @p_VALOR                    FLOAT,
                         @p_CODUSUARIOMODIFICACION   NUMERIC(22,0),
                         @p_ACTIVE                   NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    /* TODO implementation required */
       UPDATE WSXML_SFG.DETALLECATEGORIAPAGO
       SET CODCATEGORIAPAGO          = @p_CODCATEGORIAPAGO,
           CODOPERACIONPDV           = @p_CODOPERACIONPDV,
           DESIGUALDAD               = @p_DESIGUALDAD,
           VALOR                     = @p_VALOR,
           CODUSUARIOMODIFICACION    = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION     = GETDATE(),
           ACTIVE                    = @p_ACTIVE
     WHERE ID_DETALLECATEGORIAPAGO   = @pk_ID_DETALLECATEGORIAPAGO;

    IF @@rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @@rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

  --  NULL;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGDETALLECATEGORIAPAGO_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGDETALLECATEGORIAPAGO_GetRecord;
GO
  CREATE PROCEDURE WSXML_SFG.SFGDETALLECATEGORIAPAGO_GetRecord(@pk_ID_DETALLECATEGORIAPAGO NUMERIC(22,0)
                      ) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;

    SELECT @l_count = COUNT(*) FROM WSXML_SFG.DETALLECATEGORIAPAGO
     WHERE ID_DETALLECATEGORIAPAGO = @pk_ID_DETALLECATEGORIAPAGO;

    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
	  
      SELECT D.ID_DETALLECATEGORIAPAGO,
             D.CODCATEGORIAPAGO,
             D.CODOPERACIONPDV,
             O.NOMOPERACIONPDV,
             D.DESIGUALDAD,
             D.VALOR,
             D.FECHAHORAMODIFICACION,
             D.CODUSUARIOMODIFICACION,
             D.ACTIVE
      FROM WSXML_SFG.DETALLECATEGORIAPAGO D
      LEFT OUTER JOIN WSXML_SFG.OPERACIONPDV O
        ON (O.ID_OPERACIONPDV = D.CODOPERACIONPDV)
      WHERE D.ID_DETALLECATEGORIAPAGO = @pk_ID_DETALLECATEGORIAPAGO;
	  
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGDETALLECATEGORIAPAGO_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGDETALLECATEGORIAPAGO_GetList;
GO

  CREATE PROCEDURE WSXML_SFG.SFGDETALLECATEGORIAPAGO_GetList(@p_active NUMERIC(22,0)
                                  ) AS
  BEGIN
  SET NOCOUNT ON;
    
    /* TODO implementation required */
      SELECT D.ID_DETALLECATEGORIAPAGO,
             D.CODCATEGORIAPAGO,
             D.CODOPERACIONPDV,
             O.NOMOPERACIONPDV,
             D.DESIGUALDAD,
             D.VALOR,
             D.FECHAHORAMODIFICACION,
             D.CODUSUARIOMODIFICACION,
             D.ACTIVE
      FROM WSXML_SFG.DETALLECATEGORIAPAGO D
      LEFT OUTER JOIN WSXML_SFG.OPERACIONPDV O
        ON (O.ID_OPERACIONPDV = D.CODOPERACIONPDV)
       WHERE D.ACTIVE = CASE WHEN @p_active = -1 THEN D.ACTIVE ELSE @p_active END;
	   
    --NULL;
  END;
GO 


  IF OBJECT_ID('WSXML_SFG.SFGDETALLECATEGORIAPAGO_GetListByHeader', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGDETALLECATEGORIAPAGO_GetListByHeader;
GO

  CREATE PROCEDURE WSXML_SFG.SFGDETALLECATEGORIAPAGO_GetListByHeader(@p_active NUMERIC(22,0),
                                  @p_CODCATEGORIAPAGO NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    
    /* TODO implementation required */
      SELECT D.ID_DETALLECATEGORIAPAGO,
             D.CODCATEGORIAPAGO,
             D.CODOPERACIONPDV,
             O.NOMOPERACIONPDV,
             D.DESIGUALDAD,
             D.VALOR,
             D.FECHAHORAMODIFICACION,
             D.CODUSUARIOMODIFICACION,
             D.ACTIVE
      FROM WSXML_SFG.DETALLECATEGORIAPAGO D
      LEFT OUTER JOIN WSXML_SFG.OPERACIONPDV O
        ON (O.ID_OPERACIONPDV = D.CODOPERACIONPDV)
       WHERE D.CODCATEGORIAPAGO = @p_CODCATEGORIAPAGO
         AND D.ACTIVE = CASE WHEN @p_active = -1 THEN D.ACTIVE ELSE @p_active END;
		 

    --NULL;
  END;
GO






