USE SFGPRODU;
--  DDL for Package Body SFGFACTURACIONLINEADENEGOCIO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO */ 

  IF OBJECT_ID('WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_AddRecord(@p_CODLINEADENEGOCIO       NUMERIC(22,0),
                      @p_CODPERIODICIDAD         NUMERIC(22,0),
                      @p_FECHA                   DATETIME,
                      @p_CODUSUARIOMODIFICACION  NUMERIC(22,0),
                      @p_ID_FACTURACIONLDN_out   NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.FACTURACIONLINEADENEGOCIO (
                                           CODLINEADENEGOCIO,
                                           CODPERIODICIDAD,
                                           FECHA,
                                           CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODLINEADENEGOCIO,
            @p_CODPERIODICIDAD,
            CONVERT(DATETIME, CONVERT(DATE,@p_FECHA)),
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_FACTURACIONLDN_out = SCOPE_IDENTITY();
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_UpdateRecord(@pk_ID_FACTURACIONLDN     NUMERIC(22,0),
                         @p_CODLINEADENEGOCIO       NUMERIC(22,0),
                         @p_CODPERIODICIDAD         NUMERIC(22,0),
                         @p_FECHA                   DATETIME,
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.FACTURACIONLINEADENEGOCIO
       SET CODLINEADENEGOCIO      = @p_CODLINEADENEGOCIO,
           CODPERIODICIDAD        = @p_CODPERIODICIDAD,
           FECHA                  = CONVERT(DATETIME, CONVERT(DATE,@p_FECHA)),
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = @p_ACTIVE
     WHERE ID_FACTURACIONLINEADENEGOCIO = @pk_ID_FACTURACIONLDN;

    IF @@rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @@rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_DeactivateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_DeactivateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_DeactivateRecord(@pk_ID_FACTURACIONLDN     NUMERIC(22,0),
                             @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.FACTURACIONLINEADENEGOCIO
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = 0
     WHERE ID_FACTURACIONLINEADENEGOCIO = @pk_ID_FACTURACIONLDN;

    IF @@rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @@rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_GetRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_GetRecord(@pk_ID_FACTURACIONLDN NUMERIC(22,0)
                                                                          ) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.FACTURACIONLINEADENEGOCIO
     WHERE ID_FACTURACIONLINEADENEGOCIO = @pk_ID_FACTURACIONLDN;

    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
	
      SELECT ID_FACTURACIONLINEADENEGOCIO,
             CODLINEADENEGOCIO,
             CODPERIODICIDAD,
             FECHA,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.FACTURACIONLINEADENEGOCIO
       WHERE ID_FACTURACIONLINEADENEGOCIO = @pk_ID_FACTURACIONLDN;
	   
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_GetList;
GO

CREATE     PROCEDURE WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_GetList(@p_active NUMERIC(22,0)
                                                                        ) AS
  BEGIN
  SET NOCOUNT ON;
    
      SELECT ID_FACTURACIONLINEADENEGOCIO,
             CODLINEADENEGOCIO,
             CODPERIODICIDAD,
             FECHA,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.FACTURACIONLINEADENEGOCIO
       WHERE ACTIVE = CASE WHEN @p_active = -1 THEN ACTIVE ELSE @p_active END;
	   
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_GetFacturacionDefecto', 'FN') IS NOT NULL
   DROP FUNCTION WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_GetFacturacionDefecto;
GO

CREATE     FUNCTION WSXML_SFG.SFGFACTURACIONLINEADENEGOCIO_GetFacturacionDefecto
            (@p_CODLINEADENEGOCIO NUMERIC(22,0)) 
              RETURNS NUMERIC(22,0) AS
 BEGIN
    DECLARE @cCODFACTURACIONLINEADENEGOCIO NUMERIC(22,0);
   
    SELECT @cCODFACTURACIONLINEADENEGOCIO = ID_FACTURACIONLINEADENEGOCIO FROM WSXML_SFG.FACTURACIONLINEADENEGOCIO
     WHERE CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
       AND DEFECTO = 1;

    RETURN @cCODFACTURACIONLINEADENEGOCIO;
 
 -- EXCEPTION WHEN OTHERS THEN
    
     IF(@@rowcount = 0)
	   BEGIN
	     SET @cCODFACTURACIONLINEADENEGOCIO = 0
       END
    RETURN @cCODFACTURACIONLINEADENEGOCIO;
  END;
GO






