USE SFGPRODU;
--  DDL for Package Body SFGINF_INVFILEXXX
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGINF_INVFILEXXX */ 

  IF OBJECT_ID('WSXML_SFG.SFGINF_INVFILEXXX_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGINF_INVFILEXXX_GetList;
GO

CREATE     PROCEDURE WSXML_SFG.SFGINF_INVFILEXXX_GetList(
                  @p_ACTIVE NUMERIC(22,0)
                  , @p_FECHAINICIO DATETIME
                  , @p_FECHAFIN DATETIME
                  , @P_CODCADENA NUMERIC(22,0)
                  , @p_ALI_ESTRATEGICO NVARCHAR(2000)
                  , @P_PRODUCTO NVARCHAR(2000)
                  , @p_SECUENCIA  NUMERIC(22,0)
                  , @p_LINEA  NUMERIC(22,0)
                 ) AS
  BEGIN
  SET NOCOUNT ON;


      select
             RIGHT(REPLICATE('0', 4) + APV.Codigoagrupaciongtech, 4) AS CHAIN
			, RIGHT(REPLICATE('0', 6) + PV.CODIGOGTECHPUNTODEVENTA, 6) AS POS
			, RIGHT(REPLICATE('0', 6) + dbo.fn_CharLTrim(PV.NUMEROTERMINAL,0), 6) AS TERM
			, RIGHT(REPLICATE('0', 15) + SUM(isnull(VPVF.VALORVENTA,0)), 15) AS VENTAS_VAT
			, RIGHT(REPLICATE('0', 15) + SUM(VPVF.IMPUESTO_IVA), 15) AS VAT
			, RIGHT(REPLICATE('0', 15) + (SUM(VPVF.VALORVENTA)- SUM(VPVF.IMPUESTO_IVA)), 15) AS VENTAS_SIN_VAT
			, RIGHT(REPLICATE('0', 15) + SUM(isnull(VPVF.VALORANULACION,0)), 15) AS T_CANCELLED
			, RIGHT(REPLICATE('0', 12) + SUM(ISNULL(VPVF.VALORCOMISIONNETA,0)), 12) AS COMISSION_GROSS
			, RIGHT(REPLICATE('0', 12) + SUM(ISNULL(VPVF.VATCOMISION,0)), 12) AS VAT_COMISSION_GROSS
			, RIGHT(REPLICATE('0', 12) + SUM(ISNULL(VPVF.VALORCOMISION,0)), 12) AS TOTAL_COMISSION
			, RIGHT(REPLICATE('0', 10) + SUM(VPVF.RETENCION_RENTA), 10) AS TAX_RENTA
			, RIGHT(REPLICATE('0', 10) + SUM(VPVF.RETENCION_RETEICA), 10) AS TAXS_INDCOME
			, RIGHT(REPLICATE('0', 10) + SUM(VPVF.RETENCION_RETEIVA), 10) AS TAX_IVA
			, RIGHT(REPLICATE('0', 15) + SUM(ISNULL(VPVF.VALORPREMIOPAGO,0)), 15) AS GAMES_PAYMENT
			, RIGHT(REPLICATE('0', 12) + SUM(ISNULL(VPVF.RETENCIONPREMIOSPAGADOS,0)), 12) AS TAX_RENTA_GAMES
			, RIGHT(REPLICATE('0', 12) + (SUM(ISNULL(VPVF.VALORPREMIOPAGO,0))+ SUM(ISNULL(VPVF.RETENCIONPREMIOSPAGADOS,0))), 12) AS TOTAL_GAMES_PAYMENT
			, RIGHT(REPLICATE('0', 15) + SUM(isnull(0,0)), 15) AS TOTAL_MONTO_ADEUDADO
			, RIGHT(REPLICATE('0', 15) + '0', 15) TOTAL_BALANCE		
			, RIGHT(REPLICATE('0', 15) + SUM(isnull(0,0)), 15) AS TOTAL_MONTO_ADEUDADO
			, RIGHT(REPLICATE('0', 15) + SUM(isnull(0,0)), 15) AS TOTAL_ADEUDADO_POS

			, RIGHT(REPLICATE('0', 15) + '0', 15) AS DEBT_FIDUCIARY
			, RIGHT(REPLICATE('0', 15) + '0', 15) AS DEBT_DAT
			, RIGHT(REPLICATE('0', 15) + '0', 15) AS DEBT_GTECH

       FROM WSXML_SFG.vw_show_pdvfacturacion VPVF
            inner join WSXML_SFG.PUNTODEVENTA PV on PV.id_puntodeventa= VPVF.ID_PUNTODEVENTA
            inner join WSXML_SFG.AGRUPACIONPUNTODEVENTA APV ON APV.ID_AGRUPACIONPUNTODEVENTA= VPVF.CODAGRUPACIONPUNTODEVENTA
            inner join WSXML_SFG.PRODUCTO P on p.id_producto = VPVF.ID_PRODUCTO
        WHERE VPVF.ID_CICLOFACTURACIONPDV = WSXML_SFG.ULTIMO_CICLOFACTURACION(@p_FECHAINICIO)
            and P.CODIGOGTECHPRODUCTO = @P_PRODUCTO


        GROUP BY
            P.CODIGOGTECHPRODUCTO
            , Apv.Codigoagrupaciongtech
            , PV.CODIGOGTECHPUNTODEVENTA
            , PV.NUMEROTERMINAL;



  END;
GO





