USE SFGPRODU;
--  DDL for Package Body SFGINF_INVPOSCHXX
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGINF_INVPOSCHXX */ 

  IF OBJECT_ID('WSXML_SFG.SFGINF_INVPOSCHXX_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGINF_INVPOSCHXX_GetList;
GO

CREATE     PROCEDURE WSXML_SFG.SFGINF_INVPOSCHXX_GetList(
                  @p_ACTIVE NUMERIC(22,0)
                  , @p_FECHAINICIO DATETIME
                  , @p_FECHAFIN DATETIME
                  , @P_CODCADENA NUMERIC(22,0)
                  , @p_ALI_ESTRATEGICO NVARCHAR(2000)
                  , @P_PRODUCTO NVARCHAR(2000)
                  , @p_SECUENCIA  NUMERIC(22,0)
                  , @p_LINEA  NUMERIC(22,0)
                  ) AS
  BEGIN
  SET NOCOUNT ON;


         select
            AE.ID_ALIADOESTRATEGICO AS  ID_ALIADOESTRATEGICO
			, RIGHT(REPLICATE('0', 5) + 'CHN', 5) AS RECORD_TYPE
            

			--, RIGHT(REPLICATE('0', 4) + PV.CODIGOAGRUPACIONGTECH, 4) AS CHAIN
			
			
			, RIGHT(REPLICATE('0', 15) + SUM(isnull(VPVF.VALORVENTA,0)), 15) AS T_ACEPTED_BP
			

			, RIGHT(REPLICATE('0', 15) + SUM(isnull(VPVF.VALORANULACION,0)), 15) AS T_CANCELL_BP
			

			, RIGHT(REPLICATE('0', 15) + SUM(isnull(VPVF.VALORCOMISION,0)), 15) AS COMISSION_BP
			

			, RIGHT(REPLICATE('0', 12) + SUM(isnull(VPVF.IMPUESTO_IVA,0)), 12) AS VAT
			
			, RIGHT(REPLICATE('0', 12) + SUM(isnull(VPVF.VALORCOMISION,0)), 12) AS COM_BP_SIN_VAT
			

			, RIGHT(REPLICATE('0', 12) + SUM(isnull(VPVF.VATCOMISION,0)), 12) AS VAT_Commission
			
			, RIGHT(REPLICATE('0', 12) + SUM(VPVF.VALORCOMISIONBRUTA), 12) AS COM_BP_CON_VAT
			

			, RIGHT(REPLICATE('0', 10) + SUM(VPVF.RETENCION_RENTA), 10) AS TAX_RENTA
			
			, RIGHT(REPLICATE('0', 10) + SUM(VPVF.RETENCION_RETEICA), 10) AS TAXS_INDCOME
			
			, RIGHT(REPLICATE('0', 10) + SUM(VPVF.RETENCION_RETEIVA), 10) AS TAX_IVA			

			, RIGHT(REPLICATE('0', 15) + SUM(VPVF.VALORPREMIOPAGO), 15) AS GAMES_PAYMENT
			
			, RIGHT(REPLICATE('0', 12) + SUM(VPVF.VALORCOMISIONNETA), 12) AS TOTAL_COMISSION_BP
			
			, RIGHT(REPLICATE('0', 12) + SUM(VPVF.VALORCOMISION-VPVF.VATCOMISION), 12) AS TOTAL_COMISSION_BP_SIN_VAT
            /*, LPAD((SUM(VPVF.NUEVOSALDOENCONTRAGTECH-VPVF.NUEVOSALDOAFAVORGTECH)
            + SUM(VPVF.NUEVOSALDOENCONTRAFIDUCIA-VPVF.NUEVOSALDOAFAVORFIDUCIA)
            ),15,'0') AS T_QUANTY_BP*/

        FROM
           WSXML_SFG.vw_show_pdvfacturacion VPVF
          inner join WSXML_SFG.PUNTODEVENTA PV on PV.id_puntodeventa= VPVF.ID_PUNTODEVENTA
          INNER JOIN WSXML_SFG.AGRUPACIONPUNTODEVENTA APV ON APV.ID_AGRUPACIONPUNTODEVENTA = VPVF.CODAGRUPACIONPUNTODEVENTA
          INNER JOIN WSXML_SFG.ALIADOESTRATEGICO AE ON AE.ID_ALIADOESTRATEGICO = VPVF.CODALIADOESTRATEGICO
          INNER JOIN WSXML_SFG.PRODUCTO P ON P.ID_PRODUCTO = VPVF.ID_PRODUCTO

       WHERE VPVF.id_ciclofacturacionpdv = WSXML_SFG.ULTIMO_CICLOFACTURACION(@p_FECHAINICIO)
        and pv.codagrupacionpuntodeventa <> WSXML_SFG.AGRUPACION_F(0)
        and VPVF.CODLINEADENEGOCIO = @p_LINEA
        and P.CODIGOGTECHPRODUCTO = @P_PRODUCTO
        GROUP BY AE.ID_ALIADOESTRATEGICO, APV.CODIGOAGRUPACIONGTECH;

  END;
GO







