USE SFGPRODU;
--  DDL for Package Body SFGINF_INVPOSBPXX
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGINF_INVPOSBPXX */ 

 IF OBJECT_ID('WSXML_SFG.SFGINF_INVPOSBPXX_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGINF_INVPOSBPXX_GetList;
GO

CREATE   PROCEDURE WSXML_SFG.SFGINF_INVPOSBPXX_GetList(
                  @p_ACTIVE NUMERIC(22,0)
                  , @p_FECHAINICIO DATETIME
                  , @p_FECHAFIN DATETIME
                  , @P_CODCADENA NUMERIC(22,0)
                  , @p_ALI_ESTRATEGICO NVARCHAR(2000)
                  , @P_PRODUCTO NVARCHAR(2000)
                  , @p_SECUENCIA  NUMERIC(22,0)
                  , @p_LINEA  NUMERIC(22,0)
                  
                  ) AS
  BEGIN
  SET NOCOUNT ON;


      select
            isnull(AE.ID_ALIADOESTRATEGICO,0) AS  ID_ALIADOESTRATEGICO
			, RIGHT(REPLICATE('0', 5) + (ISNULL(0, '') + 'POS'), 5) AS RECORD_TYPE
			, RIGHT(REPLICATE('0', 6) + PV.CODIGOGTECHPUNTODEVENTA, 6) AS POS
			, RIGHT(REPLICATE('0', 5) + dbo.fn_CharLTrim(PV.NUMEROTERMINAL,0), 5) AS TERM
			, RIGHT(REPLICATE('0', 12) + SUM(isnull(VPVF.VALORVENTA,0)), 12) AS T_ACEPTED_BP
			, RIGHT(REPLICATE('0', 12) + SUM(isnull(VPVF.VALORANULACION,0)), 12) AS T_CANCELL_BP

			, RIGHT(REPLICATE('0', 10) + SUM(isnull(VPVF.VALORCOMISION,0)), 10) AS COMISSION_BP
			

			, RIGHT(REPLICATE('0', 10) + SUM(VPVF.VATCOMISION), 10) AS VAT
			

			, RIGHT(REPLICATE('0', 10) + SUM(isnull(VPVF.VALORCOMISION,0)), 10) AS COMISSION_BP_SIN_VAT
			
			

			, RIGHT(REPLICATE('0', 10) + SUM(VPVF.RETENCION_RENTA), 10) AS TAX_RENTA
			

			, RIGHT(REPLICATE('0', 10) + SUM(VPVF.RETENCION_RETEICA), 10) AS TAXS_INDCOME
			
			, RIGHT(REPLICATE('0', 10) + SUM(VPVF.RETENCION_RETEIVA), 10) AS TAX_IVA
			
			, RIGHT(REPLICATE('0', 10) + SUM(VPVF.VALORCOMISION), 10) AS TOTAL_COMISSION_BP
			

			, RIGHT(REPLICATE('0', 10) + (SUM(0)+ SUM(0)), 10) AS T_QUANTY_BP
			

             FROM
                   WSXML_SFG.vw_show_pdvfacturacion VPVF
                   inner join WSXML_SFG.PUNTODEVENTA PV on PV.id_puntodeventa= VPVF.ID_PUNTODEVENTA
                   inner join WSXML_SFG.ALIADOESTRATEGICO AE ON AE.ID_ALIADOESTRATEGICO = VPVF.CODALIADOESTRATEGICO
                   INNER JOIN WSXML_SFG.PRODUCTO P ON P.ID_PRODUCTO = VPVF.ID_PRODUCTO
            WHERE VPVF.ID_CICLOFACTURACIONPDV =             WSXML_SFG. ULTIMO_CICLOFACTURACION(@p_FECHAINICIO)
                   and VPVF.CODLINEADENEGOCIO = @p_LINEA
                   and P.CODIGOGTECHPRODUCTO = @P_PRODUCTO
                   and pv.codagrupacionpuntodeventa = WSXML_SFG.AGRUPACION_F(0)


        GROUP BY
              AE.ID_ALIADOESTRATEGICO
            , PV.CODIGOGTECHPUNTODEVENTA
            , PV.NUMEROTERMINAL;



  END;
GO







