USE SFGPRODU;
--  DDL for Package Body SFGMODULO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGMODULO */ 

  -- CREATES A NEW RECORD IN THE MODULO TABLE
  IF OBJECT_ID('WSXML_SFG.SFGMODULO_ADDRECORD', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGMODULO_ADDRECORD;
GO

CREATE     PROCEDURE WSXML_SFG.SFGMODULO_ADDRECORD(@P_NOMMODULO              NVARCHAR(2000),
                      @P_CODUSUARIOMODIFICACION NUMERIC(22,0),
                      @p_ID_MODULO_out          NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.MODULO
      ( NOMMODULO, CODUSUARIOMODIFICACION)
    VALUES
      ( @P_NOMMODULO, @P_CODUSUARIOMODIFICACION);
    SET @p_ID_MODULO_out = SCOPE_IDENTITY();

  END;
GO

  -- UPDATES A RECORD IN THE MODULO TABLE.
  IF OBJECT_ID('WSXML_SFG.SFGMODULO_UPDATERECORD', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGMODULO_UPDATERECORD;
GO

CREATE     PROCEDURE WSXML_SFG.SFGMODULO_UPDATERECORD(@P_ID_MODULO              NUMERIC(22,0),
                         @PK_ID_MODULO             NUMERIC(22,0),
                         @P_NOMMODULO              NVARCHAR(2000),
                         @P_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @P_ACTIVE                 NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    -- UPDATE THE RECORD WITH THE PASSED PARAMETERS
    UPDATE WSXML_SFG.MODULO
       SET --ID_MODULO              = @P_ID_MODULO,
           NOMMODULO              = @P_NOMMODULO,
           CODUSUARIOMODIFICACION = @P_CODUSUARIOMODIFICACION,
           ACTIVE                 = @P_ACTIVE
     WHERE ID_MODULO = @PK_ID_MODULO;

    -- MAKE SURE ONLY ONE RECORD IS AFFECTED
	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT;
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 THE RECORD NO LONGER EXISTS.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 DUPLICATE OBJECT INSTANCES.', 16, 1);
    END 

  END;
GO

  -- DELETES A RECORD FROM THE MODULO TABLE.

  -- DELETES THE SET OF ROWS FROM THE MODULO TABLE
  -- THAT MATCH THE SPECIFIED SEARCH CRITERIA.
  -- RETURNS THE NUMBER OF ROWS DELETED AS AN OUTPUT PARAMETER.

  -- RETURNS A SPECIFIC RECORD FROM THE MODULO TABLE.
  IF OBJECT_ID('WSXML_SFG.SFGMODULO_GETRECORD', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGMODULO_GETRECORD;
GO

CREATE     PROCEDURE WSXML_SFG.SFGMODULO_GETRECORD(@PK_ID_MODULO NUMERIC(22,0)
                                                       ) AS
 BEGIN
    DECLARE @L_COUNT INTEGER;
   
  SET NOCOUNT ON;

    -- GET THE ROWCOUNT FIRST AND MAKE SURE
    -- ONLY ONE ROW IS RETURNED
    SELECT @L_COUNT = COUNT(*)
      FROM WSXML_SFG.MODULO
     WHERE ID_MODULO = @PK_ID_MODULO;

    IF @L_COUNT = 0 BEGIN
      RAISERROR('-20054 THE RECORD NO LONGER EXISTS.', 16, 1);
    END 

    IF @L_COUNT > 1 BEGIN
      RAISERROR('-20053 DUPLICATE OBJECT INSTANCES.', 16, 1);
    END 

    -- GET THE ROW FROM THE QUERY.  CHECKSUM VALUE WILL BE
    -- RETURNED ALONG THE ROW DATA TO SUPPORT CONCURRENCY.
	
      SELECT ID_MODULO,
             NOMMODULO,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.MODULO
       WHERE ID_MODULO = @PK_ID_MODULO;
	   
  END;
GO

  -- RETURNS A QUERY RESULTSET FROM TABLE MODULO
  -- GIVEN THE SEARCH CRITERIA AND SORTING CONDITION.
  -- IT WILL RETURN A SUBSET OF THE DATA BASED
  -- ON THE CURRENT PAGE NUMBER AND BATCH SIZE.  TABLE JOINS CAN
  -- BE PERFORMED IF THE JOIN CLAUSE IS SPECIFIED.
  --
  -- IF THE RESULTSET IS NOT EMPTY, IT WILL RETURN:
  --    1) THE TOTAL NUMBER OF ROWS WHICH MATCH THE CONDITION;
  --    2) THE RESULTSET IN THE CURRENT PAGE
  -- IF NOTHING MATCHES THE SEARCH CONDITION, IT WILL RETURN:
  --    1) COUNT IS 0 ;
  --    2) EMPTY RESULTSET.
  IF OBJECT_ID('WSXML_SFG.SFGMODULO_GETLIST', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGMODULO_GETLIST;
GO

CREATE     PROCEDURE WSXML_SFG.SFGMODULO_GETLIST(@P_ACTIVE NUMERIC(22,0)
                                                     ) AS

  BEGIN
  SET NOCOUNT ON;

    -- GET THE ROWS FROM THE QUERY.  CHECKSUM VALUE WILL BE
    -- RETURNED ALONG THE ROW DATA TO SUPPORT CONCURRENCY.
	
      SELECT ID_MODULO,
             NOMMODULO,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.MODULO
       WHERE ACTIVE = CASE WHEN @P_ACTIVE = -1 THEN ACTIVE ELSE @P_ACTIVE END;
	   
  END;
GO

-- RETURNS A QUERY RESULT FROM TABLE MODULO
-- GIVEN THE SEARCH CRITERIA AND SORTING CONDITION.

-- RETURNS A QUERY RESULT FROM TABLE MODULO
-- GIVEN THE SEARCH CRITERIA AND SORTING CONDITION.

-- RETURNS THE QUERY RESULT SET IN A CSV FORMAT
-- SO THAT THE DATA CAN BE EXPORTED TO A CSV FILE






