USE SFGPRODU;
--  DDL for Package Body SFGPUNTODEVENTACUENTA
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGPUNTODEVENTACUENTA */ 

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTACUENTA_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_AddRecord(@p_CODPUNTODEVENTA         NUMERIC(22,0),
                      @p_CODCUENTALINEADENEGOCIO NUMERIC(22,0),
                      @p_CODUSUARIOMODIFICACION  NUMERIC(22,0),
                      @p_ID_PDVCUENTA_out        NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.PUNTODEVENTACUENTA (
                                    CODPUNTODEVENTA,
                                    CODCUENTALINEADENEGOCIO,
                                    CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODPUNTODEVENTA,
            @p_CODCUENTALINEADENEGOCIO,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_PDVCUENTA_out = SCOPE_IDENTITY();
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTACUENTA_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_UpdateRecord(@pk_ID_PDVCUENTA           NUMERIC(22,0),
                         @p_CODPUNTODEVENTA         NUMERIC(22,0),
                         @p_CODCUENTALINEADENEGOCIO NUMERIC(22,0),
                         @p_CODUSUARIOMODIFICACION  NUMERIC(22,0),
                         @p_ACTIVE                  NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.PUNTODEVENTACUENTA
       SET CODPUNTODEVENTA         = @p_CODPUNTODEVENTA,
           CODCUENTALINEADENEGOCIO = @p_CODCUENTALINEADENEGOCIO,
           CODUSUARIOMODIFICACION  = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION   = GETDATE(),
           ACTIVE                  = @p_ACTIVE
     WHERE ID_PUNTODEVENTACUENTA = @pk_ID_PDVCUENTA;

	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT;
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTACUENTA_SetCuentaContext', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_SetCuentaContext;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_SetCuentaContext(@pk_ID_PDVCUENTA          NUMERIC(22,0),
                             @p_CODPUNTODEVENTA        NUMERIC(22,0),
                             @p_CODLINEADENEGOCIO      NUMERIC(22,0),
                             @p_CODCUENTAGTECH         NUMERIC(22,0),
                             @p_CODCUENTAFIDUCIA       NUMERIC(22,0),
                             @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                             @p_ID_PDVCUENTA_out       NUMERIC(22,0) OUT) AS
 BEGIN
    DECLARE @cCODCUENTALINEADENEGOCIO NUMERIC(22,0);
   
  SET NOCOUNT ON;
    SET @p_ID_PDVCUENTA_out = 0;
    BEGIN
		BEGIN TRY
      SELECT @cCODCUENTALINEADENEGOCIO = ID_CUENTALINEADENEGOCIO
        FROM WSXML_SFG.CUENTALINEADENEGOCIO
       WHERE CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
         AND CODCUENTAGTECH = @p_CODCUENTAGTECH
         AND CODCUENTAFIDUCIA = @p_CODCUENTAFIDUCIA;
		 END TRY
		 BEGIN CATCH
    
		  EXEC WSXML_SFG.SFGCUENTALINEADENEGOCIO_AddRecord @p_CODLINEADENEGOCIO,
                                        @p_CODCUENTAGTECH,
                                        @p_CODCUENTAFIDUCIA,
                                        @p_CODUSUARIOMODIFICACION,
                                        @cCODCUENTALINEADENEGOCIO OUT
		END CATCH
    END;

    IF @pk_ID_PDVCUENTA > 0 BEGIN
        DECLARE @thCODCUENTALINEADENEGOCIO NUMERIC(22,0);
      BEGIN
		BEGIN TRY
			SELECT @thCODCUENTALINEADENEGOCIO = CODCUENTALINEADENEGOCIO
			  FROM WSXML_SFG.PUNTODEVENTACUENTA
			 WHERE ID_PUNTODEVENTACUENTA = @pk_ID_PDVCUENTA
			   AND CODPUNTODEVENTA = @p_CODPUNTODEVENTA;
			IF @thCODCUENTALINEADENEGOCIO <> @cCODCUENTALINEADENEGOCIO BEGIN
			  EXEC WSXML_SFG.SFGPUNTODEVENTACUENTA_DeactivateRecord @pk_ID_PDVCUENTA, @p_CODUSUARIOMODIFICACION 
			   EXEC WSXML_SFG.SFGPUNTODEVENTACUENTA_AddRecord @p_CODPUNTODEVENTA,
						@cCODCUENTALINEADENEGOCIO,
						@p_CODUSUARIOMODIFICACION,
						@p_ID_PDVCUENTA_out OUT
			END 
		END TRY
			BEGIN CATCH

			 EXEC WSXML_SFG.SFGPUNTODEVENTACUENTA_AddRecord @p_CODPUNTODEVENTA,
					  @cCODCUENTALINEADENEGOCIO,
					  @p_CODUSUARIOMODIFICACION,
					  @p_ID_PDVCUENTA_out OUT
			END CATCH
      END;

    END
    ELSE BEGIN
      EXEC WSXML_SFG.SFGPUNTODEVENTACUENTA_AddRecord @p_CODPUNTODEVENTA,
                  @cCODCUENTALINEADENEGOCIO,
                  @p_CODUSUARIOMODIFICACION,
                  @p_ID_PDVCUENTA_out OUT
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTACUENTA_DeactivateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_DeactivateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_DeactivateRecord(@pk_ID_PDVCUENTA NUMERIC(22,0), @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.PUNTODEVENTACUENTA
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = 0
     WHERE ID_PUNTODEVENTACUENTA = @pk_ID_PDVCUENTA;

	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT;
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTACUENTA_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_GetRecord(@pk_ID_PDVCUENTA NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.PUNTODEVENTACUENTA
     WHERE ID_PUNTODEVENTACUENTA = @pk_ID_PDVCUENTA;

    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

      SELECT ID_PUNTODEVENTACUENTA,
             CODPUNTODEVENTA,
             CODCUENTALINEADENEGOCIO,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.PUNTODEVENTACUENTA
       WHERE ID_PUNTODEVENTACUENTA = @pk_ID_PDVCUENTA;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTACUENTA_GetActualRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_GetActualRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_GetActualRecord(@p_CODPUNTODEVENTA NUMERIC(22,0), @p_CODLINEADENEGOCIO NUMERIC(22,0), @p_CODCUENTAGTECH_out NUMERIC(22,0) OUT, @p_CODCUENTAFIDUCIA_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    BEGIN
		BEGIN TRY
      SELECT @p_CODCUENTAGTECH_out = CODCUENTAGTECH, @p_CODCUENTAFIDUCIA_out = CODCUENTAFIDUCIA
        FROM WSXML_SFG.PUNTODEVENTACUENTA PC
			LEFT OUTER JOIN WSXML_SFG.CUENTALINEADENEGOCIO CL ON PC.CODCUENTALINEADENEGOCIO = CL.ID_CUENTALINEADENEGOCIO
       WHERE PC.CODPUNTODEVENTA = @p_CODPUNTODEVENTA
         AND CL.CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
         AND PC.ACTIVE = 1;
		END TRY
		BEGIN CATCH
    
		  SELECT @p_CODCUENTAGTECH_out = CODCUENTAGTECH, @p_CODCUENTAFIDUCIA_out = CODCUENTAFIDUCIA
			FROM WSXML_SFG.CUENTALINEADENEGOCIO
		   WHERE CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
			 AND DEFECTO = 1;
		 END CATCH
    END;

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTACUENTA_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_GetList(@p_active NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT ID_PUNTODEVENTACUENTA,
             CODPUNTODEVENTA,
             CODCUENTALINEADENEGOCIO,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.PUNTODEVENTACUENTA
       WHERE ACTIVE = CASE WHEN @p_active = -1 THEN ACTIVE ELSE @p_active END;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTACUENTA_GetListByPuntoDeVenta', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_GetListByPuntoDeVenta;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_GetListByPuntoDeVenta(@p_ACTIVE NUMERIC(22,0), @p_CODPUNTODEVENTA NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT PC.ID_PUNTODEVENTACUENTA,
             LDN.ID_LINEADENEGOCIO,
             LDN.NOMLINEADENEGOCIO,
             CL.CODCUENTAGTECH,
             CL.CODCUENTAFIDUCIA
      FROM WSXML_SFG.PUNTODEVENTA PDV
      LEFT OUTER JOIN WSXML_SFG.PUNTODEVENTACUENTA PC
        ON (PC.CODPUNTODEVENTA = PDV.ID_PUNTODEVENTA
        AND PC.ACTIVE = 1)
      LEFT OUTER JOIN WSXML_SFG.CUENTALINEADENEGOCIO CL
        ON (CL.ID_CUENTALINEADENEGOCIO = PC.CODCUENTALINEADENEGOCIO
        AND CL.ACTIVE = 1)
      LEFT OUTER JOIN WSXML_SFG.LINEADENEGOCIO LDN
        ON (LDN.ID_LINEADENEGOCIO = CL.CODLINEADENEGOCIO
        AND LDN.ACTIVE = 1)
      WHERE PDV.ID_PUNTODEVENTA = @p_CODPUNTODEVENTA
        AND PC.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN PC.ACTIVE ELSE @p_ACTIVE END;

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTACUENTA_GetListPorDefecto', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_GetListPorDefecto;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTACUENTA_GetListPorDefecto(@p_ACTIVE NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT 0 ID_PUNTODEVENTACUENTA,
             LDN.ID_LINEADENEGOCIO,
             LDN.NOMLINEADENEGOCIO,
             CL.CODCUENTAGTECH,
             CL.CODCUENTAFIDUCIA
      FROM WSXML_SFG.LINEADENEGOCIO LDN
      LEFT OUTER JOIN WSXML_SFG.CUENTALINEADENEGOCIO CL
        ON (CL.CODLINEADENEGOCIO = LDN.ID_LINEADENEGOCIO)
      WHERE LDN.ACTIVE = 1
        AND CL.DEFECTO = 1
        AND CL.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN CL.ACTIVE ELSE @p_ACTIVE END;
  END
GO






