USE SFGPRODU;
--  DDL for Package Body SFGPUNTODEVENTAPLANTILLA
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGPUNTODEVENTAPLANTILLA */ 

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_AddRecord(@p_CODPUNTODEVENTA              NUMERIC(22,0),
                      @p_CODPLANTILLAPRODUCTO         NUMERIC(22,0),
                      @p_FECHAINICIOVALIDEZ           DATETIME,
                      @p_FECHAFINVALIDEZ              DATETIME,
                      @p_CODPLANTILLAPERMANENTE       NUMERIC(22,0),
                      @p_CODUSUARIOMODIFICACION       NUMERIC(22,0),
                      @p_ID_PUNTODEVENTAPLANTILLA_out NUMERIC(22,0) OUT) AS
 BEGIN
    DECLARE @cCODLINEADENEGOCIO NUMERIC(22,0) = 0;
    DECLARE @countPLANTILLAS NUMERIC(22,0) = 0;
   
  SET NOCOUNT ON;
    SELECT @cCODLINEADENEGOCIO = CODLINEADENEGOCIO FROM WSXML_SFG.PLANTILLAPRODUCTO
     WHERE ID_PLANTILLAPRODUCTO = @p_CODPLANTILLAPRODUCTO;

    SELECT @countPLANTILLAS = COUNT(1) FROM WSXML_SFG.PUNTODEVENTAPLANTILLA
     WHERE CODLINEADENEGOCIO = @cCODLINEADENEGOCIO
       AND CODPUNTODEVENTA = @p_CODPUNTODEVENTA
       AND ACTIVE = 1;

    IF @countPLANTILLAS > 0 BEGIN
      UPDATE WSXML_SFG.PUNTODEVENTAPLANTILLA SET ACTIVE = 0
       WHERE CODLINEADENEGOCIO = @cCODLINEADENEGOCIO
         AND CODPUNTODEVENTA = @p_CODPUNTODEVENTA
         AND ACTIVE = 1;
    END 

    INSERT INTO WSXML_SFG.PUNTODEVENTAPLANTILLA (
                                       CODPUNTODEVENTA,
                                       CODPLANTILLAPRODUCTO,
                                       CODLINEADENEGOCIO,
                                       FECHAINICIOVALIDEZ,
                                       FECHAFINVALIDEZ,
                                       CODPLANTILLAPERMANENTE,
                                       CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODPUNTODEVENTA,
            @p_CODPLANTILLAPRODUCTO,
            @cCODLINEADENEGOCIO,
            @p_FECHAINICIOVALIDEZ,
            @p_FECHAFINVALIDEZ,
            @p_CODPLANTILLAPERMANENTE,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_PUNTODEVENTAPLANTILLA_out = SCOPE_IDENTITY();

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_UpdateRecord(@pk_ID_PUNTODEVENTAPLANTILLA    NUMERIC(22,0),
                         @p_CODPUNTODEVENTA              NUMERIC(22,0),
                         @p_CODPLANTILLAPRODUCTO         NUMERIC(22,0),
                         @p_FECHAINICIOVALIDEZ           DATETIME,
                         @p_FECHAFINVALIDEZ              DATETIME,
                         @p_CODPLANTILLAPERMANENTE       NUMERIC(22,0),
                         @p_CODUSUARIOMODIFICACION       NUMERIC(22,0),
                         @p_ACTIVE                       NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.PUNTODEVENTAPLANTILLA
       SET CODPUNTODEVENTA        = @p_CODPUNTODEVENTA,
           CODPLANTILLAPRODUCTO   = @p_CODPLANTILLAPRODUCTO,
           FECHAINICIOVALIDEZ     = @p_FECHAINICIOVALIDEZ,
           FECHAFINVALIDEZ        = @p_FECHAFINVALIDEZ,
           CODPLANTILLAPERMANENTE = @p_CODPLANTILLAPERMANENTE,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           ACTIVE               = @p_ACTIVE
     WHERE ID_PUNTODEVENTAPLANTILLA = @pk_ID_PUNTODEVENTAPLANTILLA;

	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT;
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_DeactivateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_DeactivateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_DeactivateRecord(@pk_ID_PUNTODEVENTAPLANTILLA NUMERIC(22,0), @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.PUNTODEVENTAPLANTILLA
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION = GETDATE(),
           ACTIVE = 0
     WHERE ID_PUNTODEVENTAPLANTILLA = @pk_ID_PUNTODEVENTAPLANTILLA;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_DeactivateRecordByData', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_DeactivateRecordByData;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_DeactivateRecordByData(@p_CODPUNTODEVENTA NUMERIC(22,0), @p_CODLINEADENEGOCIO NUMERIC(22,0), @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.PUNTODEVENTAPLANTILLA
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION = GETDATE(),
           ACTIVE = 0
     WHERE CODPUNTODEVENTA = @p_CODPUNTODEVENTA
       AND CODLINEADENEGOCIO = @p_CODLINEADENEGOCIO
       AND ACTIVE = 1;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_GetRecord(@pk_ID_PUNTODEVENTAPLANTILLA NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.PUNTODEVENTAPLANTILLA WHERE ID_PUNTODEVENTAPLANTILLA = @pk_ID_PUNTODEVENTAPLANTILLA;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

      SELECT ID_PUNTODEVENTAPLANTILLA,
             CODPUNTODEVENTA,
             CODPLANTILLAPRODUCTO,
             CODLINEADENEGOCIO,
             FECHAINICIOVALIDEZ,
             FECHAFINVALIDEZ,
             CODPLANTILLAPERMANENTE,
             CODUSUARIOMODIFICACION
             ACTIVE
        FROM WSXML_SFG.PUNTODEVENTAPLANTILLA
       WHERE ID_PUNTODEVENTAPLANTILLA = @pk_ID_PUNTODEVENTAPLANTILLA;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPUNTODEVENTAPLANTILLA_GetList(@p_active NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT ID_PUNTODEVENTAPLANTILLA,
             CODPUNTODEVENTA,
             CODPLANTILLAPRODUCTO,
             CODLINEADENEGOCIO,
             FECHAINICIOVALIDEZ,
             FECHAFINVALIDEZ,
             CODPLANTILLAPERMANENTE,
             CODUSUARIOMODIFICACION
             ACTIVE
        FROM WSXML_SFG.PUNTODEVENTAPLANTILLA
       WHERE ACTIVE = CASE WHEN @p_active = -1 THEN ACTIVE ELSE @p_active END;
  END;
GO






