USE SFGPRODU;
--  DDL for Package Body SFGPERIODICIDADPAGO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGPERIODICIDADPAGO */ 
IF OBJECT_ID('WSXML_SFG.SFGPERIODICIDADPAGO_CONSTANT', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_CONSTANT;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_CONSTANT(
						    @freqTRUE  VARCHAR(5) OUT,
							@freqFALSE VARCHAR(5) OUT,
							@dayMONDAY SMALLINT OUT,
							@dayTUESDA SMALLINT OUT,
							@dayWEDNES SMALLINT OUT,
							@dayTHURSD SMALLINT OUT,
							@dayFRIDAY SMALLINT OUT,
							@daySATURD SMALLINT OUT,
							@daySUNDAY SMALLINT	OUT				  
					  ) AS
  BEGIN
  SET NOCOUNT ON;
    SET @freqTRUE  = 'TRUE';
	SET @freqFALSE = 'FALSE';
	SET @dayMONDAY = 1;
	SET @dayTUESDA = 2;
	SET @dayWEDNES = 3;
	SET @dayTHURSD = 4;
	SET @dayFRIDAY = 5;
	SET @daySATURD = 6;
	SET @daySUNDAY = 7;

  END;
GO  
  
  
  IF OBJECT_ID('WSXML_SFG.SFGPERIODICIDADPAGO_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_AddRecord(@p_NOMPERIODICIDADPAGO     NVARCHAR(2000),
                      @p_FUNCION                 NVARCHAR(2000),
                      @p_CODUSUARIOMODIFICACION  NUMERIC(22,0),
                      @p_ID_PERIODICIDADPAGO_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.PERIODICIDADPAGO (
                                  NOMPERIODICIDADPAGO,
                                  FUNCION,
                                  CODUSUARIOMODIFICACION)
    VALUES (
            @p_NOMPERIODICIDADPAGO,
            @p_FUNCION,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_PERIODICIDADPAGO_out = SCOPE_IDENTITY();

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPERIODICIDADPAGO_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_UpdateRecord(@pk_ID_PERIODICIDADPAGO   NUMERIC(22,0),
                         @p_NOMPERIODICIDADPAGO    NVARCHAR(2000),
                         @p_FUNCION                NVARCHAR(2000),
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.PERIODICIDADPAGO
       SET NOMPERIODICIDADPAGO    = @p_NOMPERIODICIDADPAGO,
           FUNCION                = @p_FUNCION,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           ACTIVE                 = @p_ACTIVE
     WHERE ID_PERIODICIDADPAGO    = @pk_ID_PERIODICIDADPAGO;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPERIODICIDADPAGO_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_GetRecord(@pk_ID_PERIODICIDADPAGO NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(1) FROM WSXML_SFG.PERIODICIDADPAGO WHERE ID_PERIODICIDADPAGO = @pk_ID_PERIODICIDADPAGO;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END
    ELSE IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

      SELECT ID_PERIODICIDADPAGO,
             NOMPERIODICIDADPAGO,
             FUNCION,
             FECHAHORAMODIFICACION
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.PERIODICIDADPAGO
       WHERE ID_PERIODICIDADPAGO = @pk_ID_PERIODICIDADPAGO;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPERIODICIDADPAGO_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_GetList(@p_ACTIVE NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT ID_PERIODICIDADPAGO,
             NOMPERIODICIDADPAGO,
             FUNCION,
             FECHAHORAMODIFICACION
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.PERIODICIDADPAGO
       WHERE ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN ACTIVE ELSE @p_ACTIVE END;
  END;
GO

  /* PAYMENT FREQUENCY FUNCTIONS */
  /* Pago Diario requiere que existan pagos cargados
     Martes, Miercoles, Jueves, Viernes y Sabado */
  IF OBJECT_ID('WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadDiario', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadDiario;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadDiario(@p_FECHAHOY DATETIME, @p_result VARCHAR(4000) OUT ) AS
  BEGIN
  
  
  
	DECLARE @freqTRUE  VARCHAR(5),@freqFALSE VARCHAR(5),@dayMONDAY SMALLINT,@dayTUESDA SMALLINT,@dayWEDNES SMALLINT,@dayTHURSD SMALLINT,@dayFRIDAY SMALLINT,@daySATURD SMALLINT,@daySUNDAY SMALLINT	;
	EXEC WSXML_SFG.SFGPERIODICIDADPAGO_CONSTANT @freqTRUE   OUT, @freqFALSE  OUT, @dayMONDAY  OUT, @dayTUESDA  OUT, @dayWEDNES  OUT, @dayTHURSD  OUT, @dayFRIDAY  OUT, @daySATURD  OUT, @daySUNDAY  OUT	
	
    IF CAST(DATEPART(weekday, @p_FECHAHOY) AS SMALLINT) IN (@dayTUESDA, @dayWEDNES, @dayTHURSD, @dayFRIDAY, @daySATURD) BEGIN
      SET @p_result = @freqTRUE;
    END
    ELSE BEGIN
      SET @p_result = @freqFALSE;
    END 
  END;
GO


  IF OBJECT_ID('WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadTresDias', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadTresDias;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadTresDias(@p_FECHAHOY DATETIME, @p_result VARCHAR(4000) OUT)  AS
  BEGIN
	DECLARE @freqTRUE  VARCHAR(5),@freqFALSE VARCHAR(5),@dayMONDAY SMALLINT,@dayTUESDA SMALLINT,@dayWEDNES SMALLINT,@dayTHURSD SMALLINT,@dayFRIDAY SMALLINT,@daySATURD SMALLINT,@daySUNDAY SMALLINT	
	EXEC WSXML_SFG.SFGPERIODICIDADPAGO_CONSTANT @freqTRUE   OUT, @freqFALSE  OUT, @dayMONDAY  OUT, @dayTUESDA  OUT, @dayWEDNES  OUT, @dayTHURSD  OUT, @dayFRIDAY  OUT, @daySATURD  OUT, @daySUNDAY  OUT	
	
    IF CAST(DATEPART(weekday, @p_FECHAHOY) AS SMALLINT) IN (@dayTUESDA, @dayFRIDAY, @daySATURD) BEGIN
      SET @p_result = @freqTRUE;
    END
    ELSE BEGIN
      SET @p_result = @freqFALSE;
    END 
  END;
GO


  IF OBJECT_ID('WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadSemanalMiercoles', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadSemanalMiercoles;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadSemanalMiercoles(@p_FECHAHOY DATETIME, @p_result VARCHAR(4000) OUT) AS
  BEGIN
  
	DECLARE @freqTRUE  VARCHAR(5),@freqFALSE VARCHAR(5),@dayMONDAY SMALLINT,@dayTUESDA SMALLINT,@dayWEDNES SMALLINT,@dayTHURSD SMALLINT,@dayFRIDAY SMALLINT,@daySATURD SMALLINT,@daySUNDAY SMALLINT	
	EXEC WSXML_SFG.SFGPERIODICIDADPAGO_CONSTANT @freqTRUE   OUT, @freqFALSE  OUT, @dayMONDAY  OUT, @dayTUESDA  OUT, @dayWEDNES  OUT, @dayTHURSD  OUT, @dayFRIDAY  OUT, @daySATURD  OUT, @daySUNDAY  OUT	
	
    IF CAST(DATEPART(weekday, @p_FECHAHOY) AS SMALLINT) = @dayWEDNES BEGIN
      SET @p_result = @freqTRUE;
    END
    ELSE BEGIN
      SET @p_result = @freqFALSE;
    END 
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadSemanalViernes', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadSemanalViernes;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadSemanalViernes(@p_FECHAHOY DATETIME, @p_result VARCHAR(4000) OUT) AS
  BEGIN

	DECLARE @freqTRUE  VARCHAR(5),@freqFALSE VARCHAR(5),@dayMONDAY SMALLINT,@dayTUESDA SMALLINT,@dayWEDNES SMALLINT,@dayTHURSD SMALLINT,@dayFRIDAY SMALLINT,@daySATURD SMALLINT,@daySUNDAY SMALLINT	
	EXEC WSXML_SFG.SFGPERIODICIDADPAGO_CONSTANT @freqTRUE   OUT, @freqFALSE  OUT, @dayMONDAY  OUT, @dayTUESDA  OUT, @dayWEDNES  OUT, @dayTHURSD  OUT, @dayFRIDAY  OUT, @daySATURD  OUT, @daySUNDAY  OUT	
	
    IF CAST(DATEPART(weekday, @p_FECHAHOY) AS SMALLINT) = @dayFRIDAY BEGIN
      SET @p_result = @freqTRUE;
    END
    ELSE BEGIN
      SET @p_result = @freqFALSE;
    END 

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadSemanalSabado', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadSemanalSabado;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadSemanalSabado(@p_FECHAHOY DATETIME, @p_result VARCHAR(4000) OUT)  AS
  BEGIN

	DECLARE @freqTRUE  VARCHAR(5),@freqFALSE VARCHAR(5),@dayMONDAY SMALLINT,@dayTUESDA SMALLINT,@dayWEDNES SMALLINT,@dayTHURSD SMALLINT,@dayFRIDAY SMALLINT,@daySATURD SMALLINT,@daySUNDAY SMALLINT	
	EXEC WSXML_SFG.SFGPERIODICIDADPAGO_CONSTANT @freqTRUE   OUT, @freqFALSE  OUT, @dayMONDAY  OUT, @dayTUESDA  OUT, @dayWEDNES  OUT, @dayTHURSD  OUT, @dayFRIDAY  OUT, @daySATURD  OUT, @daySUNDAY  OUT	
	
    IF CAST(DATEPART(weekday, @p_FECHAHOY) AS SMALLINT) = @daySATURD BEGIN
      SET @p_result = @freqTRUE;
    END
    ELSE BEGIN
      SET @p_result = @freqFALSE;
    END 

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadSemanalLunes', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadSemanalLunes;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPERIODICIDADPAGO_PeriodicidadSemanalLunes(@p_FECHAHOY DATETIME, @p_result VARCHAR(4000) OUT) AS
  BEGIN
  
	DECLARE @freqTRUE  VARCHAR(5),@freqFALSE VARCHAR(5),@dayMONDAY SMALLINT,@dayTUESDA SMALLINT,@dayWEDNES SMALLINT,@dayTHURSD SMALLINT,@dayFRIDAY SMALLINT,@daySATURD SMALLINT,@daySUNDAY SMALLINT	
	EXEC WSXML_SFG.SFGPERIODICIDADPAGO_CONSTANT @freqTRUE   OUT, @freqFALSE  OUT, @dayMONDAY  OUT, @dayTUESDA  OUT, @dayWEDNES  OUT, @dayTHURSD  OUT, @dayFRIDAY  OUT, @daySATURD  OUT, @daySUNDAY  OUT	
	
    IF CAST(DATEPART(weekday, @p_FECHAHOY) AS SMALLINT) = @dayMONDAY BEGIN
      SET @p_result =  @freqTRUE;
    END
    ELSE BEGIN
      SET @p_result = @freqFALSE;
    END 
  END;
GO






