USE SFGPRODU;
--  DDL for Package Body SFGPUERTOTERMINAL
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGPUERTOTERMINAL */ 

  IF OBJECT_ID('WSXML_SFG.SFGPUERTOTERMINAL_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUERTOTERMINAL_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPUERTOTERMINAL_AddRecord(@p_NOMPUERTOTERMINAL      NVARCHAR(2000),
                      @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                      @p_ID_PUERTOTERMINAL_out  NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.PUERTOTERMINAL (
                                  NOMPUERTOTERMINAL,
                                  CODUSUARIOMODIFICACION)
    VALUES (
            @p_NOMPUERTOTERMINAL,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_PUERTOTERMINAL_out = SCOPE_IDENTITY();

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUERTOTERMINAL_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUERTOTERMINAL_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPUERTOTERMINAL_UpdateRecord(@pk_ID_PUERTOTERMINAL     NUMERIC(22,0),
                         @p_NOMPUERTOTERMINAL      NVARCHAR(2000),
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.PUERTOTERMINAL
       SET NOMPUERTOTERMINAL      = @p_NOMPUERTOTERMINAL,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = @p_ACTIVE
     WHERE ID_PUERTOTERMINAL      = @pk_ID_PUERTOTERMINAL;

    IF @@rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @@rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUERTOTERMINAL_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUERTOTERMINAL_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPUERTOTERMINAL_GetRecord(@pk_ID_PUERTOTERMINAL NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;

    SELECT @l_count = COUNT(*) FROM WSXML_SFG.PUERTOTERMINAL
     WHERE ID_PUERTOTERMINAL = @pk_ID_PUERTOTERMINAL;

    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

      SELECT ID_PUERTOTERMINAL,
             NOMPUERTOTERMINAL,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
      FROM WSXML_SFG.PUERTOTERMINAL
      WHERE ID_PUERTOTERMINAL = @pk_ID_PUERTOTERMINAL;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPUERTOTERMINAL_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPUERTOTERMINAL_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPUERTOTERMINAL_GetList(@p_active NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT ID_PUERTOTERMINAL,
             NOMPUERTOTERMINAL,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
      FROM WSXML_SFG.PUERTOTERMINAL
      WHERE ACTIVE = CASE WHEN @p_active = -1 THEN ACTIVE ELSE @p_active END;
  END;
GO






