USE SFGPRODU;
--  DDL for Package Body SFGPAGINA
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGPAGINA */ 

  IF OBJECT_ID('WSXML_SFG.SFGPAGINA_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPAGINA_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPAGINA_AddRecord(@p_NOMPAGINA              NVARCHAR(2000),
                      @p_URL                    NVARCHAR(2000),
                      @p_CODMODULO              NUMERIC(22,0),
                      @p_LLAVEPAGINA            NVARCHAR(2000),
                      @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                      @p_ID_PAGINA_out          NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.PAGINA (
                        NOMPAGINA,
                        URL,
                        CODMODULO,
                        LLAVEPAGINA,
                        CODUSUARIOMODIFICACION)
    VALUES (
            @p_NOMPAGINA,
            @p_URL,
            @p_CODMODULO,
            @p_LLAVEPAGINA,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_PAGINA_out = SCOPE_IDENTITY();
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPAGINA_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPAGINA_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPAGINA_UpdateRecord(@pk_ID_PAGINA             NUMERIC(22,0),
                         @p_NOMPAGINA              NVARCHAR(2000),
                         @p_URL                    NVARCHAR(2000),
                         @p_CODMODULO              NUMERIC(22,0),
                         @p_LLAVEPAGINA            NVARCHAR(2000),
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.PAGINA
       SET NOMPAGINA              = @p_NOMPAGINA,
           URL                    = @p_URL,
           CODMODULO              = @p_CODMODULO,
           LLAVEPAGINA            = @p_LLAVEPAGINA,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = @p_ACTIVE
     WHERE ID_PAGINA = @pk_ID_PAGINA;

    IF @@ROWCOUNT = 0 BEGIN
      RAISERROR('-20054 THE RECORD NO LONGER EXISTS.', 16, 1);
    END 
    IF @@ROWCOUNT > 1 BEGIN
      RAISERROR('-20053 DUPLICATE OBJECT INSTANCES.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPAGINA_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPAGINA_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPAGINA_GetRecord(@pk_ID_PAGINA NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.PAGINA WHERE ID_PAGINA = @pk_ID_PAGINA;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 THE RECORD NO LONGER EXISTS.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 DUPLICATE OBJECT INSTANCES.', 16, 1);
    END 

      SELECT ID_PAGINA,
             NOMPAGINA,
             URL,
             CODMODULO,
             LLAVEPAGINA,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.PAGINA
       WHERE ID_PAGINA = @pk_ID_PAGINA;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPAGINA_GetRecordByKey', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPAGINA_GetRecordByKey;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPAGINA_GetRecordByKey(@p_LLAVE NVARCHAR(2000)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.PAGINA WHERE LLAVEPAGINA = @p_LLAVE;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 THE RECORD NO LONGER EXISTS.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 DUPLICATE OBJECT INSTANCES.', 16, 1);
    END 

      SELECT P.ID_PAGINA,
             P.NOMPAGINA,
             P.URL,
             P.FECHAHORAMODIFICACION,
             P.CODUSUARIOMODIFICACION,
             P.ACTIVE,
             P.CODMODULO,
             M.NOMMODULO
      FROM WSXML_SFG.PAGINA P
      LEFT OUTER JOIN MODULO M
        ON (P.CODMODULO = M.ID_MODULO)
      WHERE P.LLAVEPAGINA = @p_LLAVE;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPAGINA_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPAGINA_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPAGINA_GetList(@p_ACTIVE NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT P.ID_PAGINA,
             P.NOMPAGINA,
             P.LLAVEPAGINA,
             P.URL,
             1 VER, 1 EDITAR, 1 BORRAR, 1 ADICIONAR,
             P.FECHAHORAMODIFICACION,
             P.CODUSUARIOMODIFICACION,
             P.ACTIVE,
             P.CODMODULO,
             M.NOMMODULO
        FROM WSXML_SFG.PAGINA P,WSXML_SFG.MODULO M
       WHERE CODMODULO=ID_MODULO
       AND P.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN P.ACTIVE ELSE @p_ACTIVE END
       ORDER BY M.ID_MODULO, P.ID_PAGINA;

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGPAGINA_GetPaginasForUser', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPAGINA_GetPaginasForUser;
GO
CREATE     PROCEDURE WSXML_SFG.SFGPAGINA_GetPaginasForUser(@p_CODUSUARIO NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT M.ID_MODULO, M.NOMMODULO,
             P.ID_PAGINA, P.NOMPAGINA, P.URL, P.LLAVEPAGINA
      FROM WSXML_SFG.PAGINA P
      LEFT OUTER JOIN MODULO M ON M.ID_MODULO = P.CODMODULO
      WHERE ID_PAGINA IN (SELECT P.ID_PAGINA FROM WSXML_SFG.ROLUSUARIO RU
                          LEFT OUTER JOIN ROL R ON R.ID_ROL = RU.CODROL
                          LEFT OUTER JOIN ROLPAGINA RP ON RP.CODROL = R.ID_ROL
                          LEFT OUTER JOIN PAGINA P ON P.ID_PAGINA = RP.CODPAGINA
                          WHERE RU.CODUSUARIO = @p_CODUSUARIO
                          AND P.ACTIVE = 1 AND R.ACTIVE = 1 AND RP.ACTIVE = 1 AND RU.ACTIVE = 1
                          GROUP BY P.ID_PAGINA)
      ORDER BY ID_MODULO, ID_PAGINA;
  END;
GO


IF OBJECT_ID('WSXML_SFG.SFGPAGINA_ComposeModulePath', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPAGINA_ComposeModulePath;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPAGINA_ComposeModulePath(@p_CODMODULO NUMERIC(22,0), 
                       @p_DELIMITER NVARCHAR(2000), @p_PATH NVARCHAR(2000) OUT)  AS
 BEGIN
    DECLARE @cNOMMODULO NVARCHAR(355) = '';
    DECLARE @cNIVEL NUMERIC(22,0);
   
  SET NOCOUNT ON;
    SELECT @cNIVEL = NIVEL, @cNOMMODULO = NOMMODULO FROM WSXML_SFG.MODULO WHERE ID_MODULO = @p_CODMODULO;

    IF @p_PATH IS NULL BEGIN
      SET @p_PATH = '';
    END 

    IF @cNOMMODULO IS NULL BEGIN
      SET @cNOMMODULO = '';
    END 

    SET @p_PATH = ISNULL(@cNOMMODULO, '') + ISNULL(@p_DELIMITER, '') + ISNULL(@p_PATH, '');
    IF @cNIVEL > 1 BEGIN
        DECLARE @cCODPADRE NUMERIC(22,0);
      BEGIN
        SELECT @cCODPADRE = PARENT FROM WSXML_SFG.MODULO WHERE ID_MODULO = @p_CODMODULO;
        /*
		ComposeModulePath(@cCODPADRE, @p_DELIMITER, @p_PATH);
      EXCEPTION WHEN NO_DATA_FOUND THEN
        NULL;
		*/
		EXEC WSXML_SFG.SFGPAGINA_ComposeModulePath @cCODPADRE, @p_DELIMITER, @p_PATH;
		IF(@@rowcount = 0)
		  BEGIN
		     SELECT NULL
          END
       END
     END
    END;
GO

IF OBJECT_ID('WSXML_SFG.SFGPAGINA_ComposePath', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGPAGINA_ComposePath;
GO

CREATE     PROCEDURE WSXML_SFG.SFGPAGINA_ComposePath(@p_LLAVE NVARCHAR(2000), @p_DELIMITER NVARCHAR(2000), 
                                                         @p_PATH NVARCHAR(2000) OUT)  AS
 BEGIN
    DECLARE @cCODMODULO NUMERIC(22,0);
    DECLARE @cNOMPAGINA NVARCHAR(1000);
   
  SET NOCOUNT ON;
    SET @p_PATH = '';
    SELECT @cCODMODULO = CODMODULO, @cNOMPAGINA = NOMPAGINA FROM WSXML_SFG.PAGINA WHERE LLAVEPAGINA = @p_LLAVE;
     EXEC WSXML_SFG.SFGPAGINA_ComposeModulePath @cCODMODULO, @p_DELIMITER, @p_PATH;
    SET @p_PATH = ISNULL(@p_PATH, '') + ISNULL(@cNOMPAGINA, '');
  END;
GO







