USE SFGPRODU;
--  DDL for Package Body SFGROLUSUARIO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGROLUSUARIO */ 

  IF OBJECT_ID('WSXML_SFG.SFGROLUSUARIO_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLUSUARIO_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGROLUSUARIO_AddRecord(@p_CODROL                 NUMERIC(22,0),
                      @p_CODUSUARIO             NUMERIC(22,0),
                      @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                      @p_ID_ROLUSUARIO_out      NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    -- Una sola pareja rol - usuario

    -- Un solo rol por usuario
    BEGIN
      UPDATE WSXML_SFG.ROLUSUARIO
         SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
             FECHAHORAMODIFICACION  = GETDATE(),
             ACTIVE                 = 0
       WHERE CODUSUARIO = @p_CODUSUARIO AND ACTIVE = 1;
    END;

    INSERT INTO WSXML_SFG.ROLUSUARIO ( CODROL, CODUSUARIO, CODUSUARIOMODIFICACION)
    VALUES (
              @p_CODROL,
              @p_CODUSUARIO,
              @p_CODUSUARIOMODIFICACION);
    SET @p_ID_ROLUSUARIO_out = SCOPE_IDENTITY();
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGROLUSUARIO_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLUSUARIO_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGROLUSUARIO_UpdateRecord(@pk_ID_ROLUSUARIO         NUMERIC(22,0),
                         @p_CODROL                 NUMERIC(22,0),
                         @p_CODUSUARIO             NUMERIC(22,0),
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0)) AS
 BEGIN
    DECLARE @cCODROLUSUARIO NUMERIC(22,0);
   
  SET NOCOUNT ON;
    -- Una sola pareja rol - usuario
    

    -- Un solo rol por usuario
    IF @p_ACTIVE = 1
      BEGIN
        SELECT @cCODROLUSUARIO = ID_ROLUSUARIO 
		FROM WSXML_SFG.ROLUSUARIO
        WHERE CODUSUARIO = @p_CODUSUARIO
			AND ACTIVE = 1
			AND ID_ROLUSUARIO <> @pk_ID_ROLUSUARIO;
		
		IF @@ROWCOUNT > 0 BEGIN
			IF @cCODROLUSUARIO > 0 BEGIN
			  UPDATE WSXML_SFG.ROLUSUARIO
				 SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
					 FECHAHORAMODIFICACION  = GETDATE(),
					 ACTIVE                 = 0
			   WHERE ID_ROLUSUARIO = @cCODROLUSUARIO;
			END
		END
	 
    END;


    -- Actualizar
    UPDATE WSXML_SFG.ROLUSUARIO
       SET CODROL                 = @p_CODROL,
           CODUSUARIO             = @p_CODUSUARIO,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = @p_ACTIVE
     WHERE ID_ROLUSUARIO = @pk_ID_ROLUSUARIO;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGROLUSUARIO_SetUsuario', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLUSUARIO_SetUsuario;
GO

CREATE     PROCEDURE WSXML_SFG.SFGROLUSUARIO_SetUsuario(@p_CODROL                 NUMERIC(22,0),
                       @p_CODUSUARIO             NUMERIC(22,0),
                       @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    -- Desactivar otros roles del usuario
    UPDATE WSXML_SFG.ROLUSUARIO
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE = 0
     WHERE CODUSUARIO = @p_CODUSUARIO;
      DECLARE @cCODROLUSUARIO NUMERIC(22,0);
    BEGIN
      SELECT @cCODROLUSUARIO = ID_ROLUSUARIO FROM WSXML_SFG.ROLUSUARIO
       WHERE CODROL = @p_CODROL
         AND CODUSUARIO = @p_CODUSUARIO;

		IF @@ROWCOUNT  = 0 BEGIN
			INSERT INTO WSXML_SFG.ROLUSUARIO (CODROL, CODUSUARIO, CODUSUARIOMODIFICACION)
			VALUES (@p_CODROL, @p_CODUSUARIO, @p_CODUSUARIOMODIFICACION);
		END ELSE BEGIN
		  IF @cCODROLUSUARIO > 0 BEGIN
			UPDATE WSXML_SFG.ROLUSUARIO
			   SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
				   FECHAHORAMODIFICACION  = GETDATE(),
				   ACTIVE = 1
			 WHERE ID_ROLUSUARIO = @cCODROLUSUARIO;
		  END 
		END
	  
    END;

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGROLUSUARIO_UnsetUsuario', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLUSUARIO_UnsetUsuario;
GO

CREATE     PROCEDURE WSXML_SFG.SFGROLUSUARIO_UnsetUsuario(@p_CODROL                 NUMERIC(22,0),
                         @p_CODUSUARIO             NUMERIC(22,0),
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      DECLARE @cCODROLUSUARIO NUMERIC(22,0);
    BEGIN
		SELECT @cCODROLUSUARIO = ID_ROLUSUARIO FROM WSXML_SFG.ROLUSUARIO
		WHERE CODROL = @p_CODROL
			AND CODUSUARIO = @p_CODUSUARIO;

		IF @@ROWCOUNT  > 0 BEGIN
      
			IF @cCODROLUSUARIO > 0 BEGIN
				UPDATE WSXML_SFG.ROLUSUARIO
				   SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
					   FECHAHORAMODIFICACION  = GETDATE(),
					   ACTIVE = 0
				 WHERE ID_ROLUSUARIO = @cCODROLUSUARIO;
			END 
		END
    END;
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGROLUSUARIO_DeactivateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLUSUARIO_DeactivateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGROLUSUARIO_DeactivateRecord(@pk_ID_ROLUSUARIO NUMERIC(22,0), @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.ROLUSUARIO
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = 0
     WHERE ID_ROLUSUARIO = @pk_ID_ROLUSUARIO;

	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT;
    IF @ROWCOUNT = 0 BEGIN
      RAISERROR('-20054 THE RECORD NO LONGER EXISTS.', 16, 1);
    END 
    IF @ROWCOUNT > 1 BEGIN
      RAISERROR('-20053 DUPLICATE OBJECT INSTANCES.', 16, 1);
    END 
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGROLUSUARIO_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLUSUARIO_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGROLUSUARIO_GetRecord(@pk_ID_ROLUSUARIO NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.ROLUSUARIO WHERE ID_ROLUSUARIO = @pk_ID_ROLUSUARIO;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 THE RECORD NO LONGER EXISTS.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 DUPLICATE OBJECT INSTANCES.', 16, 1);
    END 

      SELECT RU.ID_ROLUSUARIO,
             RU.CODROL,
             R.NOMROL,
             RU.CODUSUARIO,
             U.NOMUSUARIO,
             RU.FECHAHORAMODIFICACION,
             RU.CODUSUARIOMODIFICACION,
             RU.ACTIVE
      FROM WSXML_SFG.ROLUSUARIO RU
      LEFT OUTER JOIN WSXML_SFG.ROL R ON RU.CODROL = R.ID_ROL
      LEFT OUTER JOIN WSXML_SFG.USUARIO U ON RU.CODUSUARIO = U.ID_USUARIO
      WHERE ID_ROLUSUARIO = @pk_ID_ROLUSUARIO;
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGROLUSUARIO_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLUSUARIO_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGROLUSUARIO_GetList(@p_ACTIVE NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT RU.ID_ROLUSUARIO,
             RU.CODROL,
             R.NOMROL,
             RU.CODUSUARIO,
             U.NOMUSUARIO,
             RU.FECHAHORAMODIFICACION,
             RU.CODUSUARIOMODIFICACION,
             RU.ACTIVE
      FROM WSXML_SFG.ROLUSUARIO RU
      LEFT OUTER JOIN WSXML_SFG.ROL R ON RU.CODROL = R.ID_ROL
      LEFT OUTER JOIN WSXML_SFG.USUARIO U ON RU.CODUSUARIO = U.ID_USUARIO
      WHERE RU.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN RU.ACTIVE ELSE @p_ACTIVE END;

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGROLUSUARIO_GetListByRol', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLUSUARIO_GetListByRol;
GO
CREATE     PROCEDURE WSXML_SFG.SFGROLUSUARIO_GetListByRol(@p_ACTIVE NUMERIC(22,0), @p_CODROL NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT RU.ID_ROLUSUARIO,
             RU.CODROL,
             R.NOMROL,
             RU.CODUSUARIO,
             U.NOMBRE,
             U.NOMUSUARIO,
             U.EMAIL,
             RU.FECHAHORAMODIFICACION,
             RU.CODUSUARIOMODIFICACION,
             RU.ACTIVE
      FROM WSXML_SFG.ROLUSUARIO RU
      LEFT OUTER JOIN WSXML_SFG.ROL R ON RU.CODROL = R.ID_ROL
      LEFT OUTER JOIN WSXML_SFG.USUARIO U ON RU.CODUSUARIO = U.ID_USUARIO
      WHERE RU.CODROL = @p_CODROL
        AND RU.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN RU.ACTIVE ELSE @p_ACTIVE END
        AND U.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN U.ACTIVE ELSE @p_ACTIVE END;

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGROLUSUARIO_GetListByUsuario', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLUSUARIO_GetListByUsuario;
GO
CREATE     PROCEDURE WSXML_SFG.SFGROLUSUARIO_GetListByUsuario(@p_ACTIVE NUMERIC(22,0), @p_CODUSUARIO NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT RU.ID_ROLUSUARIO,
             RU.CODROL,
             R.NOMROL,
             RU.CODUSUARIO,
             U.NOMUSUARIO,
             RU.FECHAHORAMODIFICACION,
             RU.CODUSUARIOMODIFICACION,
             RU.ACTIVE
      FROM WSXML_SFG.ROLUSUARIO RU
      LEFT OUTER JOIN WSXML_SFG.ROL R ON RU.CODROL = R.ID_ROL
      LEFT OUTER JOIN WSXML_SFG.USUARIO U ON RU.CODUSUARIO = U.ID_USUARIO
      WHERE RU.CODUSUARIO = @p_CODUSUARIO
        AND RU.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN RU.ACTIVE ELSE @p_ACTIVE END
        AND R.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN R.ACTIVE ELSE @p_ACTIVE END;

  END;
GO


