USE SFGPRODU;
--  DDL for Package Body SFGRETENCIONREGFACTURACION
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGRETENCIONREGFACTURACION */ 

  IF OBJECT_ID('WSXML_SFG.SFGRETENCIONREGFACTURACION_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONREGFACTURACION_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONREGFACTURACION_AddRecord(@p_CODRETENCIONTRIBUTARIA       NUMERIC(22,0),
                      @p_CODENTRADAARCHIVOCONTROL     NUMERIC(22,0),
                      @p_CODREGISTROFACTURACION       NUMERIC(22,0),
                      @p_CODTIPOREGISTRO              NUMERIC(22,0),
                      @p_VALORRETENCION               FLOAT,
                      @p_CODUSUARIOMODIFICACION       NUMERIC(22,0),
                      @p_ID_RETENCIONREGFACTURACN_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.RETENCIONREGFACTURACION (
                                         CODRETENCIONTRIBUTARIA,
                                         CODENTRADAARCHIVOCONTROL,
                                         CODREGISTROFACTURACION,
                                         CODTIPOREGISTRO,
                                         VALORRETENCION,
                                         CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODRETENCIONTRIBUTARIA,
            @p_CODENTRADAARCHIVOCONTROL,
            @p_CODREGISTROFACTURACION,
            @p_CODTIPOREGISTRO,
            @p_VALORRETENCION,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_RETENCIONREGFACTURACN_out = SCOPE_IDENTITY();
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGRETENCIONREGFACTURACION_UpdateValue', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONREGFACTURACION_UpdateValue;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONREGFACTURACION_UpdateValue(@pk_ID_RETENCIONREGFACTURACION NUMERIC(22,0), @p_VALOR FLOAT) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.RETENCIONREGFACTURACION SET VALORRETENCION = @p_VALOR WHERE ID_RETENCIONREGFACTURACION = @pk_ID_RETENCIONREGFACTURACION;
  END;
GO






