USE SFGPRODU;
--  DDL for Package Body SFGRETENCIONTRIBUTARIAREGIMEN
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN */ 

  IF OBJECT_ID('WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_SetRetencion', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_SetRetencion;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_SetRetencion(@p_CODRETENCIONTRIBUTARIA       NUMERIC(22,0),
                         @p_CODCOMPANIA                  NUMERIC(22,0),
                         @p_CODREGIMEN                   NUMERIC(22,0),
                         @p_VALOR                        FLOAT,
                         @p_CODUSUARIOMODIFICACION       NUMERIC(22,0),
                         @p_ID_RETENCIONTRIBUTARIARE_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    SELECT @p_ID_RETENCIONTRIBUTARIARE_out = ID_RETENCIONTRIBUTARIAREGIMEN
    FROM WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN
    WHERE CODRETENCIONTRIBUTARIA = @p_CODRETENCIONTRIBUTARIA
      AND CODCOMPANIA            = @p_CODCOMPANIA
      AND CODREGIMEN             = @p_CODREGIMEN;
    UPDATE WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN SET VALOR                  = @p_VALOR,
                                          CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
                                          FECHAHORAMODIFICACION  = GETDATE()
    WHERE ID_RETENCIONTRIBUTARIAREGIMEN = @p_ID_RETENCIONTRIBUTARIARE_out;
  IF @@ROWCOUNT = 0 BEGIN
    INSERT INTO WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN (
                                            CODRETENCIONTRIBUTARIA,
                                            CODCOMPANIA,
                                            CODREGIMEN,
                                            VALOR,
                                            CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODRETENCIONTRIBUTARIA,
            @p_CODCOMPANIA,
            @p_CODREGIMEN,
            @p_VALOR,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_RETENCIONTRIBUTARIARE_out = SCOPE_IDENTITY();
	END
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_AddRecord(@p_CODREGIMEN                  NUMERIC(22,0),
                      @p_CODRETENCIONTRIBUTARIA      NUMERIC(22,0),
                      @p_VALOR                       NUMERIC(22,0),
                      @p_CODUSUARIOMODIFICACION      NUMERIC(22,0),
                      @p_ID_RETENCIONTRIBREGIMEN_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN (
                                            CODREGIMEN,
                                            CODRETENCIONTRIBUTARIA,
                                            VALOR,
                                            CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODREGIMEN,
            @p_CODRETENCIONTRIBUTARIA,
            @p_VALOR,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_RETENCIONTRIBREGIMEN_out = SCOPE_IDENTITY();

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_UpdateRecord(@pk_ID_RETENCIONTRIBREGIMEN NUMERIC(22,0),
                         @p_CODREGIMEN               NUMERIC(22,0),
                         @p_CODRETENCIONTRIBUTARIA   NUMERIC(22,0),
                         @p_VALOR                    NUMERIC(22,0),
                         @p_CODUSUARIOMODIFICACION   NUMERIC(22,0),
                         @p_ACTIVE                   NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;

    UPDATE WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN
       SET CODREGIMEN             = @p_CODREGIMEN,
           CODRETENCIONTRIBUTARIA = @p_CODRETENCIONTRIBUTARIA,
           VALOR                  = @p_VALOR,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = @p_ACTIVE
     WHERE ID_RETENCIONTRIBUTARIAREGIMEN = @pk_ID_RETENCIONTRIBREGIMEN;

    IF @@rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @@rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_DeactivateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_DeactivateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_DeactivateRecord(@pk_ID_RETENCIONTRIBREGIMEN NUMERIC(22,0),
                             @p_CODUSUARIOMODIFICACION   NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;

    UPDATE WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = 0
     WHERE ID_RETENCIONTRIBUTARIAREGIMEN = @pk_ID_RETENCIONTRIBREGIMEN;

    IF @@rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @@rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_GetRecord(@pk_ID_RETENCIONTRIBREGIMEN NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;

    SELECT @l_count = count(*) FROM WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN
     WHERE ID_RETENCIONTRIBUTARIAREGIMEN = @pk_ID_RETENCIONTRIBREGIMEN;

    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

      SELECT ID_RETENCIONTRIBUTARIAREGIMEN,
             CODREGIMEN,
             CODRETENCIONTRIBUTARIA,
             VALOR,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN
       WHERE ID_RETENCIONTRIBUTARIAREGIMEN = @pk_ID_RETENCIONTRIBREGIMEN;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_GetList(@p_active NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT ID_RETENCIONTRIBUTARIAREGIMEN,
             CODREGIMEN,
             CODRETENCIONTRIBUTARIA,
             VALOR,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN
       WHERE ACTIVE = CASE WHEN @p_active = -1 THEN ACTIVE ELSE @p_active END;

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_GetListByHeader', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_GetListByHeader;
GO
CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIAREGIMEN_GetListByHeader(@p_ACTIVE NUMERIC(22,0), @p_CODRETENCIONTRIBUTARIA NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT RTR.ID_RETENCIONTRIBUTARIAREGIMEN,
             RTR.CODREGIMEN,
             R.NOMREGIMEN,
             RTR.CODRETENCIONTRIBUTARIA,
             RTR.VALOR,
             RTR.FECHAHORAMODIFICACION,
             RTR.CODUSUARIOMODIFICACION,
             RTR.ACTIVE
        FROM WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN RTR
       LEFT OUTER JOIN WSXML_SFG.REGIMEN R
       ON (R.ID_REGIMEN = RTR.CODREGIMEN)
       WHERE RTR.CODRETENCIONTRIBUTARIA = @p_CODRETENCIONTRIBUTARIA

         AND RTR.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN RTR.ACTIVE ELSE @p_ACTIVE END;

  END;
GO






