USE SFGPRODU;
--  DDL for Package Body SFGREGISTROREVCOSTOCALCULADO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGREGISTROREVCOSTOCALCULADO */ 

  IF OBJECT_ID('WSXML_SFG.SFGREGISTROREVCOSTOCALCULADO_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGREGISTROREVCOSTOCALCULADO_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGREGISTROREVCOSTOCALCULADO_AddRecord(@p_CODREGISTROREVENUE           NUMERIC(22,0),
                      @p_CODCOSTOCALCULADO            NUMERIC(22,0),
                      @p_VALORCOSTO                   FLOAT,
                      @p_ID_REGISTROREVCOSTOCALCU_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.REGISTROREVCOSTOCALCULADO (
                                           CODREGISTROREVENUE,
                                           CODCOSTOCALCULADO,
                                           VALORCOSTO)
    VALUES (
            @p_CODREGISTROREVENUE,
            @p_CODCOSTOCALCULADO,
            @p_VALORCOSTO);
    SET @p_ID_REGISTROREVCOSTOCALCU_out = SCOPE_IDENTITY();
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGREGISTROREVCOSTOCALCULADO_AddReplaceRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGREGISTROREVCOSTOCALCULADO_AddReplaceRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGREGISTROREVCOSTOCALCULADO_AddReplaceRecord(@p_CODREGISTROREVENUE           NUMERIC(22,0),
                             @p_CODCOSTOCALCULADO            NUMERIC(22,0),
                             @p_VALORCOSTO                   FLOAT,
                             @p_ID_REGISTROREVCOSTOCALCU_out NUMERIC(22,0) OUT) AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT @p_ID_REGISTROREVCOSTOCALCU_out = ID_REGISTROREVCOSTOCALCULADO
    FROM WSXML_SFG.REGISTROREVCOSTOCALCULADO
    WHERE CODREGISTROREVENUE = @p_CODREGISTROREVENUE
		AND CODCOSTOCALCULADO  = @p_CODCOSTOCALCULADO;
	
	IF @@ROWCOUNT = 0 BEGIN
		INSERT INTO WSXML_SFG.REGISTROREVCOSTOCALCULADO (
											   CODREGISTROREVENUE,
											   CODCOSTOCALCULADO,
											   VALORCOSTO)
		VALUES (
				@p_CODREGISTROREVENUE,
				@p_CODCOSTOCALCULADO,
				@p_VALORCOSTO);
		SET @p_ID_REGISTROREVCOSTOCALCU_out = SCOPE_IDENTITY();
	END ELSE BEGIN

		UPDATE WSXML_SFG.REGISTROREVCOSTOCALCULADO SET VALORCOSTO = @p_VALORCOSTO
		WHERE ID_REGISTROREVCOSTOCALCULADO = @p_ID_REGISTROREVCOSTOCALCU_out;
	END
  
  
END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGREGISTROREVCOSTOCALCULADO_AddAppendRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGREGISTROREVCOSTOCALCULADO_AddAppendRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGREGISTROREVCOSTOCALCULADO_AddAppendRecord(@p_CODREGISTROREVENUE           NUMERIC(22,0),
                            @p_CODCOSTOCALCULADO            NUMERIC(22,0),
                            @p_VALORCOSTO                   FLOAT,
                            @p_ID_REGISTROREVCOSTOCALCU_out NUMERIC(22,0) OUT) AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT @p_ID_REGISTROREVCOSTOCALCU_out = ID_REGISTROREVCOSTOCALCULADO
    FROM WSXML_SFG.REGISTROREVCOSTOCALCULADO
    WHERE CODREGISTROREVENUE = @p_CODREGISTROREVENUE
		AND CODCOSTOCALCULADO  = @p_CODCOSTOCALCULADO;
	
	IF @@ROWCOUNT  = 0 BEGIN
		INSERT INTO WSXML_SFG.REGISTROREVCOSTOCALCULADO (
											   CODREGISTROREVENUE,
											   CODCOSTOCALCULADO,
											   VALORCOSTO)
		VALUES (
				@p_CODREGISTROREVENUE,
				@p_CODCOSTOCALCULADO,
				@p_VALORCOSTO);
		SET @p_ID_REGISTROREVCOSTOCALCU_out = SCOPE_IDENTITY();
	END ELSE BEGIN

		UPDATE WSXML_SFG.REGISTROREVCOSTOCALCULADO SET VALORCOSTO = VALORCOSTO + @p_VALORCOSTO
		WHERE ID_REGISTROREVCOSTOCALCULADO = @p_ID_REGISTROREVCOSTOCALCU_out;
	END


END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGREGISTROREVCOSTOCALCULADO_GetRecordValue', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGREGISTROREVCOSTOCALCULADO_GetRecordValue;
GO

CREATE     PROCEDURE WSXML_SFG.SFGREGISTROREVCOSTOCALCULADO_GetRecordValue(@p_CODREGISTROREVENUE NUMERIC(22,0),
                           @p_CODCOSTOCALCULADO  NUMERIC(22,0),
                           @p_VALORCOSTO         FLOAT OUT) AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT @p_VALORCOSTO = VALORCOSTO 
	FROM WSXML_SFG.REGISTROREVCOSTOCALCULADO
    WHERE CODREGISTROREVENUE = @p_CODREGISTROREVENUE 
		AND CODCOSTOCALCULADO = @p_CODCOSTOCALCULADO;
	
	IF @@ROWCOUNT = 0
		SET @p_VALORCOSTO = 0;
END;
GO
