USE SFGPRODU;
--  DDL for Package Body SFGROLPAGINA
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGROLPAGINA */ 

  IF OBJECT_ID('WSXML_SFG.SFGROLPAGINA_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLPAGINA_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGROLPAGINA_AddRecord(@p_CODROL                 NUMERIC(22,0),
                      @p_CODPAGINA              NUMERIC(22,0),
                      @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                      @p_ID_ROLPAGINA_out       NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    BEGIN
      -- Si ya existia desactivado, activar
      SELECT @p_ID_ROLPAGINA_out = ID_ROLPAGINA
        FROM WSXML_SFG.ROLPAGINA
       WHERE CODROL = @p_CODROL
         AND CODPAGINA = @p_CODPAGINA;
      UPDATE WSXML_SFG.ROLPAGINA
         SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
             FECHAHORAMODIFICACION  = GETDATE(),
             ACTIVE                 = 1
       WHERE ID_ROLPAGINA = @p_ID_ROLPAGINA_out;
    IF  @@ROWCOUNT = 0
      -- Ingresar
      INSERT INTO WSXML_SFG.ROLPAGINA ( CODROL, CODPAGINA, CODUSUARIOMODIFICACION)
      VALUES (
              @p_CODROL,
              @p_CODPAGINA,
              @p_CODUSUARIOMODIFICACION);
      SET @p_ID_ROLPAGINA_out = SCOPE_IDENTITY();
    END;

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGROLPAGINA_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLPAGINA_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGROLPAGINA_UpdateRecord(@pk_ID_ROLPAGINA          NUMERIC(22,0),
                         @p_CODROL                 NUMERIC(22,0),
                         @p_CODPAGINA              NUMERIC(22,0),
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0)) AS
 BEGIN
    DECLARE @cCODROLPAGINA NUMERIC(22,0);
   
  SET NOCOUNT ON;
    -- Si active = 1 y ya existe otro, desactivar el otro
    IF @p_ACTIVE = 1
      BEGIN
        SELECT @cCODROLPAGINA = ID_ROLPAGINA FROM WSXML_SFG.ROLPAGINA
         WHERE CODROL = @p_CODROL
           AND CODPAGINA = @p_CODPAGINA
           AND ACTIVE = 1
           AND ID_ROLPAGINA <> @pk_ID_ROLPAGINA;
        IF @cCODROLPAGINA > 0 BEGIN
          UPDATE WSXML_SFG.ROLPAGINA SET ACTIVE = 0 WHERE ID_ROLPAGINA = @cCODROLPAGINA;
        END 
		IF @@ROWCOUNT = 0
			SELECT NULL; -- Do nothing
      END;

    

    -- Actualizar
    UPDATE WSXML_SFG.ROLPAGINA
       SET CODROL                 = @p_CODROL,
           CODPAGINA              = @p_CODPAGINA,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = @p_ACTIVE
     WHERE ID_ROLPAGINA = @pk_ID_ROLPAGINA;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGROLPAGINA_SetPagina', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLPAGINA_SetPagina;
GO

CREATE     PROCEDURE WSXML_SFG.SFGROLPAGINA_SetPagina(@p_CODROL                 NUMERIC(22,0),
                      @p_CODPAGINA              NUMERIC(22,0),
                      @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      DECLARE @cCODROLPAGINA NUMERIC(22,0);
    BEGIN
      SELECT @cCODROLPAGINA = ID_ROLPAGINA FROM WSXML_SFG.ROLPAGINA
       WHERE CODROL = @p_CODROL
         AND CODPAGINA = @p_CODPAGINA;
      IF @cCODROLPAGINA > 0 BEGIN
        -- Activar el del rol
        UPDATE WSXML_SFG.ROLPAGINA
           SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
               FECHAHORAMODIFICACION  = GETDATE(),
               ACTIVE = 1
         WHERE ID_ROLPAGINA = @cCODROLPAGINA;
      END 
    IF @@ROWCOUNT = 0
      INSERT INTO WSXML_SFG.ROLPAGINA (
                             CODROL,
                             CODPAGINA,
                             CODUSUARIOMODIFICACION)
      VALUES (
              @p_CODROL,
              @p_CODPAGINA,
              @p_CODUSUARIOMODIFICACION);
    END;

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGROLPAGINA_UnsetPagina', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLPAGINA_UnsetPagina;
GO

CREATE     PROCEDURE WSXML_SFG.SFGROLPAGINA_UnsetPagina(@p_CODROL                 NUMERIC(22,0),
                        @p_CODPAGINA              NUMERIC(22,0),
                        @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      DECLARE @cCODROLPAGINA NUMERIC(22,0);
    BEGIN
      SELECT @cCODROLPAGINA = ID_ROLPAGINA FROM WSXML_SFG.ROLPAGINA
       WHERE CODROL = @p_CODROL
         AND CODPAGINA = @p_CODPAGINA;
      IF @cCODROLPAGINA > 0 BEGIN
        UPDATE WSXML_SFG.ROLPAGINA
           SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
               FECHAHORAMODIFICACION  = GETDATE(),
               ACTIVE = 0
         WHERE ID_ROLPAGINA = @cCODROLPAGINA;
      END 
    IF @@ROWCOUNT = 0
      SELECT NULL; -- No realizar operacion
    END;

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGROLPAGINA_DeactivateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLPAGINA_DeactivateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGROLPAGINA_DeactivateRecord(@pk_ID_ROLPAGINA NUMERIC(22,0), @p_CODUSUARIOMODIFICACION NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.ROLPAGINA
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = 0
     WHERE ID_ROLPAGINA = @pk_ID_ROLPAGINA;

    IF @@ROWCOUNT = 0 BEGIN
      RAISERROR('-20054 THE RECORD NO LONGER EXISTS.', 16, 1);
    END 
    IF @@ROWCOUNT > 1 BEGIN
      RAISERROR('-20053 DUPLICATE OBJECT INSTANCES.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGROLPAGINA_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLPAGINA_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGROLPAGINA_GetRecord(@pk_ID_ROLPAGINA NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.ROLPAGINA WHERE ID_ROLPAGINA = @pk_ID_ROLPAGINA;

    IF @l_count = 0 BEGIN
      RAISERROR('-20054 THE RECORD NO LONGER EXISTS.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 DUPLICATE OBJECT INSTANCES.', 16, 1);
    END 

      SELECT RP.ID_ROLPAGINA,
             RP.CODROL,
             R.NOMROL,
             RP.CODPAGINA,
             P.NOMPAGINA,
             M.NOMMODULO,
             RP.FECHAHORAMODIFICACION,
             RP.CODUSUARIOMODIFICACION,
             RP.ACTIVE
      FROM WSXML_SFG.ROLPAGINA RP
      LEFT OUTER JOIN WSXML_SFG.ROL R ON RP.CODROL = R.ID_ROL
      LEFT OUTER JOIN WSXML_SFG.PAGINA P ON RP.CODPAGINA = P.ID_PAGINA
      LEFT OUTER JOIN WSXML_SFG.MODULO M ON P.CODMODULO = M.ID_MODULO
      WHERE ID_ROLPAGINA = @pk_ID_ROLPAGINA;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGROLPAGINA_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLPAGINA_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGROLPAGINA_GetList(@p_ACTIVE NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT RP.ID_ROLPAGINA,
             RP.CODROL,
             R.NOMROL,
             RP.CODPAGINA,
             P.NOMPAGINA,
             1 VER, 1 EDITAR, 1 BORRAR, 1 ADICIONAR,
             M.NOMMODULO,
             RP.FECHAHORAMODIFICACION,
             RP.CODUSUARIOMODIFICACION,
             RP.ACTIVE
      FROM WSXML_SFG.ROLPAGINA RP
      LEFT OUTER JOIN WSXML_SFG.ROL R ON RP.CODROL = R.ID_ROL
      LEFT OUTER JOIN WSXML_SFG.PAGINA P ON RP.CODPAGINA = P.ID_PAGINA
      LEFT OUTER JOIN WSXML_SFG.MODULO M ON P.CODMODULO = M.ID_MODULO
      WHERE RP.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN RP.ACTIVE ELSE @p_ACTIVE END
      ORDER BY M.ID_MODULO, P.ID_PAGINA;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGROLPAGINA_GetListByRol', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLPAGINA_GetListByRol;
GO
CREATE     PROCEDURE WSXML_SFG.SFGROLPAGINA_GetListByRol(@p_ACTIVE NUMERIC(22,0), @p_CODROL NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT RP.ID_ROLPAGINA,
             RP.CODROL,
             R.NOMROL,
             RP.CODPAGINA,
             P.NOMPAGINA,
             1 VER, 1 EDITAR, 1 BORRAR, 1 ADICIONAR,
             M.NOMMODULO,
             RP.FECHAHORAMODIFICACION,
             RP.CODUSUARIOMODIFICACION,
             RP.ACTIVE
      FROM WSXML_SFG.ROLPAGINA RP
      LEFT OUTER JOIN WSXML_SFG.ROL R ON RP.CODROL = R.ID_ROL
      LEFT OUTER JOIN WSXML_SFG.PAGINA P ON RP.CODPAGINA = P.ID_PAGINA
      LEFT OUTER JOIN WSXML_SFG.MODULO M ON P.CODMODULO = M.ID_MODULO
      WHERE RP.CODROL = @p_CODROL
        AND RP.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN RP.ACTIVE ELSE @p_ACTIVE END
        AND P.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN P.ACTIVE ELSE @p_ACTIVE END
        AND M.ACTIVE = CASE WHEN @p_ACTIVE = 1 THEN M.ACTIVE ELSE @p_ACTIVE END
      ORDER BY ID_MODULO, ID_PAGINA;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGROLPAGINA_GetListByPagina', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGROLPAGINA_GetListByPagina;
GO
CREATE     PROCEDURE WSXML_SFG.SFGROLPAGINA_GetListByPagina(@p_ACTIVE NUMERIC(22,0), @p_CODPAGINA NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT RP.ID_ROLPAGINA,
             RP.CODROL,
             R.NOMROL,
             RP.CODPAGINA,
             P.NOMPAGINA,
             1 VER, 1 EDITAR, 1 BORRAR, 1 ADICIONAR,
             M.NOMMODULO,
             RP.FECHAHORAMODIFICACION,
             RP.CODUSUARIOMODIFICACION,
             RP.ACTIVE
      FROM WSXML_SFG.ROLPAGINA RP
      LEFT OUTER JOIN WSXML_SFG.ROL R ON RP.CODROL = R.ID_ROL
      LEFT OUTER JOIN WSXML_SFG.PAGINA P ON RP.CODPAGINA = P.ID_PAGINA
      LEFT OUTER JOIN WSXML_SFG.MODULO M ON P.CODMODULO = M.ID_MODULO
      WHERE RP.CODPAGINA = @p_CODPAGINA
        AND RP.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN RP.ACTIVE ELSE @p_ACTIVE END
        AND R.ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN R.ACTIVE ELSE @p_ACTIVE END;

  END;
GO






