USE SFGPRODU;
--  DDL for Package Body SFGRETENCIONTRIBUTARIA
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGRETENCIONTRIBUTARIA */ 

IF OBJECT_ID('WSXML_SFG.SFGRETENCIONTRIBUTARIA_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIA_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIA_AddRecord(@p_NOMRETENCIONTRIBUTARIA     NVARCHAR(2000),
                      @p_CODUSUARIOMODIFICACION     NUMERIC(22,0),
                      @p_ID_RETENCIONTRIBUTARIA_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.RETENCIONTRIBUTARIA
      (
       NOMRETENCIONTRIBUTARIA,
       CODUSUARIOMODIFICACION)
    VALUES
      (
       @p_NOMRETENCIONTRIBUTARIA,
       @p_CODUSUARIOMODIFICACION);
    SET @p_ID_RETENCIONTRIBUTARIA_out = SCOPE_IDENTITY();
  
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGRETENCIONTRIBUTARIA_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIA_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIA_UpdateRecord(@pk_ID_RETENCIONTRIBUTARIA NUMERIC(22,0),
                         @p_NOMRETENCIONTRIBUTARIA  NVARCHAR(2000),
                         @p_CODUSUARIOMODIFICACION  NUMERIC(22,0),
                         @p_ACTIVE                  NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
  
    UPDATE WSXML_SFG.RETENCIONTRIBUTARIA
       SET NOMRETENCIONTRIBUTARIA = @p_NOMRETENCIONTRIBUTARIA,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = @p_ACTIVE
     WHERE ID_RETENCIONTRIBUTARIA = @pk_ID_RETENCIONTRIBUTARIA;
  
	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT;
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGRETENCIONTRIBUTARIA_DeactivateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIA_DeactivateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIA_DeactivateRecord(@pk_ID_RETENCIONTRIBUTARIA NUMERIC(22,0),
                             @p_CODUSUARIOMODIFICACION  NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
  
    UPDATE WSXML_SFG.RETENCIONTRIBUTARIA
       SET CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = 0
     WHERE ID_RETENCIONTRIBUTARIA = @pk_ID_RETENCIONTRIBUTARIA;
	
	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT;
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  
  END;
GO


 IF OBJECT_ID('WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetRecord(@pk_ID_RETENCIONTRIBUTARIA NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
  
    SELECT @l_count = count(*)
      FROM WSXML_SFG.RETENCIONTRIBUTARIA
     WHERE ID_RETENCIONTRIBUTARIA = @pk_ID_RETENCIONTRIBUTARIA;
  
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

	  SELECT ID_RETENCIONTRIBUTARIA,
			 NOMRETENCIONTRIBUTARIA,
			 FECHAHORAMODIFICACION,
			 CODUSUARIOMODIFICACION,
			 ACTIVE
		FROM WSXML_SFG.RETENCIONTRIBUTARIA
	   WHERE ID_RETENCIONTRIBUTARIA = @pk_ID_RETENCIONTRIBUTARIA;

  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetList;
GO

CREATE     PROCEDURE WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetList(@p_active NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT R.ID_RETENCIONTRIBUTARIA,
             R.NOMRETENCIONTRIBUTARIA,
             R.FECHAHORAMODIFICACION,
             R.CODUSUARIOMODIFICACION,
             R.ACTIVE,
             COUNT(RT.ID_RETENCIONTRIBUTARIAREGIMEN) NUMREGIMENES
        FROM WSXML_SFG.RETENCIONTRIBUTARIA R
        LEFT OUTER JOIN WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN RT
          ON (RT.CODRETENCIONTRIBUTARIA = R.ID_RETENCIONTRIBUTARIA)
       WHERE R.ACTIVE = CASE WHEN @p_active = -1 THEN R.ACTIVE ELSE @p_active END
       GROUP BY R.ID_RETENCIONTRIBUTARIA,
                R.NOMRETENCIONTRIBUTARIA,
                R.FECHAHORAMODIFICACION,
                R.CODUSUARIOMODIFICACION,
                R.ACTIVE;

  END;
GO

  /* Retain Service logic to account for UVT driven taxes */

  /* Retain Service logic to account for UVT driven taxes */

IF EXISTS (
    SELECT * FROM sys.objects WHERE OBJECT_NAME(object_id) = N'SFGRETENCIONTRIBUTARIA_GetBillingTaxListByPOS'
    AND type IN (N'FN', N'IF', N'TF')
)
    DROP FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetBillingTaxListByPOS
GO


CREATE     FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetBillingTaxListByPOS(
									@p_CODPRODUCTO        NUMERIC(22,0),
									@p_CODCIUDAD          NUMERIC(22,0),
									@p_CODREGIMEN         NUMERIC(22,0),
									@p_CODCOMPANIA        NUMERIC(22,0),
									@p_CODTIPOPERSONATRIB NUMERIC(22,0),
									@p_CODTIPOCONTRATOPDV NUMERIC(22,0)
) RETURNS @lst_BILLINGTAXES_out TABLE (
		ID_RETENCIONTRIBUTARIA NUMERIC(38,0),
		VALOR FLOAT,
		CODBASERETENCION NUMERIC(38,0)
	)  AS --@lst_BILLINGTAXES_out
  BEGIN
	INSERT INTO @lst_BILLINGTAXES_out
    SELECT RTRB.ID_RETENCIONTRIBUTARIA, ISNULL(RRPE.VALOR, RETR.VALOR), ISNULL(RRPE.CODBASERETENCION, RTRB.CODBASERETENCION)
	FROM WSXML_SFG.RETENCIONTRIBUTARIA RTRB
		INNER JOIN WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN RETR
			ON (RETR.CODRETENCIONTRIBUTARIA     = RTRB.ID_RETENCIONTRIBUTARIA AND
			   RETR.CODCOMPANIA                 = @p_CODCOMPANIA AND
			   RETR.CODREGIMEN                  = @p_CODREGIMEN AND RETR.ACTIVE = 1 AND
			   RETR.CODTIPOGENERADORFACTURA     = 1 AND
			   RETR.CODTIPOPERSONATRIBUTARIA    = @p_CODTIPOPERSONATRIB AND
			   RETR.CODTIPOCONTRATOPDV          = @p_CODTIPOCONTRATOPDV )
     INNER JOIN WSXML_SFG.CIUDADRETENCION CRET ON (CRET.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND CRET.CODCIUDAD = @p_CODCIUDAD AND CRET.ACTIVE = 1)
     INNER JOIN WSXML_SFG.PRODUCTO PROD ON (PROD.ID_PRODUCTO = @p_CODPRODUCTO)
     INNER JOIN WSXML_SFG.TIPOPRODUCTO TPRD ON (TPRD.ID_TIPOPRODUCTO = PROD.CODTIPOPRODUCTO)
     INNER JOIN WSXML_SFG.RETENCIONLINEADENEGOCIO RLDN ON (RLDN.CODLINEADENEGOCIO = TPRD.CODLINEADENEGOCIO AND
            RLDN.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND 
            RLDN.CODTIPOCONTRATOPDV = @p_CODTIPOCONTRATOPDV)
      LEFT OUTER JOIN WSXML_SFG.RETENCIONREGIMENPRODEXCEP RRPE ON (RRPE.CODPRODUCTO = @p_CODPRODUCTO AND
           RRPE.CODCOMPANIA = @p_CODCOMPANIA AND
           RRPE.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
           RRPE.CODREGIMEN = @p_CODREGIMEN AND RRPE.ACTIVE = 1);
	RETURN
  END;
GO





IF EXISTS (
    SELECT * FROM sys.objects WHERE OBJECT_NAME(object_id) = N'SFGRETENCIONTRIBUTARIA_GetBillingTaxListByPOSDiferido'
    AND type IN (N'FN', N'IF', N'TF')
)
    DROP FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetBillingTaxListByPOSDiferido
GO

CREATE     FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetBillingTaxListByPOSDiferido(
											@p_CODPRODUCTO        NUMERIC(22,0),
											@p_CODCIUDAD          NUMERIC(22,0),
											@p_CODREGIMEN         NUMERIC(22,0),
											@p_CODTIPOPERSONATRIB NUMERIC(22,0)
                                           /*p_CODCOMPANIA        NUMBER,*/
                                           ) 
	RETURNS @lst_BILLINGTAXES_out TABLE (
		ID_RETENCIONTRIBUTARIA NUMERIC(38,0),
		VALOR FLOAT,
		CODBASERETENCION NUMERIC(38,0)
	)  AS --@lst_BILLINGTAXES_out
  BEGIN
	INSERT INTO @lst_BILLINGTAXES_out
    SELECT RTRB.ID_RETENCIONTRIBUTARIA, RETR.VALOR, RTRB.CODBASERETENCION

    FROM WSXML_SFG.RETENCIONTRIBUTARIA RTRB
		INNER JOIN WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN RETR
        ON (RETR.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
           /*          RETR.CODCOMPANIA = p_CODCOMPANIA AND*/
           RETR.CODREGIMEN = @p_CODREGIMEN AND RETR.ACTIVE = 1 AND
           RETR.CODTIPOGENERADORFACTURA = 3 AND
           RETR.CODTIPOPERSONATRIBUTARIA = @p_CODTIPOPERSONATRIB)
     INNER JOIN WSXML_SFG.CIUDADRETENCION CRET
        ON (CRET.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
           CRET.CODCIUDAD = @p_CODCIUDAD AND CRET.ACTIVE = 1)
     INNER JOIN WSXML_SFG.PRODUCTO PROD
        ON RETR.CODCOMPANIA = PROD.CODCOMPANIA
       AND (PROD.ID_PRODUCTO = @p_CODPRODUCTO)
     INNER JOIN TIPOPRODUCTO TPRD
        ON (TPRD.ID_TIPOPRODUCTO = PROD.CODTIPOPRODUCTO)
     INNER JOIN WSXML_SFG.RETENCIONLINEADENEGOCIO RLDN
        ON (RLDN.CODLINEADENEGOCIO = TPRD.CODLINEADENEGOCIO AND
           RLDN.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA);
	RETURN
  END;
GO

IF EXISTS (
    SELECT * FROM sys.objects WHERE OBJECT_NAME(object_id) = N'SFGRETENCIONTRIBUTARIA_GetExcludedTaxListByPOS'
    AND type IN (N'FN', N'IF', N'TF')
)
    DROP FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetExcludedTaxListByPOS
GO

CREATE     FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetExcludedTaxListByPOS(@p_CODPRODUCTO        NUMERIC(22,0),
                                    @p_CODCIUDAD          NUMERIC(22,0),
                                    @p_CODREGIMEN         NUMERIC(22,0),
                                    @p_CODCOMPANIA        NUMERIC(22,0)
	)RETURNS @lst_BILLINGTAXES_out TABLE (
		ID_RETENCIONTRIBUTARIA NUMERIC(38,0),
		VALOR FLOAT,
		CODBASERETENCION NUMERIC(38,0)
	)  AS --@lst_BILLINGTAXES_out
  BEGIN

	INSERT INTO @lst_BILLINGTAXES_out
    SELECT RTRB.ID_RETENCIONTRIBUTARIA, ISNULL(RETR.VALOR, 0), RTRB.CODBASERETENCION
    FROM WSXML_SFG.RETENCIONTRIBUTARIA RTRB
    -- Inner on Product Tree. Only available through billing
		INNER JOIN WSXML_SFG.PRODUCTO PROD ON (PROD.ID_PRODUCTO = @p_CODPRODUCTO)
		INNER JOIN WSXML_SFG.TIPOPRODUCTO TPRD ON (TPRD.ID_TIPOPRODUCTO = PROD.CODTIPOPRODUCTO)
		INNER JOIN WSXML_SFG.RETENCIONLINEADENEGOCIO RLDN ON (RLDN.CODLINEADENEGOCIO = TPRD.CODLINEADENEGOCIO AND
           RLDN.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA)
    -- Inner on Geography. Cannot reverse a city change
		INNER JOIN WSXML_SFG.CIUDADRETENCION CRET ON (CRET.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
           CRET.CODCIUDAD = @p_CODCIUDAD AND CRET.ACTIVE = 1)
    -- Left on Regimen
		LEFT OUTER JOIN WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN RETR ON (RETR.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
           RETR.CODCOMPANIA = @p_CODCOMPANIA AND
           RETR.CODREGIMEN = @p_CODREGIMEN AND RETR.ACTIVE = 1 and
           retr.codtipogeneradorfactura = 1);
	RETURN
  END;
GO

IF EXISTS (
    SELECT * FROM sys.objects WHERE OBJECT_NAME(object_id) = N'SFGRETENCIONTRIBUTARIA_GetBillingTaxListByProduct'
    AND type IN (N'FN', N'IF', N'TF')
)
    DROP FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetBillingTaxListByProduct
GO


CREATE     FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetBillingTaxListByProduct(@p_CODALIADOESTRATEGICO NUMERIC(22,0),
                                       @p_CODCIUDADPDV         NUMERIC(22,0),
                                       @p_CODREGIMEN           NUMERIC(22,0)) 
	RETURNS @lst_BILLINGTAXES_out TABLE (
		ID_RETENCIONTRIBUTARIA NUMERIC(38,0),
		VALOR FLOAT,
		CODBASERETENCION NUMERIC(38,0)
	)  AS --@lst_BILLINGTAXES_out
  BEGIN
	INSERT INTO @lst_BILLINGTAXES_out
    SELECT RTRB.ID_RETENCIONTRIBUTARIA, RETA.VALOR, RTRB.CODBASERETENCION
    FROM WSXML_SFG.RETENCIONTRIBUTARIA RTRB
		INNER JOIN WSXML_SFG.ALIADOESTRATEGICO ALIA ON (ALIA.ID_ALIADOESTRATEGICO = @p_CODALIADOESTRATEGICO)
		INNER JOIN WSXML_SFG.RETENCIONALIADOESTRATEGICO RETA ON (RETA.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
           RETA.CODALIADOESTRATEGICO = ALIA.ID_ALIADOESTRATEGICO)
	WHERE ALIA.CODCIUDAD = CASE
             WHEN RTRB.RESTRICCIONREGIONAL = 1 THEN @p_CODCIUDADPDV  ELSE ALIA.CODCIUDAD END
       AND RTRB.ID_RETENCIONTRIBUTARIA NOT IN
           (SELECT CODRETENCIONTRIBUTARIA
              FROM RETENCIONALIADOEXCEPCION
             WHERE CODREGIMEN = @p_CODREGIMEN);
	RETURN 
  END;
GO


IF EXISTS (
    SELECT * FROM sys.objects WHERE OBJECT_NAME(object_id) = N'SFGRETENCIONTRIBUTARIA_GetExcludedTaxListByProduct'
    AND type IN (N'FN', N'IF', N'TF')
)
    DROP FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetExcludedTaxListByProduct
GO

CREATE     FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetExcludedTaxListByProduct(@p_CODALIADOESTRATEGICO NUMERIC(22,0),
                                        @p_CODCIUDADPDV         NUMERIC(22,0),
                                        @p_CODREGIMEN           NUMERIC(22,0)) 
	RETURNS @lst_BILLINGTAXES_out TABLE (
		ID_RETENCIONTRIBUTARIA NUMERIC(38,0),
		VALOR FLOAT,
		CODBASERETENCION NUMERIC(38,0)
	)  AS --@lst_BILLINGTAXES_out
  BEGIN
	INSERT  INTO @lst_BILLINGTAXES_out
    SELECT RTRB.ID_RETENCIONTRIBUTARIA, ISNULL(RETA.VALOR, 0), RTRB.CODBASERETENCION
    FROM WSXML_SFG.RETENCIONTRIBUTARIA RTRB
		INNER JOIN WSXML_SFG.ALIADOESTRATEGICO ALIA ON (ALIA.ID_ALIADOESTRATEGICO = @p_CODALIADOESTRATEGICO)
    -- Left on matrix. May not be configured
      LEFT OUTER JOIN WSXML_SFG.RETENCIONALIADOESTRATEGICO RETA ON (RETA.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
           RETA.CODALIADOESTRATEGICO = ALIA.ID_ALIADOESTRATEGICO)
     WHERE ALIA.CODCIUDAD = CASE WHEN RTRB.RESTRICCIONREGIONAL = 1 THEN @p_CODCIUDADPDV ELSE ALIA.CODCIUDAD END
       AND RTRB.ID_RETENCIONTRIBUTARIA NOT IN
           (SELECT CODRETENCIONTRIBUTARIA
              FROM WSXML_SFG.RETENCIONALIADOEXCEPCION
             WHERE CODREGIMEN = @p_CODREGIMEN);
	RETURN 
  END;
GO


IF EXISTS (
    SELECT * FROM sys.objects WHERE OBJECT_NAME(object_id) = N'SFGRETENCIONTRIBUTARIA_GetBillingTaxListFromRegistry'
    AND type IN (N'FN', N'IF', N'TF')
)
    DROP FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetBillingTaxListFromRegistry
GO

CREATE     FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetBillingTaxListFromRegistry(@p_CODTIPOCONTRATOPDV     NUMERIC(22,0),
                                          @p_CODREGISTROFACTURACION NUMERIC(22,0),
                                          @p_CODTIPOPERSONATRIB     NUMERIC(22,0)) 
										  
	RETURNS @lst_BILLINGTAXES_out TABLE (
		ID_RETENCIONTRIBUTARIA NUMERIC(38,0),
		VALOR FLOAT,
		CODBASERETENCION NUMERIC(38,0)
	)  AS --@lst_BILLINGTAXES_out									  
  BEGIN
	
    IF @p_CODTIPOCONTRATOPDV IN (1, 2) BEGIN
      -- Contratos de Administracion o Arriendo buscan retenciones por producto
		INSERT INTO @lst_BILLINGTAXES_out
		SELECT RTRB.ID_RETENCIONTRIBUTARIA,RETR.VALOR, RTRB.CODBASERETENCION
        FROM WSXML_SFG.REGISTROFACTURACION REGF
			INNER JOIN WSXML_SFG.RETENCIONREGFACTURACION RTRG ON (RTRG.CODREGISTROFACTURACION = REGF.ID_REGISTROFACTURACION)
			INNER JOIN WSXML_SFG.RETENCIONTRIBUTARIA RTRB ON (RTRB.ID_RETENCIONTRIBUTARIA = RTRG.CODRETENCIONTRIBUTARIA)
			INNER JOIN WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN RETR ON (RETR.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
             RETR.CODCOMPANIA = REGF.CODCOMPANIA AND
             RETR.CODREGIMEN = REGF.CODREGIMEN and
             retr.codtipogeneradorfactura = 1 and
             retr.codtipopersonatributaria = @p_CODTIPOPERSONATRIB)
		WHERE REGF.ID_REGISTROFACTURACION = @p_CODREGISTROFACTURACION;
    END
    ELSE IF @p_CODTIPOCONTRATOPDV = 3 BEGIN
	
		INSERT INTO @lst_BILLINGTAXES_out
		SELECT RTRB.ID_RETENCIONTRIBUTARIA, RALE.VALOR, RTRB.CODBASERETENCION
        FROM WSXML_SFG.REGISTROFACTURACION REGF
			INNER JOIN WSXML_SFG.RETENCIONREGFACTURACION RTRG ON (RTRG.CODREGISTROFACTURACION = REGF.ID_REGISTROFACTURACION)
			INNER JOIN WSXML_SFG.PRODUCTO PROD ON (PROD.ID_PRODUCTO = REGF.CODPRODUCTO)
			INNER JOIN WSXML_SFG.ALIADOESTRATEGICO ALIA ON (ALIA.ID_ALIADOESTRATEGICO = PROD.CODALIADOESTRATEGICO)
			INNER JOIN WSXML_SFG.RETENCIONTRIBUTARIA RTRB ON (RTRB.ID_RETENCIONTRIBUTARIA = RTRG.CODRETENCIONTRIBUTARIA)
			INNER JOIN WSXML_SFG.RETENCIONALIADOESTRATEGICO RALE ON (RALE.CODRETENCIONTRIBUTARIA = RTRG.CODRETENCIONTRIBUTARIA AND
				RALE.CODALIADOESTRATEGICO = ALIA.ID_ALIADOESTRATEGICO)
		WHERE REGF.ID_REGISTROFACTURACION = @p_CODREGISTROFACTURACION;
    END
	RETURN
END;
GO

IF EXISTS (
    SELECT * FROM sys.objects WHERE OBJECT_NAME(object_id) = N'SFGRETENCIONTRIBUTARIA_GetBillingRetentionListByProdu'
    AND type IN (N'FN', N'IF', N'TF')
)
    DROP FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetBillingRetentionListByProdu
GO


CREATE     FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetBillingRetentionListByProdu(@p_CODPRODUCTO        NUMERIC(22,0),
                                           @p_CODCIUDAD          NUMERIC(22,0),
                                           @p_CODREGIMEN         NUMERIC(22,0),
                                           @p_CODCOMPANIA        NUMERIC(22,0))
	RETURNS @lst_BILLINGTAXES_out TABLE (
		ID_RETENCIONTRIBUTARIA NUMERIC(38,0),
		VALOR FLOAT,
		CODBASERETENCION NUMERIC(38,0)
	)  AS --@lst_BILLINGTAXES_out									   
  BEGIN

  
	INSERT INTO  @lst_BILLINGTAXES_out
    SELECT RTRB.ID_RETENCIONTRIBUTARIA, RETR.VALOR,PROD.CODBASERETENCION
    FROM WSXML_SFG.RETENCIONTRIBUTARIA RTRB
		INNER JOIN WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN RETR ON (RETR.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
			RETR.CODCOMPANIA = @p_CODCOMPANIA --4
			AND RETR.CODREGIMEN = @p_CODREGIMEN --4
			AND RETR.ACTIVE = 1 AND RETR.CODTIPOGENERADORFACTURA = 3)
		INNER JOIN WSXML_SFG.CIUDADRETENCION CRET
			ON (CRET.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
				CRET.CODCIUDAD = @p_CODCIUDAD --111 
				AND CRET.ACTIVE = 1)
		INNER JOIN WSXML_SFG.RETENCIONPRODUCTO PROD ON (RTRB.ID_RETENCIONTRIBUTARIA = PROD.CODRETENCIONTRIBUTARIA AND
           PROD.CODPRODUCTO = @p_CODPRODUCTO --1611 
           AND PROD.ACTIVE = 1);
	RETURN
  END;
GO

IF EXISTS (
    SELECT * FROM sys.objects WHERE OBJECT_NAME(object_id) = N'SFGRETENCIONTRIBUTARIA_GetRetencionValue'
    AND type IN (N'FN', N'IF', N'TF')
)
    DROP FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetRetencionValue
GO

CREATE     FUNCTION WSXML_SFG.SFGRETENCIONTRIBUTARIA_GetRetencionValue(@p_CODTIPOCONTRATOPDV     NUMERIC(22,0),
                             @p_CODPRODUCTO            NUMERIC(22,0),
                             @p_CODALIADOESTRATEGICO   NUMERIC(22,0),
                             @p_CODCIUDAD              NUMERIC(22,0),
                             @p_CODREGIMEN             NUMERIC(22,0),
                             @p_CODCOMPANIA            NUMERIC(22,0),
                             @p_CODTIPOPERSONATRIB     NUMERIC(22,0),
                             @p_CODRETENCIONTRIBUTARIA NUMERIC(22,0)) RETURNS NUMERIC(22,0) AS
 BEGIN
    DECLARE @v_VALORRETENCION NUMERIC(22,0);
   
  
    IF @p_CODTIPOCONTRATOPDV IN (1, 2) BEGIN
    
      SELECT @v_VALORRETENCION = ISNULL(RRPE.VALOR, RETR.VALOR)
        FROM WSXML_SFG.RETENCIONTRIBUTARIA RTRB
       INNER JOIN WSXML_SFG.RETENCIONTRIBUTARIAREGIMEN RETR
          ON (RETR.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
             RETR.CODCOMPANIA = @p_CODCOMPANIA AND
             RETR.CODREGIMEN = @p_CODREGIMEN AND RETR.ACTIVE = 1 AND
             RETR.CODTIPOGENERADORFACTURA = 1 AND
             RETR.CODTIPOPERSONATRIBUTARIA = @p_CODTIPOPERSONATRIB)
       INNER JOIN WSXML_SFG.CIUDADRETENCION CRET
          ON (CRET.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
             CRET.CODCIUDAD = @p_CODCIUDAD AND CRET.ACTIVE = 1)
       INNER JOIN WSXML_SFG.PRODUCTO PROD
          ON (PROD.ID_PRODUCTO = @p_CODPRODUCTO)
       INNER JOIN WSXML_SFG.TIPOPRODUCTO TPRD
          ON (TPRD.ID_TIPOPRODUCTO = PROD.CODTIPOPRODUCTO)
       INNER JOIN WSXML_SFG.RETENCIONLINEADENEGOCIO RLDN
          ON (RLDN.CODLINEADENEGOCIO = TPRD.CODLINEADENEGOCIO AND
             RLDN.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA)
        LEFT OUTER JOIN WSXML_SFG.RETENCIONREGIMENPRODEXCEP RRPE
          ON (RRPE.CODPRODUCTO = @p_CODPRODUCTO AND
             RRPE.CODCOMPANIA = @p_CODCOMPANIA AND
             RRPE.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
             RRPE.CODREGIMEN = @p_CODREGIMEN AND RRPE.ACTIVE = 1)
       WHERE RTRB.ID_RETENCIONTRIBUTARIA = @p_CODRETENCIONTRIBUTARIA;
    END
    ELSE BEGIN
    
      SELECT @v_VALORRETENCION = RETA.VALOR
        FROM WSXML_SFG.RETENCIONTRIBUTARIA RTRB
       INNER JOIN WSXML_SFG.ALIADOESTRATEGICO ALIA
          ON (ALIA.ID_ALIADOESTRATEGICO = @p_CODALIADOESTRATEGICO)
       INNER JOIN WSXML_SFG.RETENCIONALIADOESTRATEGICO RETA
          ON (RETA.CODRETENCIONTRIBUTARIA = RTRB.ID_RETENCIONTRIBUTARIA AND
             RETA.CODALIADOESTRATEGICO = ALIA.ID_ALIADOESTRATEGICO)
       WHERE ALIA.CODCIUDAD = CASE
               WHEN RTRB.RESTRICCIONREGIONAL = 1 THEN
                @p_CODCIUDAD
               ELSE
                ALIA.CODCIUDAD
             END
         AND RTRB.ID_RETENCIONTRIBUTARIA NOT IN
             (SELECT CODRETENCIONTRIBUTARIA
                FROM WSXML_SFG.RETENCIONALIADOEXCEPCION
               WHERE CODREGIMEN = @p_CODREGIMEN)
         AND RTRB.ID_RETENCIONTRIBUTARIA = @p_CODRETENCIONTRIBUTARIA;
    END 
  return isnull(@v_VALORRETENCION,0);
  END;

