USE SFGPRODU;
--  DDL for Package Body SFGSALDOCICLOFACTURACIONPDV
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGSALDOCICLOFACTURACIONPDV */ 

IF OBJECT_ID('WSXML_SFG.SFGSALDOCICLOFACTURACIONPDV_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGSALDOCICLOFACTURACIONPDV_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGSALDOCICLOFACTURACIONPDV_AddRecord(@p_CODCICLOFACTURACIONPDV       NUMERIC(22,0),
                      @p_CODDETALLESALDOPDV           NUMERIC(22,0),
                      @p_CODUSUARIOMODIFICACION       NUMERIC(22,0),
                      @p_ID_SALDOCICLOFACTURACION_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;

    INSERT INTO WSXML_SFG.SALDOCICLOFACTURACIONPDV (
                                            CODCICLOFACTURACIONPDV,
                                            CODDETALLESALDOPDV,
                                            CODUSUARIOMODIFICACION)
    VALUES (
            @p_CODCICLOFACTURACIONPDV,
            @p_CODDETALLESALDOPDV,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_SALDOCICLOFACTURACION_out = SCOPE_IDENTITY();

  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGSALDOCICLOFACTURACIONPDV_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGSALDOCICLOFACTURACIONPDV_UpdateRecord;
GO


CREATE PROCEDURE WSXML_SFG.SFGSALDOCICLOFACTURACIONPDV_UpdateRecord(@pk_ID_SALDOCICLOFACTURACION NUMERIC(22,0),
                         @p_CODCICLOFACTURACIONPDV    NUMERIC(22,0),
                         @p_CODDETALLESALDOPDV        NUMERIC(22,0),
                         @p_CODUSUARIOMODIFICACION    NUMERIC(22,0),
                         @p_ACTIVE                    NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;

    UPDATE WSXML_SFG.SALDOCICLOFACTURACIONPDV
       SET CODCICLOFACTURACIONPDV      = @p_CODCICLOFACTURACIONPDV,
           CODDETALLESALDOPDV          = @p_CODDETALLESALDOPDV,
           CODUSUARIOMODIFICACION      = @p_CODUSUARIOMODIFICACION,
           ACTIVE                      = @p_ACTIVE
     WHERE ID_SALDOCICLOFACTURACIONPDV = @pk_ID_SALDOCICLOFACTURACION;

	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT;
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

  END;
GO


IF OBJECT_ID('WSXML_SFG.SFGSALDOCICLOFACTURACIONPDV_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGSALDOCICLOFACTURACIONPDV_GetRecord;
GO

CREATE PROCEDURE WSXML_SFG.SFGSALDOCICLOFACTURACIONPDV_GetRecord(@pk_ID_SALDOCICLOFACTURACION NUMERIC(22,0)
                                                                 ) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;

    SELECT @l_count = count(*) FROM WSXML_SFG.SALDOCICLOFACTURACIONPDV
    WHERE ID_SALDOCICLOFACTURACIONPDV = @pk_ID_SALDOCICLOFACTURACION;

    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
	 
      SELECT ID_SALDOCICLOFACTURACIONPDV,
             CODCICLOFACTURACIONPDV,
             CODDETALLESALDOPDV,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.SALDOCICLOFACTURACIONPDV
       WHERE ID_SALDOCICLOFACTURACIONPDV = @pk_ID_SALDOCICLOFACTURACION;
	   
  END;
GO


IF OBJECT_ID('WSXML_SFG.SFGSALDOCICLOFACTURACIONPDV_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGSALDOCICLOFACTURACIONPDV_GetList;
GO

CREATE PROCEDURE WSXML_SFG.SFGSALDOCICLOFACTURACIONPDV_GetList(@p_active NUMERIC(22,0)
                                                               ) AS
  BEGIN
  SET NOCOUNT ON;
  
      SELECT ID_SALDOCICLOFACTURACIONPDV,
             CODCICLOFACTURACIONPDV,
             CODDETALLESALDOPDV,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.SALDOCICLOFACTURACIONPDV
       WHERE ACTIVE = CASE WHEN @p_active = -1 THEN ACTIVE ELSE @p_active END;
       
  END;
GO






