USE SFGPRODU;
--  DDL for Package Body SFGSORTEO_L1LIAB01
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGSORTEO_L1LIAB01 */ 

  --Add Record in the table SORTEO_L1LIAB01
  IF OBJECT_ID('WSXML_SFG.SFGSORTEO_L1LIAB01_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGSORTEO_L1LIAB01_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGSORTEO_L1LIAB01_AddRecord(@p_COD_CONTROL_L1LIAB01   NUMERIC(22,0),
					  @p_SORTEO                 NUMERIC(22,0),
					  @p_FECHAHORAMODIFICACION  DATETIME,
					  @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
					  @p_ACTIVE                 NUMERIC(22,0),
					  @p_ID_SORTEO_L1LIAB01_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.SORTEO_L1LIAB01 (
								 COD_CONTROL_L1LIAB01,
								 SORTEO,
								 FECHAHORAMODIFICACION,
								 CODUSUARIOMODIFICACION,
								 ACTIVE)
    VALUES (
			@p_COD_CONTROL_L1LIAB01,
			@p_SORTEO,
			@p_FECHAHORAMODIFICACION,
			@p_CODUSUARIOMODIFICACION,
			@p_ACTIVE);
    SET @p_ID_SORTEO_L1LIAB01_out = SCOPE_IDENTITY();
  END;
GO

  --Find Record on the table SORTEO_L1LIAB01
  IF OBJECT_ID('WSXML_SFG.SFGSORTEO_L1LIAB01_FindRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGSORTEO_L1LIAB01_FindRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGSORTEO_L1LIAB01_FindRecord(@p_COD_CONTROL_L1LIAB01   NUMERIC(22,0),
					  @p_SORTEO                 NUMERIC(22,0),
					  @p_ID_SORTEO_L1LIAB01_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    SELECT @p_ID_SORTEO_L1LIAB01_out = ID_SORTEO_L1LIAB01
    FROM WSXML_SFG.SORTEO_L1LIAB01 WHERE COD_CONTROL_L1LIAB01 = @p_COD_CONTROL_L1LIAB01 AND SORTEO = @p_SORTEO;
  
	IF @@ROWCOUNT = 0
      SET @p_ID_SORTEO_L1LIAB01_out = 0;
  END;
GO






