USE SFGPRODU;
--  DDL for Package Body SFGTIPONOREFERENCIADO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGTIPONOREFERENCIADO */ 

  IF OBJECT_ID('WSXML_SFG.SFGTIPONOREFERENCIADO_CONSTANT', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPONOREFERENCIADO_CONSTANT;
GO

CREATE  PROCEDURE WSXML_SFG.SFGTIPONOREFERENCIADO_CONSTANT(
  @p_HUERFANOREFERENCIA TINYINT OUTPUT,
  @p_PAGOGLOBAL         TINYINT OUTPUT,
  @p_REPORTADOASISTENCI TINYINT OUTPUT,
  @p_PARTIDENTIFIMANUAL TINYINT OUTPUT,
  @p_PARTSINREFAUTOMATC TINYINT OUTPUT,
  @p_HUERFANOVALORNOCOR TINYINT OUTPUT
) AS
  BEGIN
  SET NOCOUNT ON;
	
	SET @p_HUERFANOREFERENCIA  = 1
	SET @p_PAGOGLOBAL          = 2
	SET @p_REPORTADOASISTENCI  = 3
	SET @p_PARTIDENTIFIMANUAL  = 4
	SET @p_PARTSINREFAUTOMATC  = 5
	SET @p_HUERFANOVALORNOCOR  = 6
 END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGTIPONOREFERENCIADO_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPONOREFERENCIADO_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGTIPONOREFERENCIADO_GetRecord(@pk_ID_TIPONOREFERENCIADO NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
   
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.TIPONOREFERENCIADO WHERE ID_TIPONOREFERENCIADO = @pk_ID_TIPONOREFERENCIADO;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
	
      SELECT ID_TIPONOREFERENCIADO, NOMTIPONOREFERENCIADO FROM WSXML_SFG.TIPONOREFERENCIADO
      WHERE ID_TIPONOREFERENCIADO = @pk_ID_TIPONOREFERENCIADO;
	
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGTIPONOREFERENCIADO_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPONOREFERENCIADO_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGTIPONOREFERENCIADO_GetList AS
  BEGIN
  SET NOCOUNT ON;
   
      SELECT ID_TIPONOREFERENCIADO, NOMTIPONOREFERENCIADO FROM WSXML_SFG.TIPONOREFERENCIADO;
   
  END;
GO






