USE SFGPRODU;
--  DDL for Package Body SFGTIPONOTIFICACION
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGTIPONOTIFICACION */ 

IF OBJECT_ID('WSXML_SFG.SFGTIPONOTIFICACION_CONSTANT', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPONOTIFICACION_CONSTANT;
GO


CREATE PROCEDURE WSXML_SFG.SFGTIPONOTIFICACION_CONSTANT(
	@p_EMAIL TINYINT OUT,
	@p_SMS TINYINT OUT
    )
AS
BEGIN
SET NOCOUNT ON;
    
    -- Return the number output parameter
	SET @p_EMAIL = 1;
	SET @p_SMS = 2;

END;
GO


IF OBJECT_ID('WSXML_SFG.SFGTIPONOTIFICACION_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPONOTIFICACION_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGTIPONOTIFICACION_AddRecord(@p_NOMTIPONOTIFICACION     NVARCHAR(2000),
                      @p_CODUSUARIOMODIFICACION  NUMERIC(22,0),
                      @p_ID_TIPONOTIFICACION_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.TIPONOTIFICACION (
                                  NOMTIPONOTIFICACION,
                                  CODUSUARIOMODIFICACION)
    VALUES (
            @p_NOMTIPONOTIFICACION,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_TIPONOTIFICACION_out = SCOPE_IDENTITY();
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGTIPONOTIFICACION_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPONOTIFICACION_UpdateRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGTIPONOTIFICACION_UpdateRecord(@pk_ID_TIPONOTIFICACION   NUMERIC(22,0),
                         @p_NOMTIPONOTIFICACION    NVARCHAR(2000),
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.TIPONOTIFICACION
       SET NOMTIPONOTIFICACION    = @p_NOMTIPONOTIFICACION,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           FECHAHORAMODIFICACION  = GETDATE(),
           ACTIVE                 = @p_ACTIVE
     WHERE ID_TIPONOTIFICACION = @pk_ID_TIPONOTIFICACION;

	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT;
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGTIPONOTIFICACION_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPONOTIFICACION_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGTIPONOTIFICACION_GetRecord(@pk_ID_TIPONOTIFICACION NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.TIPONOTIFICACION WHERE ID_TIPONOTIFICACION = @pk_ID_TIPONOTIFICACION;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

      SELECT ID_TIPONOTIFICACION,
             NOMTIPONOTIFICACION,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.TIPONOTIFICACION
       WHERE ID_TIPONOTIFICACION = @pk_ID_TIPONOTIFICACION;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGTIPONOTIFICACION_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPONOTIFICACION_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGTIPONOTIFICACION_GetList(@p_active NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT ID_TIPONOTIFICACION,
             NOMTIPONOTIFICACION,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.TIPONOTIFICACION
       WHERE ACTIVE = CASE WHEN @p_active = -1 THEN ACTIVE ELSE @p_active END;
  END;
GO






