USE SFGPRODU;
--  DDL for Package Body SFGTIPOPAGO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGTIPOPAGO */ 

  IF OBJECT_ID('WSXML_SFG.SFGTIPOPAGO_CONSTANT', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPOPAGO_CONSTANT;
GO

CREATE     PROCEDURE WSXML_SFG.SFGTIPOPAGO_CONSTANT(
					@REFERENCIADO      			TINYINT OUT,
                    @NOREFRNCIADO         		TINYINT OUT,
                    @MVMNTMAJUSTE 				TINYINT OUT
					
) AS
  BEGIN
  SET NOCOUNT ON;
  SET @REFERENCIADO = 1;
  SET @NOREFRNCIADO = 2;
  SET @MVMNTMAJUSTE = 3;

  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGTIPOPAGO_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPOPAGO_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGTIPOPAGO_GetRecord(@pk_ID_TIPOPAGO NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.TIPOPAGO WHERE ID_TIPOPAGO = @pk_ID_TIPOPAGO;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 

      SELECT ID_TIPOPAGO,
             DESCRIPCION,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.TIPOPAGO
       WHERE ID_TIPOPAGO = @pk_ID_TIPOPAGO;
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGTIPOPAGO_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPOPAGO_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGTIPOPAGO_GetList(@p_ACTIVE NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
      SELECT ID_TIPOPAGO,
             DESCRIPCION,
             FECHAHORAMODIFICACION,
             CODUSUARIOMODIFICACION,
             ACTIVE
        FROM WSXML_SFG.TIPOPAGO
       WHERE ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN ACTIVE ELSE @p_ACTIVE END;
  END;
GO






