USE SFGPRODU;
--  DDL for Package Body SFGTIPOVINCULACIONPAGO
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGTIPOVINCULACIONPAGO */ 
IF OBJECT_ID('WSXML_SFG.SFGTIPOVINCULACIONPAGO_CONSTANT', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPOVINCULACIONPAGO_CONSTANT;
GO

CREATE     PROCEDURE WSXML_SFG.SFGTIPOVINCULACIONPAGO_CONSTANT(@p_PUNTODEVENTA TINYINT OUTPUT, @p_AGRUPACNXNIT TINYINT OUTPUT, @p_AGRUPACNXCAD TINYINT OUTPUT) AS
  BEGIN
  SET NOCOUNT ON;
  
  SET @p_PUNTODEVENTA = 1;
  SET @p_AGRUPACNXNIT = 2;
  SET @p_AGRUPACNXCAD = 3;

  END;
GO

  
IF OBJECT_ID('WSXML_SFG.SFGTIPOVINCULACIONPAGO_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPOVINCULACIONPAGO_GetRecord;
GO
CREATE     PROCEDURE WSXML_SFG.SFGTIPOVINCULACIONPAGO_GetRecord(@pk_ID_TIPOVINCULACIONPAGO NUMERIC(22,0)) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
   
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.TIPOVINCULACIONPAGO WHERE ID_TIPOVINCULACIONPAGO = @pk_ID_TIPOVINCULACIONPAGO;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
	
      SELECT ID_TIPOVINCULACIONPAGO,
             NOMTIPOVINCULACIONPAGO
        FROM WSXML_SFG.TIPOVINCULACIONPAGO
       WHERE ID_TIPOVINCULACIONPAGO = @pk_ID_TIPOVINCULACIONPAGO;
	
  END;
GO

  IF OBJECT_ID('WSXML_SFG.SFGTIPOVINCULACIONPAGO_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPOVINCULACIONPAGO_GetList;
GO
CREATE     PROCEDURE WSXML_SFG.SFGTIPOVINCULACIONPAGO_GetList AS
  BEGIN
  SET NOCOUNT ON;
    
      SELECT ID_TIPOVINCULACIONPAGO,
             NOMTIPOVINCULACIONPAGO
        FROM WSXML_SFG.TIPOVINCULACIONPAGO;
	
  END;
GO






