USE SFGPRODU;
--  DDL for Package Body SFGTIPOTERMINAL
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGTIPOTERMINAL */ 

IF OBJECT_ID('WSXML_SFG.SFGTIPOTERMINAL_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPOTERMINAL_AddRecord;
GO

CREATE     PROCEDURE WSXML_SFG.SFGTIPOTERMINAL_AddRecord(@p_NOMTIPOTERMINAL        NVARCHAR(2000),
                      @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                      @p_ID_TIPOTERMINAL_out    NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO WSXML_SFG.TIPOTERMINAL (
                              NOMTIPOTERMINAL,
                              CODUSUARIOMODIFICACION)
    VALUES (
            @p_NOMTIPOTERMINAL,
            @p_CODUSUARIOMODIFICACION);
    SET @p_ID_TIPOTERMINAL_out = SCOPE_IDENTITY();

  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGTIPOTERMINAL_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPOTERMINAL_UpdateRecord;
GO

CREATE PROCEDURE WSXML_SFG.SFGTIPOTERMINAL_UpdateRecord(@pk_ID_TIPOTERMINAL       NUMERIC(22,0),
                         @p_NOMTIPOTERMINAL        NVARCHAR(2000),
                         @p_CODUSUARIOMODIFICACION NUMERIC(22,0),
                         @p_ACTIVE                 NUMERIC(22,0)) AS
  BEGIN
  SET NOCOUNT ON;
    UPDATE WSXML_SFG.TIPOTERMINAL
       SET NOMTIPOTERMINAL        = @p_NOMTIPOTERMINAL,
           CODUSUARIOMODIFICACION = @p_CODUSUARIOMODIFICACION,
           ACTIVE                 = @p_ACTIVE
     WHERE ID_TIPOTERMINAL = @pk_ID_TIPOTERMINAL;

	DECLARE @rowcount NUMERIC(22,0) = @@ROWCOUNT;
    IF @rowcount = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @rowcount > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
  END;
GO

IF OBJECT_ID('WSXML_SFG.SFGTIPOTERMINAL_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPOTERMINAL_GetRecord;
GO

  CREATE PROCEDURE WSXML_SFG.SFGTIPOTERMINAL_GetRecord(@pk_ID_TIPOTERMINAL NUMERIC(22,0)
                                                       ) AS
 BEGIN
    DECLARE @l_count INTEGER;
   
  SET NOCOUNT ON;
    SELECT @l_count = COUNT(*) FROM WSXML_SFG.TIPOTERMINAL WHERE ID_TIPOTERMINAL = @pk_ID_TIPOTERMINAL;
    IF @l_count = 0 BEGIN
      RAISERROR('-20054 The record no longer exists.', 16, 1);
    END 
    IF @l_count > 1 BEGIN
      RAISERROR('-20053 Duplicate object instances.', 16, 1);
    END 
	
      SELECT ID_TIPOTERMINAL,
             NOMTIPOTERMINAL,
             CODUSUARIOMODIFICACION,
             FECHAHORAMODIFICACION,
             ACTIVE
      FROM WSXML_SFG.TIPOTERMINAL
      WHERE ID_TIPOTERMINAL = @pk_ID_TIPOTERMINAL;
	  
  END;
GO


IF OBJECT_ID('WSXML_SFG.SFGTIPOTERMINAL_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGTIPOTERMINAL_GetList;
GO

  CREATE PROCEDURE WSXML_SFG.SFGTIPOTERMINAL_GetList(@p_ACTIVE NUMERIC(22,0)
                                                     ) AS
  BEGIN
  SET NOCOUNT ON;
  
      SELECT ID_TIPOTERMINAL,
             NOMTIPOTERMINAL,
             CODUSUARIOMODIFICACION,
             FECHAHORAMODIFICACION,
             ACTIVE
      FROM WSXML_SFG.TIPOTERMINAL
      WHERE ACTIVE = CASE WHEN @p_ACTIVE = -1 THEN ACTIVE ELSE @p_ACTIVE END;
	  
  END;
GO






