USE SFGPRODU;
--  DDL for Package Body SFGUSIARCHIVODETALLE
--------------------------------------------------------

  /* PACKAGE BODY WSXML_SFG.SFGUSIARCHIVODETALLE */ 

-- Creates a new record in the TIPORANGO table
IF OBJECT_ID('WSXML_SFG.SFGUSIARCHIVODETALLE_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGUSIARCHIVODETALLE_AddRecord;
GO

CREATE PROCEDURE WSXML_SFG.SFGUSIARCHIVODETALLE_AddRecord(
    @p_CODUSIARCHIVO NUMERIC(22,0),
    @p_NUMEROTRANSACCIONUSI NVARCHAR(2000),
    @p_CODIGOGTECHPRODUCTO NVARCHAR(2000),
    @p_ARRN_SERIAL NVARCHAR(2000),
    @p_PROCESSINGCODE NVARCHAR(2000),
    @p_ANSWERCODE NVARCHAR(2000),
    @p_FECHAHORATRANSACCION DATETIME,
    @p_CODIGOGTECHPUNTODEVENTA NVARCHAR(2000),
    @p_NUMEROTERMINAL NUMERIC(22,0),
    @p_CEDULAPRINCIPAL NVARCHAR(2000),
    @p_CEDULASECUNDARIA NVARCHAR(2000),
    @p_NUMEROAUTORIZACION NUMERIC(22,0),
    @pk_ID_USIARCHIVODETALLE_out NUMERIC(22,0) OUT
    )
AS
BEGIN
SET NOCOUNT ON;
    INSERT
    INTO WSXML_SFG.USIARCHIVODETALLE
        (
            CODUSIARCHIVO,
            NUMEROTRANSACCIONUSI,
            CODIGOGTECHPRODUCTO,
            ARRN_SERIAL,
            PROCESSINGCODE,
            ANSWERCODE,
            FECHAHORATRANSACCION,
            CODIGOGTECHPUNTODEVENTA,
            NUMEROTERMINAL,
            CEDULAPRINCIPAL,
            CEDULASECUNDARIA,
            NUMEROAUTORIZACION
        )
    VALUES
        (
            @p_CODUSIARCHIVO,
            @p_NUMEROTRANSACCIONUSI,
            @p_CODIGOGTECHPRODUCTO,
            @p_ARRN_SERIAL,
            @p_PROCESSINGCODE,
            @p_ANSWERCODE,
            @p_FECHAHORATRANSACCION,
            @p_CODIGOGTECHPUNTODEVENTA,
            @p_NUMEROTERMINAL,
            @p_CEDULAPRINCIPAL,
            @p_CEDULASECUNDARIA,
            @p_NUMEROAUTORIZACION 
        );
       SET
            @pk_ID_USIARCHIVODETALLE_out = SCOPE_IDENTITY();
END;
GO

-- Updates a record in the TIPORANGO table.
IF OBJECT_ID('WSXML_SFG.SFGUSIARCHIVODETALLE_UpdateRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGUSIARCHIVODETALLE_UpdateRecord;
GO

CREATE PROCEDURE WSXML_SFG.SFGUSIARCHIVODETALLE_UpdateRecord(
    @pk_ID_USIARCHIVODETALLE NUMERIC(22,0),
    @p_CODUSIARCHIVO NUMERIC(22,0),
    @p_NUMEROTRANSACCIONUSI NVARCHAR(2000),
    @p_CODIGOGTECHPRODUCTO NVARCHAR(2000),
    @p_ARRN_SERIAL NVARCHAR(2000),
    @p_PROCESSINGCODE NVARCHAR(2000),
    @p_ANSWERCODE NVARCHAR(2000),
    @p_FECHAHORATRANSACCION DATETIME,
    @p_CODIGOGTECHPUNTODEVENTA NVARCHAR(2000),
    @p_NUMEROTERMINAL NVARCHAR(2000),
    @p_CEDULAPRINCIPAL NVARCHAR(2000),
    @p_CEDULASECUNDARIA NVARCHAR(2000),
    @p_NUMEROAUTORIZACION NUMERIC(22,0)
    )
AS
BEGIN
SET NOCOUNT ON;
    -- Update the record with the passed parameters
    UPDATE WSXML_SFG.USIARCHIVODETALLE
    SET 
           CODUSIARCHIVO = @p_CODUSIARCHIVO,
            NUMEROTRANSACCIONUSI = @p_NUMEROTRANSACCIONUSI,
            CODIGOGTECHPRODUCTO = @p_CODIGOGTECHPRODUCTO,
            ARRN_SERIAL = @p_ARRN_SERIAL,
            PROCESSINGCODE = @p_PROCESSINGCODE,
            ANSWERCODE = @p_ANSWERCODE,
            FECHAHORATRANSACCION = @p_FECHAHORATRANSACCION,
            CODIGOGTECHPUNTODEVENTA = @p_CODIGOGTECHPUNTODEVENTA,
            NUMEROTERMINAL = @p_NUMEROTERMINAL,
            CEDULAPRINCIPAL = @p_CEDULAPRINCIPAL,
            CEDULASECUNDARIA = @p_CEDULASECUNDARIA,
            NUMEROAUTORIZACION = @p_NUMEROAUTORIZACION
     WHERE ID_USIARCHIVODETALLE = @pk_ID_USIARCHIVODETALLE;

    -- Make sure only one record is affected
    IF @@rowcount = 0
    BEGIN
        RAISERROR ('-20054 The record no longer exists.', 16, 1);
    END 
    IF @@rowcount > 1
    BEGIN
        RAISERROR ('-20053 Duplicate object instances.', 16, 1);
    END 

END;
GO

-- Deletes a record from the TIPORANGO table.
IF OBJECT_ID('WSXML_SFG.SFGUSIARCHIVODETALLE_DeleteRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGUSIARCHIVODETALLE_DeleteRecord;
GO

CREATE PROCEDURE WSXML_SFG.SFGUSIARCHIVODETALLE_DeleteRecord(
    @pk_ID_USIARCHIVODETALLE NUMERIC(22,0)
    )
AS
BEGIN
SET NOCOUNT ON;
    DELETE WSXML_SFG.USIARCHIVODETALLE
    WHERE ID_USIARCHIVODETALLE = @pk_ID_USIARCHIVODETALLE;
END;
GO

IF OBJECT_ID('WSXML_SFG.SFGUSIARCHIVODETALLE_GetRecord', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGUSIARCHIVODETALLE_GetRecord;
GO

CREATE PROCEDURE WSXML_SFG.SFGUSIARCHIVODETALLE_GetRecord(
   @pk_ID_USIARCHIVODETALLE NUMERIC(22,0)

    )
AS
BEGIN
    DECLARE @l_count INTEGER;
 
SET NOCOUNT ON;

    -- Get the rowcount first and make sure 
    -- only one row is returned
    SELECT @l_count = count(*)
    FROM WSXML_SFG.USIARCHIVODETALLE
    WHERE ID_USIARCHIVODETALLE = @pk_ID_USIARCHIVODETALLE;

    IF @l_count = 0
    BEGIN
        RAISERROR ('-20054 The record no longer exists.', 16, 1);
    END 

    IF @l_count > 1
    BEGIN
        RAISERROR ('-20053 Duplicate object instances.', 16, 1);
    END 

    -- Get the row from the query.  Checksum value will be
    -- returned along the row data to support concurrency.
         
	     SELECT 
            ID_USIARCHIVODETALLE,
            CODUSIARCHIVO,
            NUMEROTRANSACCIONUSI,
            CODIGOGTECHPRODUCTO,
            ARRN_SERIAL,
            PROCESSINGCODE,
            ANSWERCODE,
            FECHAHORATRANSACCION,
            CODIGOGTECHPUNTODEVENTA,
            NUMEROTERMINAL,
            CEDULAPRINCIPAL,
            CEDULASECUNDARIA,
            NUMEROAUTORIZACION
         FROM WSXML_SFG.USIARCHIVODETALLE
         WHERE ID_USIARCHIVODETALLE = @pk_ID_USIARCHIVODETALLE; 
	    
END;
GO

IF OBJECT_ID('WSXML_SFG.SFGUSIARCHIVODETALLE_GetList', 'P') IS NOT NULL
  DROP PROCEDURE WSXML_SFG.SFGUSIARCHIVODETALLE_GetList;
GO
CREATE PROCEDURE WSXML_SFG.SFGUSIARCHIVODETALLE_GetList
AS
 BEGIN
 SET NOCOUNT ON;
                   select 
           USIARCHIVODETALLE.ID_USIARCHIVODETALLE,
           USIARCHIVODETALLE.CODUSIARCHIVO,
           USIARCHIVODETALLE.NUMEROTRANSACCIONUSI,
           USIARCHIVODETALLE.CODIGOGTECHPRODUCTO,
           USIARCHIVODETALLE.ARRN_SERIAL,
           USIARCHIVODETALLE.PROCESSINGCODE,
           USIARCHIVODETALLE.ANSWERCODE,
           USIARCHIVODETALLE.FECHAHORATRANSACCION,
           USIARCHIVODETALLE.CODIGOGTECHPUNTODEVENTA,
           USIARCHIVODETALLE.NUMEROTERMINAL,
           USIARCHIVODETALLE.CEDULAPRINCIPAL,
           USIARCHIVODETALLE.CEDULASECUNDARIA,
           USIARCHIVODETALLE.NUMEROAUTORIZACION
          from WSXML_SFG.USIARCHIVODETALLE;
END;
GO






