USE SFGPRODU;
--  DDL for Package Body SFGCONCIWEBENTRADA_FOOTER_PROC
--------------------------------------------------------

/* PACKAGE BODY SFG_CONCILIACION.SFGCONCIWEBENTRADA_FOOTER_PROC */ 

  -- Creates a new record in the ENTRADA_FOOTER_CITI table
IF OBJECT_ID('SFG_CONCILIACION.SFGCONCIWEBENTRADA_FOOTER_PROC_AddRecord', 'P') IS NOT NULL
	DROP PROCEDURE SFG_CONCILIACION.SFGCONCIWEBENTRADA_FOOTER_PROC_AddRecord;
GO

CREATE	PROCEDURE SFG_CONCILIACION.SFGCONCIWEBENTRADA_FOOTER_PROC_AddRecord(
	@p_CODCONTROL_ARCHIVOS_ALI    NUMERIC(22,0),
	@p_PRO_03_REC_TYPE            NUMERIC(22,0),
	@p_PRO_03_REC_COUNT           NUMERIC(22,0),
	@p_PRO_03_VALUE_SUM           NUMERIC(22,0),
	@p_ID_ENTRADA_FOOTER_PROC_out NUMERIC(22,0) OUT
) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO SFG_CONCILIACION.ENTRADA_FOOTER_PROC
      (
       CODCONTROL_ARCHIVOS_ALI,
       PRO_03_REC_TYPE,
       PRO_03_REC_COUNT,
       PRO_03_VALUE_SUM)
    VALUES
      (
       @p_CODCONTROL_ARCHIVOS_ALI,
       @p_PRO_03_REC_TYPE,
       @p_PRO_03_REC_COUNT,
       @p_PRO_03_VALUE_SUM);
    SET @p_ID_ENTRADA_FOOTER_PROC_out = SCOPE_IDENTITY();

  END;
GO







