USE SFGPRODU;
--  DDL for Package Body SFGCONCIWEBENTRADA_HEAD_EMCALI
--------------------------------------------------------

  /* PACKAGE BODY SFG_CONCILIACION.SFGCONCIWEBENTRADA_HEAD_EMCALI */ 

  -- Creates a new record in the ENTRADA_HEADER_PROC table
  IF OBJECT_ID('SFG_CONCILIACION.SFGCONCIWEBENTRADA_HEAD_EMCALI_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE SFG_CONCILIACION.SFGCONCIWEBENTRADA_HEAD_EMCALI_AddRecord;
GO

CREATE     PROCEDURE SFG_CONCILIACION.SFGCONCIWEBENTRADA_HEAD_EMCALI_AddRecord(@p_COD_CONTROL_ARCHIVOS_ALI     NUMERIC(22,0),
                      @p_EMCALI_01_REC_TYPE           NUMERIC(22,0),
                      @p_EMCALI_01_NIT_EMCALI         VARCHAR(4000),
                      @p_EMCALI_01_BUS_DATE           DATETIME,
                      @p_EMCALI_01_COD_GTECH          VARCHAR(4000),
                      @p_EMCALI_01_CTA_EMCALI         VARCHAR(4000),
                      @p_ID_ENTRADA_HEADER_EMCALI_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO SFG_CONCILIACION.ENTRADA_HEADER_EMCALI
      (
       COD_CONTROL_ARCHIVOS_ALI,
       EMCALI_01_REC_TYPE,
       EMCALI_01_NIT_EMCALI,
       EMCALI_01_BUS_DATE,
       EMCALI_01_COD_GTECH,
       EMCALI_01_CTA_EMCALI)
    VALUES
      (
       @p_COD_CONTROL_ARCHIVOS_ALI,
       @p_EMCALI_01_REC_TYPE,
       @p_EMCALI_01_NIT_EMCALI,
       @p_EMCALI_01_BUS_DATE,
       @p_EMCALI_01_COD_GTECH,
       @p_EMCALI_01_CTA_EMCALI);
    SET @p_ID_ENTRADA_HEADER_EMCALI_out = SCOPE_IDENTITY();

  END;
GO






