USE SFGPRODU;
--  DDL for Package Body SFGCONCIWEBENTRADA_HEADER_PROC
--------------------------------------------------------

  /* PACKAGE BODY SFG_CONCILIACION.SFGCONCIWEBENTRADA_HEADER_PROC */ 

  -- Creates a new record in the ENTRADA_HEADER_PROC table
IF OBJECT_ID('SFG_CONCILIACION.SFGCONCIWEBENTRADA_HEADER_PROC_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE SFG_CONCILIACION.SFGCONCIWEBENTRADA_HEADER_PROC_AddRecord;
GO

CREATE     PROCEDURE SFG_CONCILIACION.SFGCONCIWEBENTRADA_HEADER_PROC_AddRecord(@p_COD_CONTROL_ARCHIVOS_ALI   NUMERIC(22,0),
                      @p_PRO_01_REC_TYPE            NUMERIC(22,0),
                      @p_PRO_01_COD_GTECH           VARCHAR(4000),
                      @p_PRO_01_BUS_DATE            DATETIME,
                      @p_PRO_01_ENTITY_DESC         VARCHAR(4000),
                      @p_ID_ENTRADA_HEADER_PROC_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO SFG_CONCILIACION.ENTRADA_HEADER_PROC
      (
       COD_CONTROL_ARCHIVOS_ALI,
       PRO_01_REC_TYPE,
       PRO_01_COD_GTECH,
       PRO_01_BUS_DATE,
       PRO_01_ENTITY_DESC)
    VALUES
      (
       @p_COD_CONTROL_ARCHIVOS_ALI,
       @p_PRO_01_REC_TYPE,
       @p_PRO_01_COD_GTECH,
       @p_PRO_01_BUS_DATE,
       @p_PRO_01_ENTITY_DESC);
    SET @p_ID_ENTRADA_HEADER_PROC_out = SCOPE_IDENTITY();

  END;

