USE SFGPRODU;
--  DDL for Package Body SFGCONCIWEBENTRADA_FOOT_EMCALI
--------------------------------------------------------

  /* PACKAGE BODY SFG_CONCILIACION.SFGCONCIWEBENTRADA_FOOT_EMCALI */ 

  -- Creates a new record in the ENTRADA_FOOTER_CITI table
  IF OBJECT_ID('SFG_CONCILIACION.SFGCONCIWEBENTRADA_FOOT_EMCALI_AddRecord', 'P') IS NOT NULL
  DROP PROCEDURE SFG_CONCILIACION.SFGCONCIWEBENTRADA_FOOT_EMCALI_AddRecord;
GO

CREATE     PROCEDURE SFG_CONCILIACION.SFGCONCIWEBENTRADA_FOOT_EMCALI_AddRecord(@p_CODCONTROL_ARCHIVOS_ALI      NUMERIC(22,0),
                      @p_EMCALI_09_REC_TYPE           NUMERIC(22,0),
                      @p_EMCALI_09_REC_COUNT          NUMERIC(22,0),
                      @p_EMCALI_09_VALUE_SUM          NUMERIC(22,0),
                      @p_ID_ENTRADA_FOOTER_EMCALI_out NUMERIC(22,0) OUT) AS
  BEGIN
  SET NOCOUNT ON;
    INSERT INTO SFG_CONCILIACION.ENTRADA_FOOTER_EMCALI
      (
       CODCONTROL_ARCHIVOS_ALI,
       EMCALI_09_REC_TYPE,
       EMCALI_09_REC_COUNT,
       EMCALI_09_VALUE_SUM)
    VALUES
      (
       @p_CODCONTROL_ARCHIVOS_ALI,
       @p_EMCALI_09_REC_TYPE,
       @p_EMCALI_09_REC_COUNT,
       @p_EMCALI_09_VALUE_SUM);
    SET @p_ID_ENTRADA_FOOTER_EMCALI_out = SCOPE_IDENTITY();

  END;

